// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// TodoEdgeFields provides type-safe field selection for TodoEdge
type TodoEdgeFields struct {
	selection *builder.FieldSelection
}

// NewTodoEdgeFields creates a new TodoEdgeFields selector
func NewTodoEdgeFields(selection *builder.FieldSelection) *TodoEdgeFields {
	return &TodoEdgeFields{selection: selection}
}

// Cursor selects the cursor field
func (f *TodoEdgeFields) Cursor() *TodoEdgeFields {
	f.selection.AddField("cursor")
	return f
}

// Node selects the node field with nested selection
func (f *TodoEdgeFields) Node(selector func(*TodoFields)) *TodoEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewTodoFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}
