// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// TodoFields provides type-safe field selection for Todo
type TodoFields struct {
	selection *builder.FieldSelection
}

// NewTodoFields creates a new TodoFields selector
func NewTodoFields(selection *builder.FieldSelection) *TodoFields {
	return &TodoFields{selection: selection}
}

// ID selects the id field
func (f *TodoFields) ID() *TodoFields {
	f.selection.AddField("id")
	return f
}

// Text selects the text field
func (f *TodoFields) Text() *TodoFields {
	f.selection.AddField("text")
	return f
}

// Done selects the done field
func (f *TodoFields) Done() *TodoFields {
	f.selection.AddField("done")
	return f
}

// Priority selects the priority field
func (f *TodoFields) Priority() *TodoFields {
	f.selection.AddField("priority")
	return f
}

// Tags selects the tags field
func (f *TodoFields) Tags() *TodoFields {
	f.selection.AddField("tags")
	return f
}

// User selects the user field with nested selection
func (f *TodoFields) User(selector func(*UserFields)) *TodoFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}
