// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// NodeFields provides type-safe field selection for Node
type NodeFields struct {
	selection *builder.FieldSelection
}

// NewNodeFields creates a new NodeFields selector
func NewNodeFields(selection *builder.FieldSelection) *NodeFields {
	return &NodeFields{selection: selection}
}

// ID selects the id field
func (f *NodeFields) ID() *NodeFields {
	f.selection.AddField("id")
	return f
}
