// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// PageInfoFields provides type-safe field selection for PageInfo
type PageInfoFields struct {
	selection *builder.FieldSelection
}

// NewPageInfoFields creates a new PageInfoFields selector
func NewPageInfoFields(selection *builder.FieldSelection) *PageInfoFields {
	return &PageInfoFields{selection: selection}
}

// HasNextPage selects the hasNextPage field
func (f *PageInfoFields) HasNextPage() *PageInfoFields {
	f.selection.AddField("hasNextPage")
	return f
}

// HasPreviousPage selects the hasPreviousPage field
func (f *PageInfoFields) HasPreviousPage() *PageInfoFields {
	f.selection.AddField("hasPreviousPage")
	return f
}

// StartCursor selects the startCursor field
func (f *PageInfoFields) StartCursor() *PageInfoFields {
	f.selection.AddField("startCursor")
	return f
}

// EndCursor selects the endCursor field
func (f *PageInfoFields) EndCursor() *PageInfoFields {
	f.selection.AddField("endCursor")
	return f
}
