// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// UserFields provides type-safe field selection for User
type UserFields struct {
	selection *builder.FieldSelection
}

// NewUserFields creates a new UserFields selector
func NewUserFields(selection *builder.FieldSelection) *UserFields {
	return &UserFields{selection: selection}
}

// ID selects the id field
func (f *UserFields) ID() *UserFields {
	f.selection.AddField("id")
	return f
}

// Name selects the name field
func (f *UserFields) Name() *UserFields {
	f.selection.AddField("name")
	return f
}

// Email selects the email field
func (f *UserFields) Email() *UserFields {
	f.selection.AddField("email")
	return f
}

// Role selects the role field
func (f *UserFields) Role() *UserFields {
	f.selection.AddField("role")
	return f
}
