// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample_gqlgenapi/sdk/builder"
)

// TodoConnectionFields provides type-safe field selection for TodoConnection
type TodoConnectionFields struct {
	selection *builder.FieldSelection
}

// NewTodoConnectionFields creates a new TodoConnectionFields selector
func NewTodoConnectionFields(selection *builder.FieldSelection) *TodoConnectionFields {
	return &TodoConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *TodoConnectionFields) Edges(selector func(*TodoEdgeFields)) *TodoConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewTodoEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *TodoConnectionFields) PageInfo(selector func(*PageInfoFields)) *TodoConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *TodoConnectionFields) TotalCount() *TodoConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
