// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample_gqlgenapi/sdk/builder"
	"sdkexample_gqlgenapi/sdk/fields"
	"sdkexample_gqlgenapi/sdk/types"
)

// UsersBuilder builds a query for users
type UsersBuilder struct {
	*builder.BaseBuilder
}

// Select configures which fields to return
func (b *UsersBuilder) Select(selector func(*fields.UserFields)) *UsersBuilder {
	selector(fields.NewUserFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *UsersBuilder) Execute(ctx context.Context) ([]types.User, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.User `json:"users"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
