// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample_gqlgenapi/sdk/builder"
	"sdkexample_gqlgenapi/sdk/fields"
	"sdkexample_gqlgenapi/sdk/inputs"
	"sdkexample_gqlgenapi/sdk/types"
)

// TodosBuilder builds a query for todos
type TodosBuilder struct {
	*builder.BaseBuilder
}

// Filter sets the filter argument
func (b *TodosBuilder) Filter(v *inputs.TodoFilter) *TodosBuilder {
	b.SetArg("filter", v, "TodoFilter")
	return b
}

// Pagination sets the pagination argument
func (b *TodosBuilder) Pagination(v *inputs.PaginationInput) *TodosBuilder {
	b.SetArg("pagination", v, "PaginationInput")
	return b
}

// Select configures which fields to return
func (b *TodosBuilder) Select(selector func(*fields.TodoFields)) *TodosBuilder {
	selector(fields.NewTodoFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *TodosBuilder) Execute(ctx context.Context) ([]types.Todo, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.Todo `json:"todos"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
