// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample_gqlgenapi/sdk/builder"
)

// SumBuilder builds a query for sum
type SumBuilder struct {
	*builder.BaseBuilder
}

// A sets the a argument
func (b *SumBuilder) A(v int) *SumBuilder {
	b.SetArg("a", v, "Int!")
	return b
}

// B sets the b argument
func (b *SumBuilder) B(v int) *SumBuilder {
	b.SetArg("b", v, "Int!")
	return b
}

// Execute runs the query and returns the result
func (b *SumBuilder) Execute(ctx context.Context) (int, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result int `json:"sum"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return 0, err
	}

	return response.Result, nil
}
