// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample_gqlgenapi/sdk/builder"
)

// SearchBuilder builds a query for search
type SearchBuilder struct {
	*builder.BaseBuilder
}

// Term sets the term argument
func (b *SearchBuilder) Term(v string) *SearchBuilder {
	b.SetArg("term", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *SearchBuilder) Execute(ctx context.Context) ([]interface{}, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []interface{} `json:"search"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
