// Code generated by gqlcustom. DO NOT EDIT.

package queries

import "sdkexample_gqlgenapi/sdk/builder"

// QueryRoot is the entry point for queries
type QueryRoot struct {
	client builder.GraphQLClient
}

// NewQueryRoot creates a new QueryRoot
func NewQueryRoot(client builder.GraphQLClient) *QueryRoot {
	return &QueryRoot{client: client}
}

// Ping creates a new PingBuilder
func (q *QueryRoot) Ping() *PingBuilder {
	return &PingBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Ping", "ping"),
	}
}

// Todo creates a new TodoBuilder
func (q *QueryRoot) Todo() *TodoBuilder {
	return &TodoBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Todo", "todo"),
	}
}

// Todos creates a new TodosBuilder
func (q *QueryRoot) Todos() *TodosBuilder {
	return &TodosBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Todos", "todos"),
	}
}

// TodosConnection creates a new TodosConnectionBuilder
func (q *QueryRoot) TodosConnection() *TodosConnectionBuilder {
	return &TodosConnectionBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "TodosConnection", "todosConnection"),
	}
}

// User creates a new UserBuilder
func (q *QueryRoot) User() *UserBuilder {
	return &UserBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "User", "user"),
	}
}

// Users creates a new UsersBuilder
func (q *QueryRoot) Users() *UsersBuilder {
	return &UsersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Users", "users"),
	}
}

// Search creates a new SearchBuilder
func (q *QueryRoot) Search() *SearchBuilder {
	return &SearchBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Search", "search"),
	}
}

// Echo creates a new EchoBuilder
func (q *QueryRoot) Echo() *EchoBuilder {
	return &EchoBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Echo", "echo"),
	}
}

// Sum creates a new SumBuilder
func (q *QueryRoot) Sum() *SumBuilder {
	return &SumBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Sum", "sum"),
	}
}
