// Code generated by ent, DO NOT EDIT.

package enums

// Role is a GraphQL enum type
type Role string

// Role enum values
const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
	RoleGuest Role = "GUEST"
)
