// Code generated by ent, DO NOT EDIT.

package types

import (
	"encoding/json"
	"gqlcustom/sdk/scalars"
	"time"
)

// AiModel represents the GraphQL type AiModel
type AiModel struct {
	ID              string            `json:"id"`
	Createdat       *time.Time        `json:"createdat,omitempty"`
	Updatedat       *time.Time        `json:"updatedat,omitempty"`
	Name            *string           `json:"name,omitempty"`
	Providername    string            `json:"providername"`
	Modelid         string            `json:"modelid"`
	Baseurl         *string           `json:"baseurl,omitempty"`
	Apikey          *scalars.Password `json:"apikey,omitempty"`
	Orgid           *string           `json:"orgid,omitempty"`
	Descr           *string           `json:"descr,omitempty"`
	Status          *bool             `json:"status,omitempty"`
	Workspaceid     *string           `json:"workspaceid,omitempty"`
	Haschat         *bool             `json:"haschat,omitempty"`
	Hasembeddings   *bool             `json:"hasembeddings,omitempty"`
	Iswildai        *bool             `json:"iswildai,omitempty"`
	Intprovidername *string           `json:"intprovidername,omitempty"`
	Intbaseurl      *string           `json:"intbaseurl,omitempty"`
	Intapikey       *scalars.Password `json:"intapikey,omitempty"`
	Intorgid        *string           `json:"intorgid,omitempty"`
	Intmodelid      *string           `json:"intmodelid,omitempty"`
	Maxdims         *int              `json:"maxdims,omitempty"`
	Maxtokens       *int              `json:"maxtokens,omitempty"`
	Chatbots        []Chatbot         `json:"chatbots,omitempty"`
	Functools       []FuncTool        `json:"functools,omitempty"`
	Itemgroups      []ItemGroup       `json:"itemgroups,omitempty"`
}

// AiModelConnection A connection to a list of items.

type AiModelConnection struct {
	// A list of edges.
	Edges []*AiModelEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// AiModelEdge An edge in a connection.

type AiModelEdge struct {
	// The item at the end of the edge.
	Node *AiModel `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// AppSessionResponse represents the GraphQL type AppSessionResponse
type AppSessionResponse struct {
	Sessiontoken string    `json:"sessiontoken"`
	Launchurl    string    `json:"launchurl"`
	Expiresat    time.Time `json:"expiresat"`
}

// AppStoreApp represents the GraphQL type AppStoreApp
type AppStoreApp struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	Iconurl     *string         `json:"iconurl,omitempty"`
	Partner     AppStorePartner `json:"partner"`
}

// AppStorePartner represents the GraphQL type AppStorePartner
type AppStorePartner struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Companyname *string `json:"companyname,omitempty"`
}

// BillingFeature represents the GraphQL type BillingFeature
type BillingFeature struct {
	ID                      string                   `json:"id"`
	Createdat               *time.Time               `json:"createdat,omitempty"`
	Updatedat               *time.Time               `json:"updatedat,omitempty"`
	Name                    string                   `json:"name"`
	Groupname               *string                  `json:"groupname,omitempty"`
	Isactive                bool                     `json:"isactive"`
	Defaultvalue            *int                     `json:"defaultvalue,omitempty"`
	Unittype                *string                  `json:"unittype,omitempty"`
	Featuretype             *string                  `json:"featuretype,omitempty"`
	Sortorder               *int                     `json:"sortorder,omitempty"`
	Description             *string                  `json:"description,omitempty"`
	Billingplanfeatures     []BillingPlanFeature     `json:"billingplanfeatures,omitempty"`
	Cworkspacefeaturelimits []CWorkspaceFeatureLimit `json:"cworkspacefeaturelimits,omitempty"`
}

// BillingFeatureConnection A connection to a list of items.

type BillingFeatureConnection struct {
	// A list of edges.
	Edges []*BillingFeatureEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// BillingFeatureEdge An edge in a connection.

type BillingFeatureEdge struct {
	// The item at the end of the edge.
	Node *BillingFeature `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// BillingPlan represents the GraphQL type BillingPlan
type BillingPlan struct {
	ID                  string               `json:"id"`
	Createdat           *time.Time           `json:"createdat,omitempty"`
	Updatedat           *time.Time           `json:"updatedat,omitempty"`
	Name                string               `json:"name"`
	Groupname           *string              `json:"groupname,omitempty"`
	Description         *string              `json:"description,omitempty"`
	Isactive            bool                 `json:"isactive"`
	Stripeproductid     *string              `json:"stripeproductid,omitempty"`
	Ismultiqty          bool                 `json:"ismultiqty"`
	Maxqty              *int                 `json:"maxqty,omitempty"`
	Iscustom            bool                 `json:"iscustom"`
	Custompriceid       *string              `json:"custompriceid,omitempty"`
	Plantype            *string              `json:"plantype,omitempty"`
	Hasannual           bool                 `json:"hasannual"`
	Stripepriceid       *string              `json:"stripepriceid,omitempty"`
	Stripepriceidannual *string              `json:"stripepriceidannual,omitempty"`
	Amount              *float64             `json:"amount,omitempty"`
	Amountannual        *float64             `json:"amountannual,omitempty"`
	Features            *json.RawMessage     `json:"features,omitempty"`
	Sortorder           *int                 `json:"sortorder,omitempty"`
	Billingplanfeatures []BillingPlanFeature `json:"billingplanfeatures,omitempty"`
}

// BillingPlanConnection A connection to a list of items.

type BillingPlanConnection struct {
	// A list of edges.
	Edges []*BillingPlanEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// BillingPlanEdge An edge in a connection.

type BillingPlanEdge struct {
	// The item at the end of the edge.
	Node *BillingPlan `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// BillingPlanFeature represents the GraphQL type BillingPlanFeature
type BillingPlanFeature struct {
	ID             string          `json:"id"`
	Createdat      *time.Time      `json:"createdat,omitempty"`
	Updatedat      *time.Time      `json:"updatedat,omitempty"`
	Featureid      *string         `json:"featureid,omitempty"`
	Value          int             `json:"value"`
	Billingplanid  *string         `json:"billingplanid,omitempty"`
	Billingplan    *BillingPlan    `json:"billingplan,omitempty"`
	Billingfeature *BillingFeature `json:"billingfeature,omitempty"`
}

// BillingPlanFeatureConnection A connection to a list of items.

type BillingPlanFeatureConnection struct {
	// A list of edges.
	Edges []*BillingPlanFeatureEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// BillingPlanFeatureEdge An edge in a connection.

type BillingPlanFeatureEdge struct {
	// The item at the end of the edge.
	Node *BillingPlanFeature `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// BillingPlanWspace represents the GraphQL type BillingPlanWspace
type BillingPlanWspace struct {
	ID            string       `json:"id"`
	Createdat     *time.Time   `json:"createdat,omitempty"`
	Updatedat     *time.Time   `json:"updatedat,omitempty"`
	Billingplanid *string      `json:"billingplanid,omitempty"`
	Workspaceid   *string      `json:"workspaceid,omitempty"`
	Billingplan   *BillingPlan `json:"billingplan,omitempty"`
}

// BillingPlanWspaceConnection A connection to a list of items.

type BillingPlanWspaceConnection struct {
	// A list of edges.
	Edges []*BillingPlanWspaceEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// BillingPlanWspaceEdge An edge in a connection.

type BillingPlanWspaceEdge struct {
	// The item at the end of the edge.
	Node *BillingPlanWspace `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// CWorkspaceFeatureLimit represents the GraphQL type CWorkspaceFeatureLimit
type CWorkspaceFeatureLimit struct {
	ID               string             `json:"id"`
	Createdat        *time.Time         `json:"createdat,omitempty"`
	Updatedat        *time.Time         `json:"updatedat,omitempty"`
	Workspaceid      string             `json:"workspaceid"`
	Billingfeatureid *string            `json:"billingfeatureid,omitempty"`
	Available        int                `json:"available"`
	Used             int                `json:"used"`
	Balance          int                `json:"balance"`
	Calculatedat     time.Time          `json:"calculatedat"`
	Sources          *scalars.JsonSlice `json:"sources,omitempty"`
	Billingfeature   *BillingFeature    `json:"billingfeature,omitempty"`
}

// CWorkspaceFeatureLimitConnection A connection to a list of items.

type CWorkspaceFeatureLimitConnection struct {
	// A list of edges.
	Edges []*CWorkspaceFeatureLimitEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// CWorkspaceFeatureLimitEdge An edge in a connection.

type CWorkspaceFeatureLimitEdge struct {
	// The item at the end of the edge.
	Node *CWorkspaceFeatureLimit `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// CWorkspaceSub represents the GraphQL type CWorkspaceSub
type CWorkspaceSub struct {
	ID                  string       `json:"id"`
	Createdat           *time.Time   `json:"createdat,omitempty"`
	Updatedat           *time.Time   `json:"updatedat,omitempty"`
	Workspaceid         *string      `json:"workspaceid,omitempty"`
	Lock                *bool        `json:"lock,omitempty"`
	Billingplanid       *string      `json:"billingplanid,omitempty"`
	Status              *string      `json:"status,omitempty"`
	Stripestatus        *string      `json:"stripestatus,omitempty"`
	Issubscription      *bool        `json:"issubscription,omitempty"`
	Checkoutsessionid   *string      `json:"checkoutsessionid,omitempty"`
	Amount              *float64     `json:"amount,omitempty"`
	Qty                 *int         `json:"qty,omitempty"`
	Subscriptionid      *string      `json:"subscriptionid,omitempty"`
	Subscriptionitemid  *string      `json:"subscriptionitemid,omitempty"`
	Planinterval        *string      `json:"planinterval,omitempty"`
	Planintervalcount   *int         `json:"planintervalcount,omitempty"`
	Itemid              *string      `json:"itemid,omitempty"`
	Itempriceid         *string      `json:"itempriceid,omitempty"`
	Itemname            *string      `json:"itemname,omitempty"`
	Invoiceid           *string      `json:"invoiceid,omitempty"`
	Invoicelineid       *string      `json:"invoicelineid,omitempty"`
	Invoicenumber       *string      `json:"invoicenumber,omitempty"`
	Currentperiodstart  *string      `json:"currentperiodstart,omitempty"`
	Currentperiodend    *string      `json:"currentperiodend,omitempty"`
	Cancelat            *string      `json:"cancelat,omitempty"`
	Cancelatperiodend   *string      `json:"cancelatperiodend,omitempty"`
	Canceledat          *string      `json:"canceledat,omitempty"`
	Stripecustomerid    *string      `json:"stripecustomerid,omitempty"`
	Stripecustomeremail *string      `json:"stripecustomeremail,omitempty"`
	Lastcheckedat       *time.Time   `json:"lastcheckedat,omitempty"`
	Billingplan         *BillingPlan `json:"billingplan,omitempty"`
}

// CWorkspaceSubConnection A connection to a list of items.

type CWorkspaceSubConnection struct {
	// A list of edges.
	Edges []*CWorkspaceSubEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// CWorkspaceSubEdge An edge in a connection.

type CWorkspaceSubEdge struct {
	// The item at the end of the edge.
	Node *CWorkspaceSub `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Channel represents the GraphQL type Channel
type Channel struct {
	ID           string                `json:"id"`
	Createdat    *time.Time            `json:"createdat,omitempty"`
	Updatedat    *time.Time            `json:"updatedat,omitempty"`
	Name         *string               `json:"name,omitempty"`
	Ispublic     *bool                 `json:"ispublic,omitempty"`
	Guestid      *string               `json:"guestid,omitempty"`
	Ownerid      *string               `json:"ownerid,omitempty"`
	Workspaceid  *string               `json:"workspaceid,omitempty"`
	Chatbotid    *string               `json:"chatbotid,omitempty"`
	Folderid     *string               `json:"folderid,omitempty"`
	Messages     MessageConnection     `json:"messages"`
	Users        UserConnection        `json:"users"`
	Owner        *User                 `json:"owner,omitempty"`
	Chatbot      *Chatbot              `json:"chatbot,omitempty"`
	Folder       *Folder               `json:"folder,omitempty"`
	Channelusers ChannelUserConnection `json:"channelusers"`
}

// ChannelConnection A connection to a list of items.

type ChannelConnection struct {
	// A list of edges.
	Edges []*ChannelEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ChannelEdge An edge in a connection.

type ChannelEdge struct {
	// The item at the end of the edge.
	Node *Channel `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ChannelUser represents the GraphQL type ChannelUser
type ChannelUser struct {
	ID          string     `json:"id"`
	Createdat   *time.Time `json:"createdat,omitempty"`
	Updatedat   *time.Time `json:"updatedat,omitempty"`
	Userid      string     `json:"userid"`
	Channelid   string     `json:"channelid"`
	Workspaceid *string    `json:"workspaceid,omitempty"`
	Chatbotid   *string    `json:"chatbotid,omitempty"`
	User        User       `json:"user"`
	Channel     Channel    `json:"channel"`
}

// ChannelUserConnection A connection to a list of items.

type ChannelUserConnection struct {
	// A list of edges.
	Edges []*ChannelUserEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ChannelUserEdge An edge in a connection.

type ChannelUserEdge struct {
	// The item at the end of the edge.
	Node *ChannelUser `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Chatbot represents the GraphQL type Chatbot
type Chatbot struct {
	ID                 string                `json:"id"`
	Createdat          *time.Time            `json:"createdat,omitempty"`
	Updatedat          *time.Time            `json:"updatedat,omitempty"`
	Name               *string               `json:"name,omitempty"`
	Shortdescr         *string               `json:"shortdescr,omitempty"`
	Active             *bool                 `json:"active,omitempty"`
	Ispublic           *bool                 `json:"ispublic,omitempty"`
	Instruction        *string               `json:"instruction,omitempty"`
	Temperature        *float64              `json:"temperature,omitempty"`
	Overviewdescr      *string               `json:"overviewdescr,omitempty"`
	Totalchars         *int                  `json:"totalchars,omitempty"`
	Text               *string               `json:"text,omitempty"`
	Colorusermessage   *string               `json:"colorusermessage,omitempty"`
	Initialmessage1    *string               `json:"initialmessage1,omitempty"`
	Initialmessage2    *string               `json:"initialmessage2,omitempty"`
	Colorbubble        *string               `json:"colorbubble,omitempty"`
	Chatbuttonalign    *string               `json:"chatbuttonalign,omitempty"`
	Displayname        *string               `json:"displayname,omitempty"`
	Chaticonurl        *string               `json:"chaticonurl,omitempty"`
	Boticonurl         *string               `json:"boticonurl,omitempty"`
	Messageplaceholder *string               `json:"messageplaceholder,omitempty"`
	Footer             *string               `json:"footer,omitempty"`
	Theme              *string               `json:"theme,omitempty"`
	Autoshowpopupafter *int                  `json:"autoshowpopupafter,omitempty"`
	Aimodelid          *string               `json:"aimodelid,omitempty"`
	Sbyteuserid        *string               `json:"sbyteuserid,omitempty"`
	Aiuserid           *string               `json:"aiuserid,omitempty"`
	Workspaceid        *string               `json:"workspaceid,omitempty"`
	Isfavorite         *bool                 `json:"isfavorite,omitempty"`
	Isdebug            *bool                 `json:"isdebug,omitempty"`
	Cachedisabled      *bool                 `json:"cachedisabled,omitempty"`
	Leadnameenabled    *bool                 `json:"leadnameenabled,omitempty"`
	Leademailenabled   *bool                 `json:"leademailenabled,omitempty"`
	Leadphoneenabled   *bool                 `json:"leadphoneenabled,omitempty"`
	Users              []User                `json:"users,omitempty"`
	Channels           []Channel             `json:"channels,omitempty"`
	Folders            []Folder              `json:"folders,omitempty"`
	Functools          FuncToolConnection    `json:"functools"`
	Aimodel            *AiModel              `json:"aimodel,omitempty"`
	Chatbotusers       []ChatbotUser         `json:"chatbotusers,omitempty"`
	Chatbottools       ChatbotToolConnection `json:"chatbottools"`
}

// ChatbotConnection A connection to a list of items.

type ChatbotConnection struct {
	// A list of edges.
	Edges []*ChatbotEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ChatbotEdge An edge in a connection.

type ChatbotEdge struct {
	// The item at the end of the edge.
	Node *Chatbot `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ChatbotTool represents the GraphQL type ChatbotTool
type ChatbotTool struct {
	ID          string     `json:"id"`
	Createdat   *time.Time `json:"createdat,omitempty"`
	Updatedat   *time.Time `json:"updatedat,omitempty"`
	Functoolid  string     `json:"functoolid"`
	Chatbotid   string     `json:"chatbotid"`
	Workspaceid *string    `json:"workspaceid,omitempty"`
	Functool    FuncTool   `json:"functool"`
	Chatbot     Chatbot    `json:"chatbot"`
}

// ChatbotToolConnection A connection to a list of items.

type ChatbotToolConnection struct {
	// A list of edges.
	Edges []*ChatbotToolEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ChatbotToolEdge An edge in a connection.

type ChatbotToolEdge struct {
	// The item at the end of the edge.
	Node *ChatbotTool `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ChatbotUser represents the GraphQL type ChatbotUser
type ChatbotUser struct {
	ID          string     `json:"id"`
	Createdat   *time.Time `json:"createdat,omitempty"`
	Updatedat   *time.Time `json:"updatedat,omitempty"`
	Userid      string     `json:"userid"`
	Chatbotid   string     `json:"chatbotid"`
	Workspaceid *string    `json:"workspaceid,omitempty"`
	User        User       `json:"user"`
	Chatbot     Chatbot    `json:"chatbot"`
}

// ChatbotUserConnection A connection to a list of items.

type ChatbotUserConnection struct {
	// A list of edges.
	Edges []*ChatbotUserEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ChatbotUserEdge An edge in a connection.

type ChatbotUserEdge struct {
	// The item at the end of the edge.
	Node *ChatbotUser `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// CheckoutSession represents the GraphQL type CheckoutSession
type CheckoutSession struct {
	ID    *string `json:"id,omitempty"`
	Value *string `json:"value,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// CheckoutSessionVerify represents the GraphQL type CheckoutSessionVerify
type CheckoutSessionVerify struct {
	Workspaceid     *string `json:"workspaceid,omitempty"`
	Alreadyverified *bool   `json:"alreadyverified,omitempty"`
}

// CreateChatbotResponse represents the GraphQL type CreateChatbotResponse
type CreateChatbotResponse struct {
	Chatbot   Chatbot   `json:"chatbot"`
	Itemgroup ItemGroup `json:"itemgroup"`
}

// Credential represents the GraphQL type Credential
type Credential struct {
	ID             string            `json:"id"`
	Createdat      *time.Time        `json:"createdat,omitempty"`
	Updatedat      *time.Time        `json:"updatedat,omitempty"`
	Name           *string           `json:"name,omitempty"`
	Credentialtype *string           `json:"credentialtype,omitempty"`
	Active         *bool             `json:"active,omitempty"`
	Dbtype         *string           `json:"dbtype,omitempty"`
	Dbname         *string           `json:"dbname,omitempty"`
	Host           *string           `json:"host,omitempty"`
	Port           *uint             `json:"port,omitempty"`
	Username       *string           `json:"username,omitempty"`
	Password       *scalars.Password `json:"password,omitempty"`
	Secret         *scalars.Password `json:"secret,omitempty"`
	Apikey         *scalars.Password `json:"apikey,omitempty"`
	Workspaceid    *string           `json:"workspaceid,omitempty"`
	Functools      []FuncTool        `json:"functools,omitempty"`
}

// CredentialConnection A connection to a list of items.

type CredentialConnection struct {
	// A list of edges.
	Edges []*CredentialEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// CredentialEdge An edge in a connection.

type CredentialEdge struct {
	// The item at the end of the edge.
	Node *Credential `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Folder represents the GraphQL type Folder
type Folder struct {
	ID           string     `json:"id"`
	Createdat    *time.Time `json:"createdat,omitempty"`
	Updatedat    *time.Time `json:"updatedat,omitempty"`
	Name         string     `json:"name"`
	Chatbotid    *string    `json:"chatbotid,omitempty"`
	Ownerid      *string    `json:"ownerid,omitempty"`
	Position     int        `json:"position"`
	Channels     []Channel  `json:"channels,omitempty"`
	Chatbot      *Chatbot   `json:"chatbot,omitempty"`
	Owner        *User      `json:"owner,omitempty"`
	Channelcount int        `json:"channelcount"`
}

// FolderConnection A connection to a list of items.

type FolderConnection struct {
	// A list of edges.
	Edges []*FolderEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// FolderEdge An edge in a connection.

type FolderEdge struct {
	// The item at the end of the edge.
	Node *Folder `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// FuncTool represents the GraphQL type FuncTool
type FuncTool struct {
	ID           string           `json:"id"`
	Createdat    *time.Time       `json:"createdat,omitempty"`
	Updatedat    *time.Time       `json:"updatedat,omitempty"`
	Name         *string          `json:"name,omitempty"`
	Functooltype *string          `json:"functooltype,omitempty"`
	Active       *bool            `json:"active,omitempty"`
	Description  *string          `json:"description,omitempty"`
	Systemprompt *string          `json:"systemprompt,omitempty"`
	Credentialid *string          `json:"credentialid,omitempty"`
	Data         *json.RawMessage `json:"data,omitempty"`
	Aimodelid    *string          `json:"aimodelid,omitempty"`
	Maxtokens    *int             `json:"maxtokens,omitempty"`
	Temperature  *float64         `json:"temperature,omitempty"`
	Itemgroupid  *string          `json:"itemgroupid,omitempty"`
	Limit        *int             `json:"limit,omitempty"`
	Workspaceid  *string          `json:"workspaceid,omitempty"`
	Chatbots     []Chatbot        `json:"chatbots,omitempty"`
	Credential   *Credential      `json:"credential,omitempty"`
	Functoollogs []FuncToolLog    `json:"functoollogs,omitempty"`
	Aimodel      *AiModel         `json:"aimodel,omitempty"`
	Itemgroup    *ItemGroup       `json:"itemgroup,omitempty"`
	Chatbottools []ChatbotTool    `json:"chatbottools,omitempty"`
}

// FuncToolConnection A connection to a list of items.

type FuncToolConnection struct {
	// A list of edges.
	Edges []*FuncToolEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// FuncToolEdge An edge in a connection.

type FuncToolEdge struct {
	// The item at the end of the edge.
	Node *FuncTool `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// FuncToolLog represents the GraphQL type FuncToolLog
type FuncToolLog struct {
	ID          string           `json:"id"`
	Createdat   *time.Time       `json:"createdat,omitempty"`
	Updatedat   *time.Time       `json:"updatedat,omitempty"`
	Toolcallid  *string          `json:"toolcallid,omitempty"`
	Logtype     *string          `json:"logtype,omitempty"`
	Msg         *string          `json:"msg,omitempty"`
	Body        *json.RawMessage `json:"body,omitempty"`
	Functoolid  *string          `json:"functoolid,omitempty"`
	Channelid   *string          `json:"channelid,omitempty"`
	Userid      *string          `json:"userid,omitempty"`
	Workspaceid *string          `json:"workspaceid,omitempty"`
	Chatbotid   *string          `json:"chatbotid,omitempty"`
	Functool    *FuncTool        `json:"functool,omitempty"`
}

// FuncToolLogConnection A connection to a list of items.

type FuncToolLogConnection struct {
	// A list of edges.
	Edges []*FuncToolLogEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// FuncToolLogEdge An edge in a connection.

type FuncToolLogEdge struct {
	// The item at the end of the edge.
	Node *FuncToolLog `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Guest represents the GraphQL type Guest
type Guest struct {
	ID          string     `json:"id"`
	Createdat   *time.Time `json:"createdat,omitempty"`
	Updatedat   *time.Time `json:"updatedat,omitempty"`
	Extuserid   *string    `json:"extuserid,omitempty"`
	Firstname   *string    `json:"firstname,omitempty"`
	Lastname    *string    `json:"lastname,omitempty"`
	Email       *string    `json:"email,omitempty"`
	Ip          *string    `json:"ip,omitempty"`
	Chatbotid   *string    `json:"chatbotid,omitempty"`
	Workspaceid *string    `json:"workspaceid,omitempty"`
}

// GuestConnection A connection to a list of items.

type GuestConnection struct {
	// A list of edges.
	Edges []*GuestEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// GuestEdge An edge in a connection.

type GuestEdge struct {
	// The item at the end of the edge.
	Node *Guest `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// HtmlToMarkdownResponse represents the GraphQL type HtmlToMarkdownResponse
type HtmlToMarkdownResponse struct {
	Content string `json:"content"`
}

// Item represents the GraphQL type Item
type Item struct {
	ID                string                       `json:"id"`
	Createdat         *time.Time                   `json:"createdat,omitempty"`
	Updatedat         *time.Time                   `json:"updatedat,omitempty"`
	Name              *string                      `json:"name,omitempty"`
	Embeddingstatus   *scalars.ItemEmbeddingStatus `json:"embeddingstatus,omitempty"`
	Embeddingmsg      *string                      `json:"embeddingmsg,omitempty"`
	Content           *string                      `json:"content,omitempty"`
	Filename          *string                      `json:"filename,omitempty"`
	Contentchars      *int                         `json:"contentchars,omitempty"`
	Aimodelid         *string                      `json:"aimodelid,omitempty"`
	Vecdims           *int                         `json:"vecdims,omitempty"`
	Totaltokens       *int                         `json:"totaltokens,omitempty"`
	Metadata          *json.RawMessage             `json:"metadata,omitempty"`
	Extref            *string                      `json:"extref,omitempty"`
	Extid             *string                      `json:"extid,omitempty"`
	Extmetadata       *json.RawMessage             `json:"extmetadata,omitempty"`
	Workspaceid       *string                      `json:"workspaceid,omitempty"`
	Chatbotid         *string                      `json:"chatbotid,omitempty"`
	Itemgroupsourceid *string                      `json:"itemgroupsourceid,omitempty"`
	Itemgroupid       *string                      `json:"itemgroupid,omitempty"`
}

// ItemConnection A connection to a list of items.

type ItemConnection struct {
	// A list of edges.
	Edges []*ItemEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ItemEdge An edge in a connection.

type ItemEdge struct {
	// The item at the end of the edge.
	Node *Item `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ItemGroup represents the GraphQL type ItemGroup
type ItemGroup struct {
	ID               string                    `json:"id"`
	Createdat        *time.Time                `json:"createdat,omitempty"`
	Updatedat        *time.Time                `json:"updatedat,omitempty"`
	Name             *string                   `json:"name,omitempty"`
	Shortdescr       *string                   `json:"shortdescr,omitempty"`
	Aimodelid        *string                   `json:"aimodelid,omitempty"`
	Dims             *int                      `json:"dims,omitempty"`
	Haspendingitems  *bool                     `json:"haspendingitems,omitempty"`
	Locked           *bool                     `json:"locked,omitempty"`
	Workspaceid      *string                   `json:"workspaceid,omitempty"`
	Itemgroupsources ItemGroupSourceConnection `json:"itemgroupsources"`
	Functools        []FuncTool                `json:"functools,omitempty"`
	Aimodel          *AiModel                  `json:"aimodel,omitempty"`
}

// ItemGroupConnection A connection to a list of items.

type ItemGroupConnection struct {
	// A list of edges.
	Edges []*ItemGroupEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ItemGroupEdge An edge in a connection.

type ItemGroupEdge struct {
	// The item at the end of the edge.
	Node *ItemGroup `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ItemGroupSource represents the GraphQL type ItemGroupSource
type ItemGroupSource struct {
	ID                  string                                 `json:"id"`
	Createdat           *time.Time                             `json:"createdat,omitempty"`
	Updatedat           *time.Time                             `json:"updatedat,omitempty"`
	Itemgroupid         *string                                `json:"itemgroupid,omitempty"`
	Name                *string                                `json:"name,omitempty"`
	Type                *scalars.ItemGroupSourceType           `json:"type,omitempty"`
	URL                 *string                                `json:"url,omitempty"`
	Fileid              *string                                `json:"fileid,omitempty"`
	Originalfilename    *string                                `json:"originalfilename,omitempty"`
	Filename            *string                                `json:"filename,omitempty"`
	Filesize            *int                                   `json:"filesize,omitempty"`
	Isqueued            *bool                                  `json:"isqueued,omitempty"`
	Queueid             *bool                                  `json:"queueid,omitempty"`
	Trainingstatus      *scalars.ItemGroupSourceTrainingStatus `json:"trainingstatus,omitempty"`
	Trainingmsg         *string                                `json:"trainingmsg,omitempty"`
	Chars               *int                                   `json:"chars,omitempty"`
	Workspaceid         *string                                `json:"workspaceid,omitempty"`
	Extid               *string                                `json:"extid,omitempty"`
	Deletedat           *time.Time                             `json:"deletedat,omitempty"`
	Body                *string                                `json:"body,omitempty"`
	Metadata            *json.RawMessage                       `json:"metadata,omitempty"`
	Totalitems          *int                                   `json:"totalitems,omitempty"`
	Totalitemspending   *int                                   `json:"totalitemspending,omitempty"`
	Totalitemserror     *int                                   `json:"totalitemserror,omitempty"`
	Totalitemscompleted *int                                   `json:"totalitemscompleted,omitempty"`
	Itemgroup           *ItemGroup                             `json:"itemgroup,omitempty"`
}

// ItemGroupSourceConnection A connection to a list of items.

type ItemGroupSourceConnection struct {
	// A list of edges.
	Edges []*ItemGroupSourceEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// ItemGroupSourceEdge An edge in a connection.

type ItemGroupSourceEdge struct {
	// The item at the end of the edge.
	Node *ItemGroupSource `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// ItemGroupSourceSummary represents the GraphQL type ItemGroupSourceSummary
type ItemGroupSourceSummary struct {
	Type           string `json:"type"`
	Count          int    `json:"count"`
	Totalcompleted int    `json:"totalcompleted"`
	Totlapending   int    `json:"totlapending"`
	Totalerror     int    `json:"totalerror"`
}

// ItemInfo represents the GraphQL type ItemInfo
type ItemInfo struct {
	ID          string           `json:"id"`
	Createdat   string           `json:"createdat"`
	Name        string           `json:"name"`
	Filename    string           `json:"filename"`
	Metadata    *json.RawMessage `json:"metadata,omitempty"`
	Extref      *string          `json:"extref,omitempty"`
	Extid       *string          `json:"extid,omitempty"`
	Extmetadata *json.RawMessage `json:"extmetadata,omitempty"`
	Workspaceid string           `json:"workspaceid"`
}

// Lead represents the GraphQL type Lead
type Lead struct {
	ID          string     `json:"id"`
	Createdat   *time.Time `json:"createdat,omitempty"`
	Updatedat   *time.Time `json:"updatedat,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Email       *string    `json:"email,omitempty"`
	Phone       *string    `json:"phone,omitempty"`
	Company     *string    `json:"company,omitempty"`
	Ip          *string    `json:"ip,omitempty"`
	Guestuserid *string    `json:"guestuserid,omitempty"`
	Chatbotid   *string    `json:"chatbotid,omitempty"`
	Workspaceid *string    `json:"workspaceid,omitempty"`
}

// LeadConnection A connection to a list of items.

type LeadConnection struct {
	// A list of edges.
	Edges []*LeadEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// LeadEdge An edge in a connection.

type LeadEdge struct {
	// The item at the end of the edge.
	Node *Lead `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Message represents the GraphQL type Message
type Message struct {
	ID               string             `json:"id"`
	Createdat        *time.Time         `json:"createdat,omitempty"`
	Updatedat        *time.Time         `json:"updatedat,omitempty"`
	Role             *string            `json:"role,omitempty"`
	Msgid            *string            `json:"msgid,omitempty"`
	Content          *json.RawMessage   `json:"content,omitempty"`
	Parts            *scalars.JsonSlice `json:"parts,omitempty"`
	Prompttokens     *int               `json:"prompttokens,omitempty"`
	Completiontokens *int               `json:"completiontokens,omitempty"`
	Totaltokens      *int               `json:"totaltokens,omitempty"`
	Userid           *string            `json:"userid,omitempty"`
	Channelid        *string            `json:"channelid,omitempty"`
	Workspaceid      *string            `json:"workspaceid,omitempty"`
	Chatbotid        *string            `json:"chatbotid,omitempty"`
	Channel          *Channel           `json:"channel,omitempty"`
	User             *User              `json:"user,omitempty"`
}

// MessageConnection A connection to a list of items.

type MessageConnection struct {
	// A list of edges.
	Edges []*MessageEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// MessageEdge An edge in a connection.

type MessageEdge struct {
	// The item at the end of the edge.
	Node *Message `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// Node An object with an ID.
// Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)

type Node interface {
	IsNode()
}

// PageInfo Information about pagination in a connection.
// https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo

type PageInfo struct {
	// When paginating forwards, are there more items?
	Hasnextpage bool `json:"hasnextpage"`
	// When paginating backwards, are there more items?
	Haspreviouspage bool `json:"haspreviouspage"`
	// When paginating backwards, the cursor to continue.
	Startcursor *scalars.Cursor `json:"startcursor,omitempty"`
	// When paginating forwards, the cursor to continue.
	Endcursor *scalars.Cursor `json:"endcursor,omitempty"`
}

// Student represents the GraphQL type Student
type Student struct {
	Name string `json:"name"`
}

// TmpItem represents the GraphQL type TmpItem
type TmpItem struct {
	ID                string                       `json:"id"`
	Createdat         *time.Time                   `json:"createdat,omitempty"`
	Updatedat         *time.Time                   `json:"updatedat,omitempty"`
	Itemid            *string                      `json:"itemid,omitempty"`
	Batchid           *string                      `json:"batchid,omitempty"`
	Embeddingstatus   *scalars.ItemEmbeddingStatus `json:"embeddingstatus,omitempty"`
	Embeddingmsg      *string                      `json:"embeddingmsg,omitempty"`
	Workspaceid       string                       `json:"workspaceid"`
	Itemgroupid       *string                      `json:"itemgroupid,omitempty"`
	Itemgroupsourceid *string                      `json:"itemgroupsourceid,omitempty"`
}

// UrlToHtmlResponse represents the GraphQL type UrlToHtmlResponse
type UrlToHtmlResponse struct {
	Content    string `json:"content"`
	Statuscode *int   `json:"statuscode,omitempty"`
}

// User represents the GraphQL type User
type User struct {
	ID           string            `json:"id"`
	Createdat    *time.Time        `json:"createdat,omitempty"`
	Updatedat    *time.Time        `json:"updatedat,omitempty"`
	Type         *scalars.UserType `json:"type,omitempty"`
	Extuserid    *string           `json:"extuserid,omitempty"`
	Firstname    *string           `json:"firstname,omitempty"`
	Lastname     *string           `json:"lastname,omitempty"`
	Email        *string           `json:"email,omitempty"`
	Ip           *string           `json:"ip,omitempty"`
	Workspaceid  *string           `json:"workspaceid,omitempty"`
	Mychannels   []Channel         `json:"mychannels,omitempty"`
	Channels     []Channel         `json:"channels,omitempty"`
	Messages     []Message         `json:"messages,omitempty"`
	Chatbots     []Chatbot         `json:"chatbots,omitempty"`
	Folders      []Folder          `json:"folders,omitempty"`
	Channelusers []ChannelUser     `json:"channelusers,omitempty"`
	Chatbotusers []ChatbotUser     `json:"chatbotusers,omitempty"`
}

// UserConnection A connection to a list of items.

type UserConnection struct {
	// A list of edges.
	Edges []*UserEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	Pageinfo PageInfo `json:"pageinfo"`
	// Identifies the total count of items in the connection.
	Totalcount int `json:"totalcount"`
}

// UserEdge An edge in a connection.

type UserEdge struct {
	// The item at the end of the edge.
	Node *User `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor scalars.Cursor `json:"cursor"`
}

// WorkspaceAppInstallation represents the GraphQL type WorkspaceAppInstallation
type WorkspaceAppInstallation struct {
	ID          string      `json:"id"`
	App         AppStoreApp `json:"app"`
	Workspaceid string      `json:"workspaceid"`
	Status      string      `json:"status"`
	Installedat time.Time   `json:"installedat"`
}

// WorkspaceDetail represents the GraphQL type WorkspaceDetail
type WorkspaceDetail struct {
	ID            string  `json:"id"`
	Name          *string `json:"name,omitempty"`
	Totalagents   int     `json:"totalagents"`
	Totaldatasets int     `json:"totaldatasets"`
	Totalusers    int     `json:"totalusers"`
	Totalchannels int     `json:"totalchannels"`
	Totalmessages int     `json:"totalmessages"`
}
