package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"gqlgenapi/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	// simple in-memory store
	if r.users == nil || len(r.users) == 0 {
		r.seedData()
	}

	id := fmt.Sprintf("%d", len(r.todos)+1)
	todo := &model.Todo{
		ID:       id,
		Text:     input.Text,
		Done:     false,
		Priority: input.Priority,
		Tags:     input.Tags,
	}

	// attach user if found
	for _, u := range r.users {
		if u.ID == input.UserID {
			todo.User = u
			break
		}
	}

	r.todos = append(r.todos, todo)
	return todo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodoInput) (*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	for _, t := range r.todos {
		if t.ID == id {
			if input.Text != nil {
				t.Text = *input.Text
			}
			if input.Done != nil {
				t.Done = *input.Done
			}
			if input.Priority != nil {
				t.Priority = input.Priority
			}
			if input.Tags != nil && len(input.Tags) > 0 {
				t.Tags = input.Tags
			}
			return t, nil
		}
	}
	return nil, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	if r.todos == nil {
		r.seedData()
	}
	for i, t := range r.todos {
		if t.ID == id {
			r.todos = append(r.todos[:i], r.todos[i+1:]...)
			return true, nil
		}
	}
	return false, nil
}

// UpsertUser is the resolver for the upsertUser field.
func (r *mutationResolver) UpsertUser(ctx context.Context, id *string, name string, email *string, role *model.Role) (*model.User, error) {
	if r.users == nil {
		r.seedData()
	}

	// update existing if id provided
	if id != nil {
		for _, u := range r.users {
			if u.ID == *id {
				u.Name = name
				u.Email = email
				if role != nil {
					u.Role = *role
				}
				return u, nil
			}
		}
	}

	// create new
	newID := fmt.Sprintf("%d", len(r.users)+1)
	newRole := model.RoleUser
	if role != nil {
		newRole = *role
	}
	u := &model.User{
		ID:    newID,
		Name:  name,
		Email: email,
		Role:  newRole,
	}
	r.users = append(r.users, u)
	return u, nil
}

// CompleteAllTodos is the resolver for the completeAllTodos field.
func (r *mutationResolver) CompleteAllTodos(ctx context.Context) (int32, error) {
	if r.todos == nil {
		r.seedData()
	}
	var count int32
	for _, t := range r.todos {
		if !t.Done {
			t.Done = true
			count++
		}
	}
	return count, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong from gqlgenapi", nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	for _, t := range r.todos {
		if t.ID == id {
			return t, nil
		}
	}
	return nil, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, filter *model.TodoFilter, pagination *model.PaginationInput) ([]*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	var out []*model.Todo
	for _, t := range r.todos {
		if matchesTodoFilter(t, filter) {
			out = append(out, t)
		}
	}
	// simple offset pagination
	start := 0
	limit := len(out)
	if pagination != nil {
		if pagination.Offset > 0 && int(pagination.Offset) < len(out) {
			start = int(pagination.Offset)
		}
		if pagination.Limit > 0 && int(pagination.Limit) < limit {
			limit = int(pagination.Limit)
		}
	}
	if start > len(out) {
		return []*model.Todo{}, nil
	}
	end := start + limit
	if end > len(out) {
		end = len(out)
	}
	return out[start:end], nil
}

// TodosConnection is the resolver for the todosConnection field.
func (r *queryResolver) TodosConnection(ctx context.Context, filter *model.TodoFilter, pagination *model.PaginationInput) (*model.TodoConnection, error) {
	items, err := r.Todos(ctx, filter, pagination)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.TodoEdge, len(items))
	for i, t := range items {
		cursor := fmt.Sprintf("cursor-%s", t.ID)
		edges[i] = &model.TodoEdge{
			Cursor: cursor,
			Node:   t,
		}
	}
	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}
	conn := &model.TodoConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(len(items)),
	}
	return conn, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if r.users == nil {
		r.seedData()
	}
	for _, u := range r.users {
		if u.ID == id {
			return u, nil
		}
	}
	return nil, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	if r.users == nil {
		r.seedData()
	}
	return r.users, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, term string) ([]model.SearchResult, error) {
	if r.users == nil || r.todos == nil {
		r.seedData()
	}
	var results []model.SearchResult
	for _, t := range r.todos {
		if term == "" || containsIgnoreCase(t.Text, term) {
			results = append(results, t)
		}
	}
	for _, u := range r.users {
		if term == "" || containsIgnoreCase(u.Name, term) {
			results = append(results, u)
		}
	}
	return results, nil
}

// Echo is the resolver for the echo field.
func (r *queryResolver) Echo(ctx context.Context, message string) (string, error) {
	return message, nil
}

// Sum is the resolver for the sum field.
func (r *queryResolver) Sum(ctx context.Context, a int32, b int32) (int32, error) {
	return a + b, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *Resolver) seedData() {
	if r.users == nil {
		r.users = []*model.User{
			{ID: "1", Name: "Alice", Role: model.RoleUser},
			{ID: "2", Name: "Bob", Role: model.RoleAdmin},
		}
	}
	if r.todos == nil {
		r.todos = []*model.Todo{
			{
				ID:   "1",
				Text: "Try the ping query",
				Done: false,
				Tags: []string{"demo", "ping"},
				User: r.users[0],
			},
			{
				ID:   "2",
				Text: "Create your first todo",
				Done: false,
				Tags: []string{"demo"},
				User: r.users[1],
			},
		}
	}
}
func matchesTodoFilter(t *model.Todo, f *model.TodoFilter) bool {
	if f == nil {
		return true
	}
	if f.TextContains != nil && !containsIgnoreCase(t.Text, *f.TextContains) {
		return false
	}
	if f.Done != nil && t.Done != *f.Done {
		return false
	}
	if f.MinPriority != nil {
		if t.Priority == nil || *t.Priority < *f.MinPriority {
			return false
		}
	}
	if f.HasTag != nil {
		found := false
		for _, tag := range t.Tags {
			if tag == *f.HasTag {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}
func containsIgnoreCase(s, substr string) bool {
	if substr == "" {
		return true
	}
	// simple case-insensitive contains without pulling in extra deps
	sLower := strings.ToLower(s)
	subLower := strings.ToLower(substr)
	return strings.Contains(sLower, subLower)
}
*/
