// Code generated by ent, DO NOT EDIT.

package scalars

import (
	"time"

	"encoding/json"
)

type (
	Boolean = bool

	Cursor = any

	Float = float64

	ID = string

	Int = int

	ItemEmbeddingStatus = any

	ItemGroupSourceTrainingStatus = any

	ItemGroupSourceType = any

	JSON = json.RawMessage

	JsonSlice = any

	Map = any

	Password = any

	String = string

	Time = time.Time

	Uint = uint

	Uint64 = uint64

	UserType = any
)
