// Code generated by ent, DO NOT EDIT.

package inputs

// NewTodo represents the GraphQL type NewTodo
type NewTodo struct {
	Text     string   `json:"text"`
	UserID   string   `json:"userId"`
	Priority *int     `json:"priority,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

// PaginationInput represents the GraphQL type PaginationInput
type PaginationInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

// TodoFilter represents the GraphQL type TodoFilter
type TodoFilter struct {
	TextContains *string `json:"textContains,omitempty"`
	Done         *bool   `json:"done,omitempty"`
	MinPriority  *int    `json:"minPriority,omitempty"`
	HasTag       *string `json:"hasTag,omitempty"`
}

// UpdateTodoInput represents the GraphQL type UpdateTodoInput
type UpdateTodoInput struct {
	Text     *string  `json:"text,omitempty"`
	Done     *bool    `json:"done,omitempty"`
	Priority *int     `json:"priority,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}
