// Code generated by ent, DO NOT EDIT.

package types

import (
	"sdkexample_gqlgenapi/sdk/enums"
)

// Node is a GraphQL interface type
type Node interface {
	IsNode()
}

// PageInfo represents the GraphQL type PageInfo
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

// Todo represents the GraphQL type Todo
type Todo struct {
	ID       string   `json:"iD"`
	Text     string   `json:"text"`
	Done     bool     `json:"done"`
	Priority *int     `json:"priority,omitempty"`
	Tags     []string `json:"tags"`
	User     User     `json:"user"`
}

// TodoConnection represents the GraphQL type TodoConnection
type TodoConnection struct {
	Edges      []TodoEdge `json:"edges"`
	PageInfo   PageInfo   `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

// TodoEdge represents the GraphQL type TodoEdge
type TodoEdge struct {
	Cursor string `json:"cursor"`
	Node   Todo   `json:"node"`
}

// User represents the GraphQL type User
type User struct {
	ID    string     `json:"iD"`
	Name  string     `json:"name"`
	Email *string    `json:"email,omitempty"`
	Role  enums.Role `json:"role"`
}
