// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ItemGroupSourceFields provides type-safe field selection for ItemGroupSource
type ItemGroupSourceFields struct {
	selection *api.FieldSelection
}

// NewItemGroupSourceFields creates a new ItemGroupSourceFields selector
func NewItemGroupSourceFields(selection *api.FieldSelection) *ItemGroupSourceFields {
	return &ItemGroupSourceFields{selection: selection}
}

// ID selects the id field
func (f *ItemGroupSourceFields) ID() *ItemGroupSourceFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ItemGroupSourceFields) CreatedAt() *ItemGroupSourceFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ItemGroupSourceFields) UpdatedAt() *ItemGroupSourceFields {
	f.selection.AddField("updatedAt")
	return f
}

// ItemGroupID selects the itemGroupID field
func (f *ItemGroupSourceFields) ItemGroupID() *ItemGroupSourceFields {
	f.selection.AddField("itemGroupID")
	return f
}

// Name selects the name field
func (f *ItemGroupSourceFields) Name() *ItemGroupSourceFields {
	f.selection.AddField("name")
	return f
}

// Type selects the type field
func (f *ItemGroupSourceFields) Type() *ItemGroupSourceFields {
	f.selection.AddField("type")
	return f
}

// URL selects the url field
func (f *ItemGroupSourceFields) URL() *ItemGroupSourceFields {
	f.selection.AddField("url")
	return f
}

// FileID selects the fileID field
func (f *ItemGroupSourceFields) FileID() *ItemGroupSourceFields {
	f.selection.AddField("fileID")
	return f
}

// OriginalFileName selects the originalFileName field
func (f *ItemGroupSourceFields) OriginalFileName() *ItemGroupSourceFields {
	f.selection.AddField("originalFileName")
	return f
}

// FileName selects the fileName field
func (f *ItemGroupSourceFields) FileName() *ItemGroupSourceFields {
	f.selection.AddField("fileName")
	return f
}

// FileSize selects the fileSize field
func (f *ItemGroupSourceFields) FileSize() *ItemGroupSourceFields {
	f.selection.AddField("fileSize")
	return f
}

// IsQueued selects the isQueued field
func (f *ItemGroupSourceFields) IsQueued() *ItemGroupSourceFields {
	f.selection.AddField("isQueued")
	return f
}

// QueueID selects the queueID field
func (f *ItemGroupSourceFields) QueueID() *ItemGroupSourceFields {
	f.selection.AddField("queueID")
	return f
}

// TrainingStatus selects the trainingStatus field
func (f *ItemGroupSourceFields) TrainingStatus() *ItemGroupSourceFields {
	f.selection.AddField("trainingStatus")
	return f
}

// TrainingMsg selects the trainingMsg field
func (f *ItemGroupSourceFields) TrainingMsg() *ItemGroupSourceFields {
	f.selection.AddField("trainingMsg")
	return f
}

// Chars selects the chars field
func (f *ItemGroupSourceFields) Chars() *ItemGroupSourceFields {
	f.selection.AddField("chars")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ItemGroupSourceFields) WorkspaceID() *ItemGroupSourceFields {
	f.selection.AddField("workspaceID")
	return f
}

// ExtID selects the extID field
func (f *ItemGroupSourceFields) ExtID() *ItemGroupSourceFields {
	f.selection.AddField("extID")
	return f
}

// DeletedAt selects the deletedAt field
func (f *ItemGroupSourceFields) DeletedAt() *ItemGroupSourceFields {
	f.selection.AddField("deletedAt")
	return f
}

// Body selects the body field
func (f *ItemGroupSourceFields) Body() *ItemGroupSourceFields {
	f.selection.AddField("body")
	return f
}

// Metadata selects the metadata field
func (f *ItemGroupSourceFields) Metadata() *ItemGroupSourceFields {
	f.selection.AddField("metadata")
	return f
}

// TotalItems selects the totalItems field
func (f *ItemGroupSourceFields) TotalItems() *ItemGroupSourceFields {
	f.selection.AddField("totalItems")
	return f
}

// TotalItemsPending selects the totalItemsPending field
func (f *ItemGroupSourceFields) TotalItemsPending() *ItemGroupSourceFields {
	f.selection.AddField("totalItemsPending")
	return f
}

// TotalItemsError selects the totalItemsError field
func (f *ItemGroupSourceFields) TotalItemsError() *ItemGroupSourceFields {
	f.selection.AddField("totalItemsError")
	return f
}

// TotalItemsCompleted selects the totalItemsCompleted field
func (f *ItemGroupSourceFields) TotalItemsCompleted() *ItemGroupSourceFields {
	f.selection.AddField("totalItemsCompleted")
	return f
}

// ItemGroup selects the itemGroup field with nested selection
func (f *ItemGroupSourceFields) ItemGroup(selector func(*ItemGroupFields)) *ItemGroupSourceFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("itemGroup", child)
	return f
}

// ItemGroupSourceConnectionFields provides type-safe field selection for ItemGroupSourceConnection
type ItemGroupSourceConnectionFields struct {
	selection *api.FieldSelection
}

// NewItemGroupSourceConnectionFields creates a new ItemGroupSourceConnectionFields selector
func NewItemGroupSourceConnectionFields(selection *api.FieldSelection) *ItemGroupSourceConnectionFields {
	return &ItemGroupSourceConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ItemGroupSourceConnectionFields) Edges(selector func(*ItemGroupSourceEdgeFields)) *ItemGroupSourceConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupSourceEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ItemGroupSourceConnectionFields) PageInfo(selector func(*PageInfoFields)) *ItemGroupSourceConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ItemGroupSourceConnectionFields) TotalCount() *ItemGroupSourceConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ItemGroupSourceEdgeFields provides type-safe field selection for ItemGroupSourceEdge
type ItemGroupSourceEdgeFields struct {
	selection *api.FieldSelection
}

// NewItemGroupSourceEdgeFields creates a new ItemGroupSourceEdgeFields selector
func NewItemGroupSourceEdgeFields(selection *api.FieldSelection) *ItemGroupSourceEdgeFields {
	return &ItemGroupSourceEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ItemGroupSourceEdgeFields) Node(selector func(*ItemGroupSourceFields)) *ItemGroupSourceEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupSourceFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ItemGroupSourceEdgeFields) Cursor() *ItemGroupSourceEdgeFields {
	f.selection.AddField("cursor")
	return f
}
