// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// UserFields provides type-safe field selection for User
type UserFields struct {
	selection *api.FieldSelection
}

// NewUserFields creates a new UserFields selector
func NewUserFields(selection *api.FieldSelection) *UserFields {
	return &UserFields{selection: selection}
}

// ID selects the id field
func (f *UserFields) ID() *UserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *UserFields) CreatedAt() *UserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *UserFields) UpdatedAt() *UserFields {
	f.selection.AddField("updatedAt")
	return f
}

// Type selects the type field
func (f *UserFields) Type() *UserFields {
	f.selection.AddField("type")
	return f
}

// ExtUserID selects the extUserID field
func (f *UserFields) ExtUserID() *UserFields {
	f.selection.AddField("extUserID")
	return f
}

// FirstName selects the firstName field
func (f *UserFields) FirstName() *UserFields {
	f.selection.AddField("firstName")
	return f
}

// LastName selects the lastName field
func (f *UserFields) LastName() *UserFields {
	f.selection.AddField("lastName")
	return f
}

// Email selects the email field
func (f *UserFields) Email() *UserFields {
	f.selection.AddField("email")
	return f
}

// Ip selects the ip field
func (f *UserFields) Ip() *UserFields {
	f.selection.AddField("ip")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *UserFields) WorkspaceID() *UserFields {
	f.selection.AddField("workspaceID")
	return f
}

// MyChannels selects the myChannels field with nested selection
func (f *UserFields) MyChannels(selector func(*ChannelFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("myChannels", child)
	return f
}

// Channels selects the channels field with nested selection
func (f *UserFields) Channels(selector func(*ChannelFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channels", child)
	return f
}

// Messages selects the messages field with nested selection
func (f *UserFields) Messages(selector func(*MessageFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewMessageFields(child))
	}
	f.selection.AddChild("messages", child)
	return f
}

// Chatbots selects the chatbots field with nested selection
func (f *UserFields) Chatbots(selector func(*ChatbotFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbots", child)
	return f
}

// Folders selects the folders field with nested selection
func (f *UserFields) Folders(selector func(*FolderFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("folders", child)
	return f
}

// ChannelUsers selects the channelUsers field with nested selection
func (f *UserFields) ChannelUsers(selector func(*ChannelUserFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserFields(child))
	}
	f.selection.AddChild("channelUsers", child)
	return f
}

// ChatbotUsers selects the chatbotUsers field with nested selection
func (f *UserFields) ChatbotUsers(selector func(*ChatbotUserFields)) *UserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserFields(child))
	}
	f.selection.AddChild("chatbotUsers", child)
	return f
}

// UserConnectionFields provides type-safe field selection for UserConnection
type UserConnectionFields struct {
	selection *api.FieldSelection
}

// NewUserConnectionFields creates a new UserConnectionFields selector
func NewUserConnectionFields(selection *api.FieldSelection) *UserConnectionFields {
	return &UserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *UserConnectionFields) Edges(selector func(*UserEdgeFields)) *UserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *UserConnectionFields) PageInfo(selector func(*PageInfoFields)) *UserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *UserConnectionFields) TotalCount() *UserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// UserEdgeFields provides type-safe field selection for UserEdge
type UserEdgeFields struct {
	selection *api.FieldSelection
}

// NewUserEdgeFields creates a new UserEdgeFields selector
func NewUserEdgeFields(selection *api.FieldSelection) *UserEdgeFields {
	return &UserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *UserEdgeFields) Node(selector func(*UserFields)) *UserEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *UserEdgeFields) Cursor() *UserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
