// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// FuncToolLogFields provides type-safe field selection for FuncToolLog
type FuncToolLogFields struct {
	selection *api.FieldSelection
}

// NewFuncToolLogFields creates a new FuncToolLogFields selector
func NewFuncToolLogFields(selection *api.FieldSelection) *FuncToolLogFields {
	return &FuncToolLogFields{selection: selection}
}

// ID selects the id field
func (f *FuncToolLogFields) ID() *FuncToolLogFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *FuncToolLogFields) CreatedAt() *FuncToolLogFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *FuncToolLogFields) UpdatedAt() *FuncToolLogFields {
	f.selection.AddField("updatedAt")
	return f
}

// ToolCallID selects the toolCallID field
func (f *FuncToolLogFields) ToolCallID() *FuncToolLogFields {
	f.selection.AddField("toolCallID")
	return f
}

// LogType selects the logType field
func (f *FuncToolLogFields) LogType() *FuncToolLogFields {
	f.selection.AddField("logType")
	return f
}

// Msg selects the msg field
func (f *FuncToolLogFields) Msg() *FuncToolLogFields {
	f.selection.AddField("msg")
	return f
}

// Body selects the body field
func (f *FuncToolLogFields) Body() *FuncToolLogFields {
	f.selection.AddField("body")
	return f
}

// FuncToolID selects the funcToolID field
func (f *FuncToolLogFields) FuncToolID() *FuncToolLogFields {
	f.selection.AddField("funcToolID")
	return f
}

// ChannelID selects the channelID field
func (f *FuncToolLogFields) ChannelID() *FuncToolLogFields {
	f.selection.AddField("channelID")
	return f
}

// UserID selects the userID field
func (f *FuncToolLogFields) UserID() *FuncToolLogFields {
	f.selection.AddField("userID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *FuncToolLogFields) WorkspaceID() *FuncToolLogFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *FuncToolLogFields) ChatbotID() *FuncToolLogFields {
	f.selection.AddField("chatbotID")
	return f
}

// FuncTool selects the funcTool field with nested selection
func (f *FuncToolLogFields) FuncTool(selector func(*FuncToolFields)) *FuncToolLogFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTool", child)
	return f
}

// FuncToolLogConnectionFields provides type-safe field selection for FuncToolLogConnection
type FuncToolLogConnectionFields struct {
	selection *api.FieldSelection
}

// NewFuncToolLogConnectionFields creates a new FuncToolLogConnectionFields selector
func NewFuncToolLogConnectionFields(selection *api.FieldSelection) *FuncToolLogConnectionFields {
	return &FuncToolLogConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FuncToolLogConnectionFields) Edges(selector func(*FuncToolLogEdgeFields)) *FuncToolLogConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolLogEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FuncToolLogConnectionFields) PageInfo(selector func(*PageInfoFields)) *FuncToolLogConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FuncToolLogConnectionFields) TotalCount() *FuncToolLogConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// FuncToolLogEdgeFields provides type-safe field selection for FuncToolLogEdge
type FuncToolLogEdgeFields struct {
	selection *api.FieldSelection
}

// NewFuncToolLogEdgeFields creates a new FuncToolLogEdgeFields selector
func NewFuncToolLogEdgeFields(selection *api.FieldSelection) *FuncToolLogEdgeFields {
	return &FuncToolLogEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FuncToolLogEdgeFields) Node(selector func(*FuncToolLogFields)) *FuncToolLogEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolLogFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FuncToolLogEdgeFields) Cursor() *FuncToolLogEdgeFields {
	f.selection.AddField("cursor")
	return f
}
