// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// FuncToolFields provides type-safe field selection for FuncTool
type FuncToolFields struct {
	selection *api.FieldSelection
}

// NewFuncToolFields creates a new FuncToolFields selector
func NewFuncToolFields(selection *api.FieldSelection) *FuncToolFields {
	return &FuncToolFields{selection: selection}
}

// ID selects the id field
func (f *FuncToolFields) ID() *FuncToolFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *FuncToolFields) CreatedAt() *FuncToolFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *FuncToolFields) UpdatedAt() *FuncToolFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *FuncToolFields) Name() *FuncToolFields {
	f.selection.AddField("name")
	return f
}

// FuncToolType selects the funcToolType field
func (f *FuncToolFields) FuncToolType() *FuncToolFields {
	f.selection.AddField("funcToolType")
	return f
}

// Active selects the active field
func (f *FuncToolFields) Active() *FuncToolFields {
	f.selection.AddField("active")
	return f
}

// Description selects the description field
func (f *FuncToolFields) Description() *FuncToolFields {
	f.selection.AddField("description")
	return f
}

// SystemPrompt selects the systemPrompt field
func (f *FuncToolFields) SystemPrompt() *FuncToolFields {
	f.selection.AddField("systemPrompt")
	return f
}

// CredentialID selects the credentialID field
func (f *FuncToolFields) CredentialID() *FuncToolFields {
	f.selection.AddField("credentialID")
	return f
}

// Data selects the data field
func (f *FuncToolFields) Data() *FuncToolFields {
	f.selection.AddField("data")
	return f
}

// AiModelID selects the aiModelID field
func (f *FuncToolFields) AiModelID() *FuncToolFields {
	f.selection.AddField("aiModelID")
	return f
}

// MaxTokens selects the maxTokens field
func (f *FuncToolFields) MaxTokens() *FuncToolFields {
	f.selection.AddField("maxTokens")
	return f
}

// Temperature selects the temperature field
func (f *FuncToolFields) Temperature() *FuncToolFields {
	f.selection.AddField("temperature")
	return f
}

// ItemGroupID selects the itemGroupID field
func (f *FuncToolFields) ItemGroupID() *FuncToolFields {
	f.selection.AddField("itemGroupID")
	return f
}

// Limit selects the limit field
func (f *FuncToolFields) Limit() *FuncToolFields {
	f.selection.AddField("limit")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *FuncToolFields) WorkspaceID() *FuncToolFields {
	f.selection.AddField("workspaceID")
	return f
}

// Chatbots selects the chatbots field with nested selection
func (f *FuncToolFields) Chatbots(selector func(*ChatbotFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbots", child)
	return f
}

// Credential selects the credential field with nested selection
func (f *FuncToolFields) Credential(selector func(*CredentialFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewCredentialFields(child))
	}
	f.selection.AddChild("credential", child)
	return f
}

// FuncToolLogs selects the funcToolLogs field with nested selection
func (f *FuncToolFields) FuncToolLogs(selector func(*FuncToolLogFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolLogFields(child))
	}
	f.selection.AddChild("funcToolLogs", child)
	return f
}

// AiModel selects the aiModel field with nested selection
func (f *FuncToolFields) AiModel(selector func(*AiModelFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelFields(child))
	}
	f.selection.AddChild("aiModel", child)
	return f
}

// ItemGroup selects the itemGroup field with nested selection
func (f *FuncToolFields) ItemGroup(selector func(*ItemGroupFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("itemGroup", child)
	return f
}

// ChatbotTools selects the chatbotTools field with nested selection
func (f *FuncToolFields) ChatbotTools(selector func(*ChatbotToolFields)) *FuncToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolFields(child))
	}
	f.selection.AddChild("chatbotTools", child)
	return f
}

// FuncToolConnectionFields provides type-safe field selection for FuncToolConnection
type FuncToolConnectionFields struct {
	selection *api.FieldSelection
}

// NewFuncToolConnectionFields creates a new FuncToolConnectionFields selector
func NewFuncToolConnectionFields(selection *api.FieldSelection) *FuncToolConnectionFields {
	return &FuncToolConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FuncToolConnectionFields) Edges(selector func(*FuncToolEdgeFields)) *FuncToolConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FuncToolConnectionFields) PageInfo(selector func(*PageInfoFields)) *FuncToolConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FuncToolConnectionFields) TotalCount() *FuncToolConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// FuncToolEdgeFields provides type-safe field selection for FuncToolEdge
type FuncToolEdgeFields struct {
	selection *api.FieldSelection
}

// NewFuncToolEdgeFields creates a new FuncToolEdgeFields selector
func NewFuncToolEdgeFields(selection *api.FieldSelection) *FuncToolEdgeFields {
	return &FuncToolEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FuncToolEdgeFields) Node(selector func(*FuncToolFields)) *FuncToolEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FuncToolEdgeFields) Cursor() *FuncToolEdgeFields {
	f.selection.AddField("cursor")
	return f
}
