// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// CheckoutSessionVerifyFields provides type-safe field selection for CheckoutSessionVerify
type CheckoutSessionVerifyFields struct {
	selection *api.FieldSelection
}

// NewCheckoutSessionVerifyFields creates a new CheckoutSessionVerifyFields selector
func NewCheckoutSessionVerifyFields(selection *api.FieldSelection) *CheckoutSessionVerifyFields {
	return &CheckoutSessionVerifyFields{selection: selection}
}

// WorkspaceID selects the workspaceId field
func (f *CheckoutSessionVerifyFields) WorkspaceID() *CheckoutSessionVerifyFields {
	f.selection.AddField("workspaceId")
	return f
}

// AlreadyVerified selects the alreadyVerified field
func (f *CheckoutSessionVerifyFields) AlreadyVerified() *CheckoutSessionVerifyFields {
	f.selection.AddField("alreadyVerified")
	return f
}
