// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// AppStorePartnerFields provides type-safe field selection for AppStorePartner
type AppStorePartnerFields struct {
	selection *api.FieldSelection
}

// NewAppStorePartnerFields creates a new AppStorePartnerFields selector
func NewAppStorePartnerFields(selection *api.FieldSelection) *AppStorePartnerFields {
	return &AppStorePartnerFields{selection: selection}
}

// ID selects the id field
func (f *AppStorePartnerFields) ID() *AppStorePartnerFields {
	f.selection.AddField("id")
	return f
}

// Name selects the name field
func (f *AppStorePartnerFields) Name() *AppStorePartnerFields {
	f.selection.AddField("name")
	return f
}

// CompanyName selects the companyName field
func (f *AppStorePartnerFields) CompanyName() *AppStorePartnerFields {
	f.selection.AddField("companyName")
	return f
}
