// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// CWorkspaceFeatureLimitFields provides type-safe field selection for CWorkspaceFeatureLimit
type CWorkspaceFeatureLimitFields struct {
	selection *api.FieldSelection
}

// NewCWorkspaceFeatureLimitFields creates a new CWorkspaceFeatureLimitFields selector
func NewCWorkspaceFeatureLimitFields(selection *api.FieldSelection) *CWorkspaceFeatureLimitFields {
	return &CWorkspaceFeatureLimitFields{selection: selection}
}

// ID selects the id field
func (f *CWorkspaceFeatureLimitFields) ID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *CWorkspaceFeatureLimitFields) CreatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *CWorkspaceFeatureLimitFields) UpdatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("updatedAt")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *CWorkspaceFeatureLimitFields) WorkspaceID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("workspaceID")
	return f
}

// BillingFeatureID selects the billingFeatureID field
func (f *CWorkspaceFeatureLimitFields) BillingFeatureID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("billingFeatureID")
	return f
}

// Available selects the available field
func (f *CWorkspaceFeatureLimitFields) Available() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("available")
	return f
}

// Used selects the used field
func (f *CWorkspaceFeatureLimitFields) Used() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("used")
	return f
}

// Balance selects the balance field
func (f *CWorkspaceFeatureLimitFields) Balance() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("balance")
	return f
}

// CalculatedAt selects the calculatedAt field
func (f *CWorkspaceFeatureLimitFields) CalculatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("calculatedAt")
	return f
}

// Sources selects the sources field
func (f *CWorkspaceFeatureLimitFields) Sources() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("sources")
	return f
}

// BillingFeature selects the billingFeature field with nested selection
func (f *CWorkspaceFeatureLimitFields) BillingFeature(selector func(*BillingFeatureFields)) *CWorkspaceFeatureLimitFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("billingFeature", child)
	return f
}

// CWorkspaceFeatureLimitConnectionFields provides type-safe field selection for CWorkspaceFeatureLimitConnection
type CWorkspaceFeatureLimitConnectionFields struct {
	selection *api.FieldSelection
}

// NewCWorkspaceFeatureLimitConnectionFields creates a new CWorkspaceFeatureLimitConnectionFields selector
func NewCWorkspaceFeatureLimitConnectionFields(selection *api.FieldSelection) *CWorkspaceFeatureLimitConnectionFields {
	return &CWorkspaceFeatureLimitConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *CWorkspaceFeatureLimitConnectionFields) Edges(selector func(*CWorkspaceFeatureLimitEdgeFields)) *CWorkspaceFeatureLimitConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *CWorkspaceFeatureLimitConnectionFields) PageInfo(selector func(*PageInfoFields)) *CWorkspaceFeatureLimitConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *CWorkspaceFeatureLimitConnectionFields) TotalCount() *CWorkspaceFeatureLimitConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// CWorkspaceFeatureLimitEdgeFields provides type-safe field selection for CWorkspaceFeatureLimitEdge
type CWorkspaceFeatureLimitEdgeFields struct {
	selection *api.FieldSelection
}

// NewCWorkspaceFeatureLimitEdgeFields creates a new CWorkspaceFeatureLimitEdgeFields selector
func NewCWorkspaceFeatureLimitEdgeFields(selection *api.FieldSelection) *CWorkspaceFeatureLimitEdgeFields {
	return &CWorkspaceFeatureLimitEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *CWorkspaceFeatureLimitEdgeFields) Node(selector func(*CWorkspaceFeatureLimitFields)) *CWorkspaceFeatureLimitEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *CWorkspaceFeatureLimitEdgeFields) Cursor() *CWorkspaceFeatureLimitEdgeFields {
	f.selection.AddField("cursor")
	return f
}
