// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// BillingFeatureFields provides type-safe field selection for BillingFeature
type BillingFeatureFields struct {
	selection *api.FieldSelection
}

// NewBillingFeatureFields creates a new BillingFeatureFields selector
func NewBillingFeatureFields(selection *api.FieldSelection) *BillingFeatureFields {
	return &BillingFeatureFields{selection: selection}
}

// ID selects the id field
func (f *BillingFeatureFields) ID() *BillingFeatureFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingFeatureFields) CreatedAt() *BillingFeatureFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingFeatureFields) UpdatedAt() *BillingFeatureFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *BillingFeatureFields) Name() *BillingFeatureFields {
	f.selection.AddField("name")
	return f
}

// GroupName selects the groupName field
func (f *BillingFeatureFields) GroupName() *BillingFeatureFields {
	f.selection.AddField("groupName")
	return f
}

// IsActive selects the isActive field
func (f *BillingFeatureFields) IsActive() *BillingFeatureFields {
	f.selection.AddField("isActive")
	return f
}

// DefaultValue selects the defaultValue field
func (f *BillingFeatureFields) DefaultValue() *BillingFeatureFields {
	f.selection.AddField("defaultValue")
	return f
}

// UnitType selects the unitType field
func (f *BillingFeatureFields) UnitType() *BillingFeatureFields {
	f.selection.AddField("unitType")
	return f
}

// FeatureType selects the featureType field
func (f *BillingFeatureFields) FeatureType() *BillingFeatureFields {
	f.selection.AddField("featureType")
	return f
}

// SortOrder selects the sortOrder field
func (f *BillingFeatureFields) SortOrder() *BillingFeatureFields {
	f.selection.AddField("sortOrder")
	return f
}

// Description selects the description field
func (f *BillingFeatureFields) Description() *BillingFeatureFields {
	f.selection.AddField("description")
	return f
}

// BillingPlanFeatures selects the billingPlanFeatures field with nested selection
func (f *BillingFeatureFields) BillingPlanFeatures(selector func(*BillingPlanFeatureFields)) *BillingFeatureFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureFields(child))
	}
	f.selection.AddChild("billingPlanFeatures", child)
	return f
}

// CworkspaceFeatureLimits selects the cworkspaceFeatureLimits field with nested selection
func (f *BillingFeatureFields) CworkspaceFeatureLimits(selector func(*CWorkspaceFeatureLimitFields)) *BillingFeatureFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitFields(child))
	}
	f.selection.AddChild("cworkspaceFeatureLimits", child)
	return f
}

// BillingFeatureConnectionFields provides type-safe field selection for BillingFeatureConnection
type BillingFeatureConnectionFields struct {
	selection *api.FieldSelection
}

// NewBillingFeatureConnectionFields creates a new BillingFeatureConnectionFields selector
func NewBillingFeatureConnectionFields(selection *api.FieldSelection) *BillingFeatureConnectionFields {
	return &BillingFeatureConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingFeatureConnectionFields) Edges(selector func(*BillingFeatureEdgeFields)) *BillingFeatureConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingFeatureConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingFeatureConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingFeatureConnectionFields) TotalCount() *BillingFeatureConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// BillingFeatureEdgeFields provides type-safe field selection for BillingFeatureEdge
type BillingFeatureEdgeFields struct {
	selection *api.FieldSelection
}

// NewBillingFeatureEdgeFields creates a new BillingFeatureEdgeFields selector
func NewBillingFeatureEdgeFields(selection *api.FieldSelection) *BillingFeatureEdgeFields {
	return &BillingFeatureEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingFeatureEdgeFields) Node(selector func(*BillingFeatureFields)) *BillingFeatureEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingFeatureEdgeFields) Cursor() *BillingFeatureEdgeFields {
	f.selection.AddField("cursor")
	return f
}
