// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ChatbotToolFields provides type-safe field selection for ChatbotTool
type ChatbotToolFields struct {
	selection *api.FieldSelection
}

// NewChatbotToolFields creates a new ChatbotToolFields selector
func NewChatbotToolFields(selection *api.FieldSelection) *ChatbotToolFields {
	return &ChatbotToolFields{selection: selection}
}

// ID selects the id field
func (f *ChatbotToolFields) ID() *ChatbotToolFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChatbotToolFields) CreatedAt() *ChatbotToolFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChatbotToolFields) UpdatedAt() *ChatbotToolFields {
	f.selection.AddField("updatedAt")
	return f
}

// FuncToolID selects the funcToolID field
func (f *ChatbotToolFields) FuncToolID() *ChatbotToolFields {
	f.selection.AddField("funcToolID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChatbotToolFields) ChatbotID() *ChatbotToolFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChatbotToolFields) WorkspaceID() *ChatbotToolFields {
	f.selection.AddField("workspaceID")
	return f
}

// FuncTool selects the funcTool field with nested selection
func (f *ChatbotToolFields) FuncTool(selector func(*FuncToolFields)) *ChatbotToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTool", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChatbotToolFields) Chatbot(selector func(*ChatbotFields)) *ChatbotToolFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// ChatbotToolConnectionFields provides type-safe field selection for ChatbotToolConnection
type ChatbotToolConnectionFields struct {
	selection *api.FieldSelection
}

// NewChatbotToolConnectionFields creates a new ChatbotToolConnectionFields selector
func NewChatbotToolConnectionFields(selection *api.FieldSelection) *ChatbotToolConnectionFields {
	return &ChatbotToolConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotToolConnectionFields) Edges(selector func(*ChatbotToolEdgeFields)) *ChatbotToolConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotToolConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotToolConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotToolConnectionFields) TotalCount() *ChatbotToolConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ChatbotToolEdgeFields provides type-safe field selection for ChatbotToolEdge
type ChatbotToolEdgeFields struct {
	selection *api.FieldSelection
}

// NewChatbotToolEdgeFields creates a new ChatbotToolEdgeFields selector
func NewChatbotToolEdgeFields(selection *api.FieldSelection) *ChatbotToolEdgeFields {
	return &ChatbotToolEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotToolEdgeFields) Node(selector func(*ChatbotToolFields)) *ChatbotToolEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotToolEdgeFields) Cursor() *ChatbotToolEdgeFields {
	f.selection.AddField("cursor")
	return f
}
