// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// BillingPlanWspaceFields provides type-safe field selection for BillingPlanWspace
type BillingPlanWspaceFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanWspaceFields creates a new BillingPlanWspaceFields selector
func NewBillingPlanWspaceFields(selection *api.FieldSelection) *BillingPlanWspaceFields {
	return &BillingPlanWspaceFields{selection: selection}
}

// ID selects the id field
func (f *BillingPlanWspaceFields) ID() *BillingPlanWspaceFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingPlanWspaceFields) CreatedAt() *BillingPlanWspaceFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingPlanWspaceFields) UpdatedAt() *BillingPlanWspaceFields {
	f.selection.AddField("updatedAt")
	return f
}

// BillingPlanID selects the billingPlanID field
func (f *BillingPlanWspaceFields) BillingPlanID() *BillingPlanWspaceFields {
	f.selection.AddField("billingPlanID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *BillingPlanWspaceFields) WorkspaceID() *BillingPlanWspaceFields {
	f.selection.AddField("workspaceID")
	return f
}

// BillingPlan selects the billingPlan field with nested selection
func (f *BillingPlanWspaceFields) BillingPlan(selector func(*BillingPlanFields)) *BillingPlanWspaceFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("billingPlan", child)
	return f
}

// BillingPlanWspaceConnectionFields provides type-safe field selection for BillingPlanWspaceConnection
type BillingPlanWspaceConnectionFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanWspaceConnectionFields creates a new BillingPlanWspaceConnectionFields selector
func NewBillingPlanWspaceConnectionFields(selection *api.FieldSelection) *BillingPlanWspaceConnectionFields {
	return &BillingPlanWspaceConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingPlanWspaceConnectionFields) Edges(selector func(*BillingPlanWspaceEdgeFields)) *BillingPlanWspaceConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanWspaceEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingPlanWspaceConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingPlanWspaceConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingPlanWspaceConnectionFields) TotalCount() *BillingPlanWspaceConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// BillingPlanWspaceEdgeFields provides type-safe field selection for BillingPlanWspaceEdge
type BillingPlanWspaceEdgeFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanWspaceEdgeFields creates a new BillingPlanWspaceEdgeFields selector
func NewBillingPlanWspaceEdgeFields(selection *api.FieldSelection) *BillingPlanWspaceEdgeFields {
	return &BillingPlanWspaceEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingPlanWspaceEdgeFields) Node(selector func(*BillingPlanWspaceFields)) *BillingPlanWspaceEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanWspaceFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingPlanWspaceEdgeFields) Cursor() *BillingPlanWspaceEdgeFields {
	f.selection.AddField("cursor")
	return f
}
