// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// CheckoutSessionFields provides type-safe field selection for CheckoutSession
type CheckoutSessionFields struct {
	selection *api.FieldSelection
}

// NewCheckoutSessionFields creates a new CheckoutSessionFields selector
func NewCheckoutSessionFields(selection *api.FieldSelection) *CheckoutSessionFields {
	return &CheckoutSessionFields{selection: selection}
}

// ID selects the id field
func (f *CheckoutSessionFields) ID() *CheckoutSessionFields {
	f.selection.AddField("id")
	return f
}

// Value selects the value field
func (f *CheckoutSessionFields) Value() *CheckoutSessionFields {
	f.selection.AddField("value")
	return f
}

// Type selects the type field
func (f *CheckoutSessionFields) Type() *CheckoutSessionFields {
	f.selection.AddField("type")
	return f
}
