// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// WorkspaceAppInstallationFields provides type-safe field selection for WorkspaceAppInstallation
type WorkspaceAppInstallationFields struct {
	selection *api.FieldSelection
}

// NewWorkspaceAppInstallationFields creates a new WorkspaceAppInstallationFields selector
func NewWorkspaceAppInstallationFields(selection *api.FieldSelection) *WorkspaceAppInstallationFields {
	return &WorkspaceAppInstallationFields{selection: selection}
}

// ID selects the id field
func (f *WorkspaceAppInstallationFields) ID() *WorkspaceAppInstallationFields {
	f.selection.AddField("id")
	return f
}

// App selects the app field with nested selection
func (f *WorkspaceAppInstallationFields) App(selector func(*AppStoreAppFields)) *WorkspaceAppInstallationFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAppStoreAppFields(child))
	}
	f.selection.AddChild("app", child)
	return f
}

// WorkspaceID selects the workspaceId field
func (f *WorkspaceAppInstallationFields) WorkspaceID() *WorkspaceAppInstallationFields {
	f.selection.AddField("workspaceId")
	return f
}

// Status selects the status field
func (f *WorkspaceAppInstallationFields) Status() *WorkspaceAppInstallationFields {
	f.selection.AddField("status")
	return f
}

// InstalledAt selects the installedAt field
func (f *WorkspaceAppInstallationFields) InstalledAt() *WorkspaceAppInstallationFields {
	f.selection.AddField("installedAt")
	return f
}
