// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ChatbotUserFields provides type-safe field selection for ChatbotUser
type ChatbotUserFields struct {
	selection *api.FieldSelection
}

// NewChatbotUserFields creates a new ChatbotUserFields selector
func NewChatbotUserFields(selection *api.FieldSelection) *ChatbotUserFields {
	return &ChatbotUserFields{selection: selection}
}

// ID selects the id field
func (f *ChatbotUserFields) ID() *ChatbotUserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChatbotUserFields) CreatedAt() *ChatbotUserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChatbotUserFields) UpdatedAt() *ChatbotUserFields {
	f.selection.AddField("updatedAt")
	return f
}

// UserID selects the userID field
func (f *ChatbotUserFields) UserID() *ChatbotUserFields {
	f.selection.AddField("userID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChatbotUserFields) ChatbotID() *ChatbotUserFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChatbotUserFields) WorkspaceID() *ChatbotUserFields {
	f.selection.AddField("workspaceID")
	return f
}

// User selects the user field with nested selection
func (f *ChatbotUserFields) User(selector func(*UserFields)) *ChatbotUserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChatbotUserFields) Chatbot(selector func(*ChatbotFields)) *ChatbotUserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// ChatbotUserConnectionFields provides type-safe field selection for ChatbotUserConnection
type ChatbotUserConnectionFields struct {
	selection *api.FieldSelection
}

// NewChatbotUserConnectionFields creates a new ChatbotUserConnectionFields selector
func NewChatbotUserConnectionFields(selection *api.FieldSelection) *ChatbotUserConnectionFields {
	return &ChatbotUserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotUserConnectionFields) Edges(selector func(*ChatbotUserEdgeFields)) *ChatbotUserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotUserConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotUserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotUserConnectionFields) TotalCount() *ChatbotUserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ChatbotUserEdgeFields provides type-safe field selection for ChatbotUserEdge
type ChatbotUserEdgeFields struct {
	selection *api.FieldSelection
}

// NewChatbotUserEdgeFields creates a new ChatbotUserEdgeFields selector
func NewChatbotUserEdgeFields(selection *api.FieldSelection) *ChatbotUserEdgeFields {
	return &ChatbotUserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotUserEdgeFields) Node(selector func(*ChatbotUserFields)) *ChatbotUserEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotUserEdgeFields) Cursor() *ChatbotUserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
