// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ItemGroupSourceSummaryFields provides type-safe field selection for ItemGroupSourceSummary
type ItemGroupSourceSummaryFields struct {
	selection *api.FieldSelection
}

// NewItemGroupSourceSummaryFields creates a new ItemGroupSourceSummaryFields selector
func NewItemGroupSourceSummaryFields(selection *api.FieldSelection) *ItemGroupSourceSummaryFields {
	return &ItemGroupSourceSummaryFields{selection: selection}
}

// Type selects the type field
func (f *ItemGroupSourceSummaryFields) Type() *ItemGroupSourceSummaryFields {
	f.selection.AddField("type")
	return f
}

// Count selects the count field
func (f *ItemGroupSourceSummaryFields) Count() *ItemGroupSourceSummaryFields {
	f.selection.AddField("count")
	return f
}

// TotalCompleted selects the totalCompleted field
func (f *ItemGroupSourceSummaryFields) TotalCompleted() *ItemGroupSourceSummaryFields {
	f.selection.AddField("totalCompleted")
	return f
}

// TotlaPending selects the totlaPending field
func (f *ItemGroupSourceSummaryFields) TotlaPending() *ItemGroupSourceSummaryFields {
	f.selection.AddField("totlaPending")
	return f
}

// TotalError selects the totalError field
func (f *ItemGroupSourceSummaryFields) TotalError() *ItemGroupSourceSummaryFields {
	f.selection.AddField("totalError")
	return f
}
