// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// NodeFields provides type-safe field selection for Node
type NodeFields struct {
	selection *api.FieldSelection
}

// NewNodeFields creates a new NodeFields selector
func NewNodeFields(selection *api.FieldSelection) *NodeFields {
	return &NodeFields{selection: selection}
}

// ID selects the id field
func (f *NodeFields) ID() *NodeFields {
	f.selection.AddField("id")
	return f
}
