// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// MessageFields provides type-safe field selection for Message
type MessageFields struct {
	selection *api.FieldSelection
}

// NewMessageFields creates a new MessageFields selector
func NewMessageFields(selection *api.FieldSelection) *MessageFields {
	return &MessageFields{selection: selection}
}

// ID selects the id field
func (f *MessageFields) ID() *MessageFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *MessageFields) CreatedAt() *MessageFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *MessageFields) UpdatedAt() *MessageFields {
	f.selection.AddField("updatedAt")
	return f
}

// Role selects the role field
func (f *MessageFields) Role() *MessageFields {
	f.selection.AddField("role")
	return f
}

// Msgid selects the msgid field
func (f *MessageFields) Msgid() *MessageFields {
	f.selection.AddField("msgid")
	return f
}

// Content selects the content field
func (f *MessageFields) Content() *MessageFields {
	f.selection.AddField("content")
	return f
}

// Parts selects the parts field
func (f *MessageFields) Parts() *MessageFields {
	f.selection.AddField("parts")
	return f
}

// PromptTokens selects the promptTokens field
func (f *MessageFields) PromptTokens() *MessageFields {
	f.selection.AddField("promptTokens")
	return f
}

// CompletionTokens selects the completionTokens field
func (f *MessageFields) CompletionTokens() *MessageFields {
	f.selection.AddField("completionTokens")
	return f
}

// TotalTokens selects the totalTokens field
func (f *MessageFields) TotalTokens() *MessageFields {
	f.selection.AddField("totalTokens")
	return f
}

// UserID selects the userID field
func (f *MessageFields) UserID() *MessageFields {
	f.selection.AddField("userID")
	return f
}

// ChannelID selects the channelID field
func (f *MessageFields) ChannelID() *MessageFields {
	f.selection.AddField("channelID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *MessageFields) WorkspaceID() *MessageFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *MessageFields) ChatbotID() *MessageFields {
	f.selection.AddField("chatbotID")
	return f
}

// Channel selects the channel field with nested selection
func (f *MessageFields) Channel(selector func(*ChannelFields)) *MessageFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channel", child)
	return f
}

// User selects the user field with nested selection
func (f *MessageFields) User(selector func(*UserFields)) *MessageFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}

// MessageConnectionFields provides type-safe field selection for MessageConnection
type MessageConnectionFields struct {
	selection *api.FieldSelection
}

// NewMessageConnectionFields creates a new MessageConnectionFields selector
func NewMessageConnectionFields(selection *api.FieldSelection) *MessageConnectionFields {
	return &MessageConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *MessageConnectionFields) Edges(selector func(*MessageEdgeFields)) *MessageConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewMessageEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *MessageConnectionFields) PageInfo(selector func(*PageInfoFields)) *MessageConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *MessageConnectionFields) TotalCount() *MessageConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// MessageEdgeFields provides type-safe field selection for MessageEdge
type MessageEdgeFields struct {
	selection *api.FieldSelection
}

// NewMessageEdgeFields creates a new MessageEdgeFields selector
func NewMessageEdgeFields(selection *api.FieldSelection) *MessageEdgeFields {
	return &MessageEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *MessageEdgeFields) Node(selector func(*MessageFields)) *MessageEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewMessageFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *MessageEdgeFields) Cursor() *MessageEdgeFields {
	f.selection.AddField("cursor")
	return f
}
