// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// GuestFields provides type-safe field selection for Guest
type GuestFields struct {
	selection *api.FieldSelection
}

// NewGuestFields creates a new GuestFields selector
func NewGuestFields(selection *api.FieldSelection) *GuestFields {
	return &GuestFields{selection: selection}
}

// ID selects the id field
func (f *GuestFields) ID() *GuestFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *GuestFields) CreatedAt() *GuestFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *GuestFields) UpdatedAt() *GuestFields {
	f.selection.AddField("updatedAt")
	return f
}

// ExtUserID selects the extUserID field
func (f *GuestFields) ExtUserID() *GuestFields {
	f.selection.AddField("extUserID")
	return f
}

// FirstName selects the firstName field
func (f *GuestFields) FirstName() *GuestFields {
	f.selection.AddField("firstName")
	return f
}

// LastName selects the lastName field
func (f *GuestFields) LastName() *GuestFields {
	f.selection.AddField("lastName")
	return f
}

// Email selects the email field
func (f *GuestFields) Email() *GuestFields {
	f.selection.AddField("email")
	return f
}

// Ip selects the ip field
func (f *GuestFields) Ip() *GuestFields {
	f.selection.AddField("ip")
	return f
}

// ChatbotID selects the chatbotID field
func (f *GuestFields) ChatbotID() *GuestFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *GuestFields) WorkspaceID() *GuestFields {
	f.selection.AddField("workspaceID")
	return f
}

// GuestConnectionFields provides type-safe field selection for GuestConnection
type GuestConnectionFields struct {
	selection *api.FieldSelection
}

// NewGuestConnectionFields creates a new GuestConnectionFields selector
func NewGuestConnectionFields(selection *api.FieldSelection) *GuestConnectionFields {
	return &GuestConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *GuestConnectionFields) Edges(selector func(*GuestEdgeFields)) *GuestConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewGuestEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *GuestConnectionFields) PageInfo(selector func(*PageInfoFields)) *GuestConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *GuestConnectionFields) TotalCount() *GuestConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// GuestEdgeFields provides type-safe field selection for GuestEdge
type GuestEdgeFields struct {
	selection *api.FieldSelection
}

// NewGuestEdgeFields creates a new GuestEdgeFields selector
func NewGuestEdgeFields(selection *api.FieldSelection) *GuestEdgeFields {
	return &GuestEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *GuestEdgeFields) Node(selector func(*GuestFields)) *GuestEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewGuestFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *GuestEdgeFields) Cursor() *GuestEdgeFields {
	f.selection.AddField("cursor")
	return f
}
