// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// AppStoreAppFields provides type-safe field selection for AppStoreApp
type AppStoreAppFields struct {
	selection *api.FieldSelection
}

// NewAppStoreAppFields creates a new AppStoreAppFields selector
func NewAppStoreAppFields(selection *api.FieldSelection) *AppStoreAppFields {
	return &AppStoreAppFields{selection: selection}
}

// ID selects the id field
func (f *AppStoreAppFields) ID() *AppStoreAppFields {
	f.selection.AddField("id")
	return f
}

// Name selects the name field
func (f *AppStoreAppFields) Name() *AppStoreAppFields {
	f.selection.AddField("name")
	return f
}

// Description selects the description field
func (f *AppStoreAppFields) Description() *AppStoreAppFields {
	f.selection.AddField("description")
	return f
}

// IconURL selects the iconUrl field
func (f *AppStoreAppFields) IconURL() *AppStoreAppFields {
	f.selection.AddField("iconUrl")
	return f
}

// Partner selects the partner field with nested selection
func (f *AppStoreAppFields) Partner(selector func(*AppStorePartnerFields)) *AppStoreAppFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAppStorePartnerFields(child))
	}
	f.selection.AddChild("partner", child)
	return f
}
