// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// StudentFields provides type-safe field selection for Student
type StudentFields struct {
	selection *api.FieldSelection
}

// NewStudentFields creates a new StudentFields selector
func NewStudentFields(selection *api.FieldSelection) *StudentFields {
	return &StudentFields{selection: selection}
}

// Name selects the name field
func (f *StudentFields) Name() *StudentFields {
	f.selection.AddField("name")
	return f
}
