// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// BillingPlanFeatureFields provides type-safe field selection for BillingPlanFeature
type BillingPlanFeatureFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanFeatureFields creates a new BillingPlanFeatureFields selector
func NewBillingPlanFeatureFields(selection *api.FieldSelection) *BillingPlanFeatureFields {
	return &BillingPlanFeatureFields{selection: selection}
}

// ID selects the id field
func (f *BillingPlanFeatureFields) ID() *BillingPlanFeatureFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingPlanFeatureFields) CreatedAt() *BillingPlanFeatureFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingPlanFeatureFields) UpdatedAt() *BillingPlanFeatureFields {
	f.selection.AddField("updatedAt")
	return f
}

// FeatureID selects the featureID field
func (f *BillingPlanFeatureFields) FeatureID() *BillingPlanFeatureFields {
	f.selection.AddField("featureID")
	return f
}

// Value selects the value field
func (f *BillingPlanFeatureFields) Value() *BillingPlanFeatureFields {
	f.selection.AddField("value")
	return f
}

// BillingPlanID selects the billingPlanID field
func (f *BillingPlanFeatureFields) BillingPlanID() *BillingPlanFeatureFields {
	f.selection.AddField("billingPlanID")
	return f
}

// BillingPlan selects the billingPlan field with nested selection
func (f *BillingPlanFeatureFields) BillingPlan(selector func(*BillingPlanFields)) *BillingPlanFeatureFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("billingPlan", child)
	return f
}

// BillingFeature selects the billingFeature field with nested selection
func (f *BillingPlanFeatureFields) BillingFeature(selector func(*BillingFeatureFields)) *BillingPlanFeatureFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("billingFeature", child)
	return f
}

// BillingPlanFeatureConnectionFields provides type-safe field selection for BillingPlanFeatureConnection
type BillingPlanFeatureConnectionFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanFeatureConnectionFields creates a new BillingPlanFeatureConnectionFields selector
func NewBillingPlanFeatureConnectionFields(selection *api.FieldSelection) *BillingPlanFeatureConnectionFields {
	return &BillingPlanFeatureConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingPlanFeatureConnectionFields) Edges(selector func(*BillingPlanFeatureEdgeFields)) *BillingPlanFeatureConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingPlanFeatureConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingPlanFeatureConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingPlanFeatureConnectionFields) TotalCount() *BillingPlanFeatureConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// BillingPlanFeatureEdgeFields provides type-safe field selection for BillingPlanFeatureEdge
type BillingPlanFeatureEdgeFields struct {
	selection *api.FieldSelection
}

// NewBillingPlanFeatureEdgeFields creates a new BillingPlanFeatureEdgeFields selector
func NewBillingPlanFeatureEdgeFields(selection *api.FieldSelection) *BillingPlanFeatureEdgeFields {
	return &BillingPlanFeatureEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingPlanFeatureEdgeFields) Node(selector func(*BillingPlanFeatureFields)) *BillingPlanFeatureEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingPlanFeatureEdgeFields) Cursor() *BillingPlanFeatureEdgeFields {
	f.selection.AddField("cursor")
	return f
}
