// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// AppSessionResponseFields provides type-safe field selection for AppSessionResponse
type AppSessionResponseFields struct {
	selection *api.FieldSelection
}

// NewAppSessionResponseFields creates a new AppSessionResponseFields selector
func NewAppSessionResponseFields(selection *api.FieldSelection) *AppSessionResponseFields {
	return &AppSessionResponseFields{selection: selection}
}

// SessionToken selects the sessionToken field
func (f *AppSessionResponseFields) SessionToken() *AppSessionResponseFields {
	f.selection.AddField("sessionToken")
	return f
}

// LaunchURL selects the launchUrl field
func (f *AppSessionResponseFields) LaunchURL() *AppSessionResponseFields {
	f.selection.AddField("launchUrl")
	return f
}

// ExpiresAt selects the expiresAt field
func (f *AppSessionResponseFields) ExpiresAt() *AppSessionResponseFields {
	f.selection.AddField("expiresAt")
	return f
}
