// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// HtmlToMarkdownResponseFields provides type-safe field selection for HtmlToMarkdownResponse
type HtmlToMarkdownResponseFields struct {
	selection *api.FieldSelection
}

// NewHtmlToMarkdownResponseFields creates a new HtmlToMarkdownResponseFields selector
func NewHtmlToMarkdownResponseFields(selection *api.FieldSelection) *HtmlToMarkdownResponseFields {
	return &HtmlToMarkdownResponseFields{selection: selection}
}

// Content selects the content field
func (f *HtmlToMarkdownResponseFields) Content() *HtmlToMarkdownResponseFields {
	f.selection.AddField("content")
	return f
}
