// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// FolderFields provides type-safe field selection for Folder
type FolderFields struct {
	selection *api.FieldSelection
}

// NewFolderFields creates a new FolderFields selector
func NewFolderFields(selection *api.FieldSelection) *FolderFields {
	return &FolderFields{selection: selection}
}

// ID selects the id field
func (f *FolderFields) ID() *FolderFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *FolderFields) CreatedAt() *FolderFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *FolderFields) UpdatedAt() *FolderFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *FolderFields) Name() *FolderFields {
	f.selection.AddField("name")
	return f
}

// ChatbotID selects the chatbotID field
func (f *FolderFields) ChatbotID() *FolderFields {
	f.selection.AddField("chatbotID")
	return f
}

// OwnerID selects the ownerID field
func (f *FolderFields) OwnerID() *FolderFields {
	f.selection.AddField("ownerID")
	return f
}

// Position selects the position field
func (f *FolderFields) Position() *FolderFields {
	f.selection.AddField("position")
	return f
}

// Channels selects the channels field with nested selection
func (f *FolderFields) Channels(selector func(*ChannelFields)) *FolderFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channels", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *FolderFields) Chatbot(selector func(*ChatbotFields)) *FolderFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// Owner selects the owner field with nested selection
func (f *FolderFields) Owner(selector func(*UserFields)) *FolderFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("owner", child)
	return f
}

// ChannelCount selects the channelCount field
func (f *FolderFields) ChannelCount() *FolderFields {
	f.selection.AddField("channelCount")
	return f
}

// FolderConnectionFields provides type-safe field selection for FolderConnection
type FolderConnectionFields struct {
	selection *api.FieldSelection
}

// NewFolderConnectionFields creates a new FolderConnectionFields selector
func NewFolderConnectionFields(selection *api.FieldSelection) *FolderConnectionFields {
	return &FolderConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FolderConnectionFields) Edges(selector func(*FolderEdgeFields)) *FolderConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFolderEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FolderConnectionFields) PageInfo(selector func(*PageInfoFields)) *FolderConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FolderConnectionFields) TotalCount() *FolderConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// FolderEdgeFields provides type-safe field selection for FolderEdge
type FolderEdgeFields struct {
	selection *api.FieldSelection
}

// NewFolderEdgeFields creates a new FolderEdgeFields selector
func NewFolderEdgeFields(selection *api.FieldSelection) *FolderEdgeFields {
	return &FolderEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FolderEdgeFields) Node(selector func(*FolderFields)) *FolderEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FolderEdgeFields) Cursor() *FolderEdgeFields {
	f.selection.AddField("cursor")
	return f
}
