// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// UrlToHtmlResponseFields provides type-safe field selection for UrlToHtmlResponse
type UrlToHtmlResponseFields struct {
	selection *api.FieldSelection
}

// NewUrlToHtmlResponseFields creates a new UrlToHtmlResponseFields selector
func NewUrlToHtmlResponseFields(selection *api.FieldSelection) *UrlToHtmlResponseFields {
	return &UrlToHtmlResponseFields{selection: selection}
}

// Content selects the content field
func (f *UrlToHtmlResponseFields) Content() *UrlToHtmlResponseFields {
	f.selection.AddField("content")
	return f
}

// StatusCode selects the statusCode field
func (f *UrlToHtmlResponseFields) StatusCode() *UrlToHtmlResponseFields {
	f.selection.AddField("statusCode")
	return f
}
