// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ChannelFields provides type-safe field selection for Channel
type ChannelFields struct {
	selection *api.FieldSelection
}

// NewChannelFields creates a new ChannelFields selector
func NewChannelFields(selection *api.FieldSelection) *ChannelFields {
	return &ChannelFields{selection: selection}
}

// ID selects the id field
func (f *ChannelFields) ID() *ChannelFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChannelFields) CreatedAt() *ChannelFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChannelFields) UpdatedAt() *ChannelFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *ChannelFields) Name() *ChannelFields {
	f.selection.AddField("name")
	return f
}

// IsPublic selects the isPublic field
func (f *ChannelFields) IsPublic() *ChannelFields {
	f.selection.AddField("isPublic")
	return f
}

// GuestID selects the guestID field
func (f *ChannelFields) GuestID() *ChannelFields {
	f.selection.AddField("guestID")
	return f
}

// OwnerID selects the ownerID field
func (f *ChannelFields) OwnerID() *ChannelFields {
	f.selection.AddField("ownerID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChannelFields) WorkspaceID() *ChannelFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChannelFields) ChatbotID() *ChannelFields {
	f.selection.AddField("chatbotID")
	return f
}

// FolderID selects the folderID field
func (f *ChannelFields) FolderID() *ChannelFields {
	f.selection.AddField("folderID")
	return f
}

// Messages selects the messages field with nested selection
func (f *ChannelFields) Messages(selector func(*MessageConnectionFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewMessageConnectionFields(child))
	}
	f.selection.AddChild("messages", child)
	return f
}

// Users selects the users field with nested selection
func (f *ChannelFields) Users(selector func(*UserConnectionFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserConnectionFields(child))
	}
	f.selection.AddChild("users", child)
	return f
}

// Owner selects the owner field with nested selection
func (f *ChannelFields) Owner(selector func(*UserFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("owner", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChannelFields) Chatbot(selector func(*ChatbotFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// Folder selects the folder field with nested selection
func (f *ChannelFields) Folder(selector func(*FolderFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("folder", child)
	return f
}

// ChannelUsers selects the channelUsers field with nested selection
func (f *ChannelFields) ChannelUsers(selector func(*ChannelUserConnectionFields)) *ChannelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserConnectionFields(child))
	}
	f.selection.AddChild("channelUsers", child)
	return f
}

// ChannelConnectionFields provides type-safe field selection for ChannelConnection
type ChannelConnectionFields struct {
	selection *api.FieldSelection
}

// NewChannelConnectionFields creates a new ChannelConnectionFields selector
func NewChannelConnectionFields(selection *api.FieldSelection) *ChannelConnectionFields {
	return &ChannelConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChannelConnectionFields) Edges(selector func(*ChannelEdgeFields)) *ChannelConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChannelConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChannelConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChannelConnectionFields) TotalCount() *ChannelConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ChannelEdgeFields provides type-safe field selection for ChannelEdge
type ChannelEdgeFields struct {
	selection *api.FieldSelection
}

// NewChannelEdgeFields creates a new ChannelEdgeFields selector
func NewChannelEdgeFields(selection *api.FieldSelection) *ChannelEdgeFields {
	return &ChannelEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChannelEdgeFields) Node(selector func(*ChannelFields)) *ChannelEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChannelEdgeFields) Cursor() *ChannelEdgeFields {
	f.selection.AddField("cursor")
	return f
}
