// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// TmpItemFields provides type-safe field selection for TmpItem
type TmpItemFields struct {
	selection *api.FieldSelection
}

// NewTmpItemFields creates a new TmpItemFields selector
func NewTmpItemFields(selection *api.FieldSelection) *TmpItemFields {
	return &TmpItemFields{selection: selection}
}

// ID selects the id field
func (f *TmpItemFields) ID() *TmpItemFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *TmpItemFields) CreatedAt() *TmpItemFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *TmpItemFields) UpdatedAt() *TmpItemFields {
	f.selection.AddField("updatedAt")
	return f
}

// ItemID selects the itemID field
func (f *TmpItemFields) ItemID() *TmpItemFields {
	f.selection.AddField("itemID")
	return f
}

// BatchID selects the batchID field
func (f *TmpItemFields) BatchID() *TmpItemFields {
	f.selection.AddField("batchID")
	return f
}

// EmbeddingStatus selects the embeddingStatus field
func (f *TmpItemFields) EmbeddingStatus() *TmpItemFields {
	f.selection.AddField("embeddingStatus")
	return f
}

// EmbeddingMsg selects the embeddingMsg field
func (f *TmpItemFields) EmbeddingMsg() *TmpItemFields {
	f.selection.AddField("embeddingMsg")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *TmpItemFields) WorkspaceID() *TmpItemFields {
	f.selection.AddField("workspaceID")
	return f
}

// ItemGroupID selects the itemGroupID field
func (f *TmpItemFields) ItemGroupID() *TmpItemFields {
	f.selection.AddField("itemGroupID")
	return f
}

// ItemGroupSourceID selects the itemGroupSourceID field
func (f *TmpItemFields) ItemGroupSourceID() *TmpItemFields {
	f.selection.AddField("itemGroupSourceID")
	return f
}
