// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ItemFields provides type-safe field selection for Item
type ItemFields struct {
	selection *api.FieldSelection
}

// NewItemFields creates a new ItemFields selector
func NewItemFields(selection *api.FieldSelection) *ItemFields {
	return &ItemFields{selection: selection}
}

// ID selects the id field
func (f *ItemFields) ID() *ItemFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ItemFields) CreatedAt() *ItemFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ItemFields) UpdatedAt() *ItemFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *ItemFields) Name() *ItemFields {
	f.selection.AddField("name")
	return f
}

// EmbeddingStatus selects the embeddingStatus field
func (f *ItemFields) EmbeddingStatus() *ItemFields {
	f.selection.AddField("embeddingStatus")
	return f
}

// EmbeddingMsg selects the embeddingMsg field
func (f *ItemFields) EmbeddingMsg() *ItemFields {
	f.selection.AddField("embeddingMsg")
	return f
}

// Content selects the content field
func (f *ItemFields) Content() *ItemFields {
	f.selection.AddField("content")
	return f
}

// Filename selects the filename field
func (f *ItemFields) Filename() *ItemFields {
	f.selection.AddField("filename")
	return f
}

// ContentChars selects the contentChars field
func (f *ItemFields) ContentChars() *ItemFields {
	f.selection.AddField("contentChars")
	return f
}

// AiModelID selects the aiModelID field
func (f *ItemFields) AiModelID() *ItemFields {
	f.selection.AddField("aiModelID")
	return f
}

// VecDims selects the vecDims field
func (f *ItemFields) VecDims() *ItemFields {
	f.selection.AddField("vecDims")
	return f
}

// TotalTokens selects the totalTokens field
func (f *ItemFields) TotalTokens() *ItemFields {
	f.selection.AddField("totalTokens")
	return f
}

// Metadata selects the metadata field
func (f *ItemFields) Metadata() *ItemFields {
	f.selection.AddField("metadata")
	return f
}

// ExtRef selects the extRef field
func (f *ItemFields) ExtRef() *ItemFields {
	f.selection.AddField("extRef")
	return f
}

// ExtID selects the extID field
func (f *ItemFields) ExtID() *ItemFields {
	f.selection.AddField("extID")
	return f
}

// ExtMetadata selects the extMetadata field
func (f *ItemFields) ExtMetadata() *ItemFields {
	f.selection.AddField("extMetadata")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ItemFields) WorkspaceID() *ItemFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ItemFields) ChatbotID() *ItemFields {
	f.selection.AddField("chatbotID")
	return f
}

// ItemGroupSourceID selects the itemGroupSourceID field
func (f *ItemFields) ItemGroupSourceID() *ItemFields {
	f.selection.AddField("itemGroupSourceID")
	return f
}

// ItemGroupID selects the itemGroupID field
func (f *ItemFields) ItemGroupID() *ItemFields {
	f.selection.AddField("itemGroupID")
	return f
}

// ItemConnectionFields provides type-safe field selection for ItemConnection
type ItemConnectionFields struct {
	selection *api.FieldSelection
}

// NewItemConnectionFields creates a new ItemConnectionFields selector
func NewItemConnectionFields(selection *api.FieldSelection) *ItemConnectionFields {
	return &ItemConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ItemConnectionFields) Edges(selector func(*ItemEdgeFields)) *ItemConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ItemConnectionFields) PageInfo(selector func(*PageInfoFields)) *ItemConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ItemConnectionFields) TotalCount() *ItemConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ItemEdgeFields provides type-safe field selection for ItemEdge
type ItemEdgeFields struct {
	selection *api.FieldSelection
}

// NewItemEdgeFields creates a new ItemEdgeFields selector
func NewItemEdgeFields(selection *api.FieldSelection) *ItemEdgeFields {
	return &ItemEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ItemEdgeFields) Node(selector func(*ItemFields)) *ItemEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ItemEdgeFields) Cursor() *ItemEdgeFields {
	f.selection.AddField("cursor")
	return f
}
