// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// AiModelFields provides type-safe field selection for AiModel
type AiModelFields struct {
	selection *api.FieldSelection
}

// NewAiModelFields creates a new AiModelFields selector
func NewAiModelFields(selection *api.FieldSelection) *AiModelFields {
	return &AiModelFields{selection: selection}
}

// ID selects the id field
func (f *AiModelFields) ID() *AiModelFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *AiModelFields) CreatedAt() *AiModelFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *AiModelFields) UpdatedAt() *AiModelFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *AiModelFields) Name() *AiModelFields {
	f.selection.AddField("name")
	return f
}

// ProviderName selects the providerName field
func (f *AiModelFields) ProviderName() *AiModelFields {
	f.selection.AddField("providerName")
	return f
}

// ModelID selects the modelID field
func (f *AiModelFields) ModelID() *AiModelFields {
	f.selection.AddField("modelID")
	return f
}

// BaseURL selects the baseURL field
func (f *AiModelFields) BaseURL() *AiModelFields {
	f.selection.AddField("baseURL")
	return f
}

// APIKey selects the apiKey field
func (f *AiModelFields) APIKey() *AiModelFields {
	f.selection.AddField("apiKey")
	return f
}

// OrgID selects the orgID field
func (f *AiModelFields) OrgID() *AiModelFields {
	f.selection.AddField("orgID")
	return f
}

// Descr selects the descr field
func (f *AiModelFields) Descr() *AiModelFields {
	f.selection.AddField("descr")
	return f
}

// Status selects the status field
func (f *AiModelFields) Status() *AiModelFields {
	f.selection.AddField("status")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *AiModelFields) WorkspaceID() *AiModelFields {
	f.selection.AddField("workspaceID")
	return f
}

// HasChat selects the hasChat field
func (f *AiModelFields) HasChat() *AiModelFields {
	f.selection.AddField("hasChat")
	return f
}

// HasEmbeddings selects the hasEmbeddings field
func (f *AiModelFields) HasEmbeddings() *AiModelFields {
	f.selection.AddField("hasEmbeddings")
	return f
}

// IsWildai selects the isWildai field
func (f *AiModelFields) IsWildai() *AiModelFields {
	f.selection.AddField("isWildai")
	return f
}

// IntProviderName selects the intProviderName field
func (f *AiModelFields) IntProviderName() *AiModelFields {
	f.selection.AddField("intProviderName")
	return f
}

// IntBaseURL selects the intBaseURL field
func (f *AiModelFields) IntBaseURL() *AiModelFields {
	f.selection.AddField("intBaseURL")
	return f
}

// IntApikey selects the intAPIKey field
func (f *AiModelFields) IntApikey() *AiModelFields {
	f.selection.AddField("intAPIKey")
	return f
}

// IntOrgID selects the intOrgID field
func (f *AiModelFields) IntOrgID() *AiModelFields {
	f.selection.AddField("intOrgID")
	return f
}

// IntModelID selects the intModelID field
func (f *AiModelFields) IntModelID() *AiModelFields {
	f.selection.AddField("intModelID")
	return f
}

// MaxDims selects the maxDims field
func (f *AiModelFields) MaxDims() *AiModelFields {
	f.selection.AddField("maxDims")
	return f
}

// MaxTokens selects the maxTokens field
func (f *AiModelFields) MaxTokens() *AiModelFields {
	f.selection.AddField("maxTokens")
	return f
}

// Chatbots selects the chatbots field with nested selection
func (f *AiModelFields) Chatbots(selector func(*ChatbotFields)) *AiModelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbots", child)
	return f
}

// FuncTools selects the funcTools field with nested selection
func (f *AiModelFields) FuncTools(selector func(*FuncToolFields)) *AiModelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTools", child)
	return f
}

// ItemGroups selects the itemGroups field with nested selection
func (f *AiModelFields) ItemGroups(selector func(*ItemGroupFields)) *AiModelFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("itemGroups", child)
	return f
}

// AiModelConnectionFields provides type-safe field selection for AiModelConnection
type AiModelConnectionFields struct {
	selection *api.FieldSelection
}

// NewAiModelConnectionFields creates a new AiModelConnectionFields selector
func NewAiModelConnectionFields(selection *api.FieldSelection) *AiModelConnectionFields {
	return &AiModelConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *AiModelConnectionFields) Edges(selector func(*AiModelEdgeFields)) *AiModelConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *AiModelConnectionFields) PageInfo(selector func(*PageInfoFields)) *AiModelConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *AiModelConnectionFields) TotalCount() *AiModelConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// AiModelEdgeFields provides type-safe field selection for AiModelEdge
type AiModelEdgeFields struct {
	selection *api.FieldSelection
}

// NewAiModelEdgeFields creates a new AiModelEdgeFields selector
func NewAiModelEdgeFields(selection *api.FieldSelection) *AiModelEdgeFields {
	return &AiModelEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *AiModelEdgeFields) Node(selector func(*AiModelFields)) *AiModelEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *AiModelEdgeFields) Cursor() *AiModelEdgeFields {
	f.selection.AddField("cursor")
	return f
}
