// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ChatbotFields provides type-safe field selection for Chatbot
type ChatbotFields struct {
	selection *api.FieldSelection
}

// NewChatbotFields creates a new ChatbotFields selector
func NewChatbotFields(selection *api.FieldSelection) *ChatbotFields {
	return &ChatbotFields{selection: selection}
}

// ID selects the id field
func (f *ChatbotFields) ID() *ChatbotFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChatbotFields) CreatedAt() *ChatbotFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChatbotFields) UpdatedAt() *ChatbotFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *ChatbotFields) Name() *ChatbotFields {
	f.selection.AddField("name")
	return f
}

// ShortDescr selects the shortDescr field
func (f *ChatbotFields) ShortDescr() *ChatbotFields {
	f.selection.AddField("shortDescr")
	return f
}

// Active selects the active field
func (f *ChatbotFields) Active() *ChatbotFields {
	f.selection.AddField("active")
	return f
}

// IsPublic selects the isPublic field
func (f *ChatbotFields) IsPublic() *ChatbotFields {
	f.selection.AddField("isPublic")
	return f
}

// Instruction selects the instruction field
func (f *ChatbotFields) Instruction() *ChatbotFields {
	f.selection.AddField("instruction")
	return f
}

// Temperature selects the temperature field
func (f *ChatbotFields) Temperature() *ChatbotFields {
	f.selection.AddField("temperature")
	return f
}

// OverviewDescr selects the overviewDescr field
func (f *ChatbotFields) OverviewDescr() *ChatbotFields {
	f.selection.AddField("overviewDescr")
	return f
}

// TotalChars selects the totalChars field
func (f *ChatbotFields) TotalChars() *ChatbotFields {
	f.selection.AddField("totalChars")
	return f
}

// Text selects the text field
func (f *ChatbotFields) Text() *ChatbotFields {
	f.selection.AddField("text")
	return f
}

// ColorUserMessage selects the colorUserMessage field
func (f *ChatbotFields) ColorUserMessage() *ChatbotFields {
	f.selection.AddField("colorUserMessage")
	return f
}

// InitialMessage1 selects the initialMessage1 field
func (f *ChatbotFields) InitialMessage1() *ChatbotFields {
	f.selection.AddField("initialMessage1")
	return f
}

// InitialMessage2 selects the initialMessage2 field
func (f *ChatbotFields) InitialMessage2() *ChatbotFields {
	f.selection.AddField("initialMessage2")
	return f
}

// ColorBubble selects the colorBubble field
func (f *ChatbotFields) ColorBubble() *ChatbotFields {
	f.selection.AddField("colorBubble")
	return f
}

// ChatButtonAlign selects the chatButtonAlign field
func (f *ChatbotFields) ChatButtonAlign() *ChatbotFields {
	f.selection.AddField("chatButtonAlign")
	return f
}

// DisplayName selects the displayName field
func (f *ChatbotFields) DisplayName() *ChatbotFields {
	f.selection.AddField("displayName")
	return f
}

// ChatIconURL selects the chatIconURL field
func (f *ChatbotFields) ChatIconURL() *ChatbotFields {
	f.selection.AddField("chatIconURL")
	return f
}

// BotIconURL selects the botIconURL field
func (f *ChatbotFields) BotIconURL() *ChatbotFields {
	f.selection.AddField("botIconURL")
	return f
}

// MessagePlaceholder selects the messagePlaceholder field
func (f *ChatbotFields) MessagePlaceholder() *ChatbotFields {
	f.selection.AddField("messagePlaceholder")
	return f
}

// Footer selects the footer field
func (f *ChatbotFields) Footer() *ChatbotFields {
	f.selection.AddField("footer")
	return f
}

// Theme selects the theme field
func (f *ChatbotFields) Theme() *ChatbotFields {
	f.selection.AddField("theme")
	return f
}

// AutoShowPopupAfter selects the autoShowPopupAfter field
func (f *ChatbotFields) AutoShowPopupAfter() *ChatbotFields {
	f.selection.AddField("autoShowPopupAfter")
	return f
}

// AiModelID selects the aiModelID field
func (f *ChatbotFields) AiModelID() *ChatbotFields {
	f.selection.AddField("aiModelID")
	return f
}

// SbyteUserID selects the sbyteUserID field
func (f *ChatbotFields) SbyteUserID() *ChatbotFields {
	f.selection.AddField("sbyteUserID")
	return f
}

// AiUserID selects the aiUserID field
func (f *ChatbotFields) AiUserID() *ChatbotFields {
	f.selection.AddField("aiUserID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChatbotFields) WorkspaceID() *ChatbotFields {
	f.selection.AddField("workspaceID")
	return f
}

// IsFavorite selects the isFavorite field
func (f *ChatbotFields) IsFavorite() *ChatbotFields {
	f.selection.AddField("isFavorite")
	return f
}

// IsDebug selects the isDebug field
func (f *ChatbotFields) IsDebug() *ChatbotFields {
	f.selection.AddField("isDebug")
	return f
}

// CacheDisabled selects the cacheDisabled field
func (f *ChatbotFields) CacheDisabled() *ChatbotFields {
	f.selection.AddField("cacheDisabled")
	return f
}

// LeadNameEnabled selects the leadNameEnabled field
func (f *ChatbotFields) LeadNameEnabled() *ChatbotFields {
	f.selection.AddField("leadNameEnabled")
	return f
}

// LeadEmailEnabled selects the leadEmailEnabled field
func (f *ChatbotFields) LeadEmailEnabled() *ChatbotFields {
	f.selection.AddField("leadEmailEnabled")
	return f
}

// LeadPhoneEnabled selects the leadPhoneEnabled field
func (f *ChatbotFields) LeadPhoneEnabled() *ChatbotFields {
	f.selection.AddField("leadPhoneEnabled")
	return f
}

// Users selects the users field with nested selection
func (f *ChatbotFields) Users(selector func(*UserFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("users", child)
	return f
}

// Channels selects the channels field with nested selection
func (f *ChatbotFields) Channels(selector func(*ChannelFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channels", child)
	return f
}

// Folders selects the folders field with nested selection
func (f *ChatbotFields) Folders(selector func(*FolderFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("folders", child)
	return f
}

// FuncTools selects the funcTools field with nested selection
func (f *ChatbotFields) FuncTools(selector func(*FuncToolConnectionFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolConnectionFields(child))
	}
	f.selection.AddChild("funcTools", child)
	return f
}

// AiModel selects the aiModel field with nested selection
func (f *ChatbotFields) AiModel(selector func(*AiModelFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelFields(child))
	}
	f.selection.AddChild("aiModel", child)
	return f
}

// ChatbotUsers selects the chatbotUsers field with nested selection
func (f *ChatbotFields) ChatbotUsers(selector func(*ChatbotUserFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserFields(child))
	}
	f.selection.AddChild("chatbotUsers", child)
	return f
}

// ChatbotTools selects the chatbotTools field with nested selection
func (f *ChatbotFields) ChatbotTools(selector func(*ChatbotToolConnectionFields)) *ChatbotFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolConnectionFields(child))
	}
	f.selection.AddChild("chatbotTools", child)
	return f
}

// ChatbotConnectionFields provides type-safe field selection for ChatbotConnection
type ChatbotConnectionFields struct {
	selection *api.FieldSelection
}

// NewChatbotConnectionFields creates a new ChatbotConnectionFields selector
func NewChatbotConnectionFields(selection *api.FieldSelection) *ChatbotConnectionFields {
	return &ChatbotConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotConnectionFields) Edges(selector func(*ChatbotEdgeFields)) *ChatbotConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotConnectionFields) TotalCount() *ChatbotConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ChatbotEdgeFields provides type-safe field selection for ChatbotEdge
type ChatbotEdgeFields struct {
	selection *api.FieldSelection
}

// NewChatbotEdgeFields creates a new ChatbotEdgeFields selector
func NewChatbotEdgeFields(selection *api.FieldSelection) *ChatbotEdgeFields {
	return &ChatbotEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotEdgeFields) Node(selector func(*ChatbotFields)) *ChatbotEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotEdgeFields) Cursor() *ChatbotEdgeFields {
	f.selection.AddField("cursor")
	return f
}
