// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// LeadFields provides type-safe field selection for Lead
type LeadFields struct {
	selection *api.FieldSelection
}

// NewLeadFields creates a new LeadFields selector
func NewLeadFields(selection *api.FieldSelection) *LeadFields {
	return &LeadFields{selection: selection}
}

// ID selects the id field
func (f *LeadFields) ID() *LeadFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *LeadFields) CreatedAt() *LeadFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *LeadFields) UpdatedAt() *LeadFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *LeadFields) Name() *LeadFields {
	f.selection.AddField("name")
	return f
}

// Email selects the email field
func (f *LeadFields) Email() *LeadFields {
	f.selection.AddField("email")
	return f
}

// Phone selects the phone field
func (f *LeadFields) Phone() *LeadFields {
	f.selection.AddField("phone")
	return f
}

// Company selects the company field
func (f *LeadFields) Company() *LeadFields {
	f.selection.AddField("company")
	return f
}

// Ip selects the ip field
func (f *LeadFields) Ip() *LeadFields {
	f.selection.AddField("ip")
	return f
}

// GuestUserID selects the guestUserID field
func (f *LeadFields) GuestUserID() *LeadFields {
	f.selection.AddField("guestUserID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *LeadFields) ChatbotID() *LeadFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *LeadFields) WorkspaceID() *LeadFields {
	f.selection.AddField("workspaceID")
	return f
}

// LeadConnectionFields provides type-safe field selection for LeadConnection
type LeadConnectionFields struct {
	selection *api.FieldSelection
}

// NewLeadConnectionFields creates a new LeadConnectionFields selector
func NewLeadConnectionFields(selection *api.FieldSelection) *LeadConnectionFields {
	return &LeadConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *LeadConnectionFields) Edges(selector func(*LeadEdgeFields)) *LeadConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewLeadEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *LeadConnectionFields) PageInfo(selector func(*PageInfoFields)) *LeadConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *LeadConnectionFields) TotalCount() *LeadConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// LeadEdgeFields provides type-safe field selection for LeadEdge
type LeadEdgeFields struct {
	selection *api.FieldSelection
}

// NewLeadEdgeFields creates a new LeadEdgeFields selector
func NewLeadEdgeFields(selection *api.FieldSelection) *LeadEdgeFields {
	return &LeadEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *LeadEdgeFields) Node(selector func(*LeadFields)) *LeadEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewLeadFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *LeadEdgeFields) Cursor() *LeadEdgeFields {
	f.selection.AddField("cursor")
	return f
}
