// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ItemInfoFields provides type-safe field selection for ItemInfo
type ItemInfoFields struct {
	selection *api.FieldSelection
}

// NewItemInfoFields creates a new ItemInfoFields selector
func NewItemInfoFields(selection *api.FieldSelection) *ItemInfoFields {
	return &ItemInfoFields{selection: selection}
}

// ID selects the id field
func (f *ItemInfoFields) ID() *ItemInfoFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ItemInfoFields) CreatedAt() *ItemInfoFields {
	f.selection.AddField("createdAt")
	return f
}

// Name selects the name field
func (f *ItemInfoFields) Name() *ItemInfoFields {
	f.selection.AddField("name")
	return f
}

// FileName selects the fileName field
func (f *ItemInfoFields) FileName() *ItemInfoFields {
	f.selection.AddField("fileName")
	return f
}

// Metadata selects the metadata field
func (f *ItemInfoFields) Metadata() *ItemInfoFields {
	f.selection.AddField("metadata")
	return f
}

// ExtRef selects the extRef field
func (f *ItemInfoFields) ExtRef() *ItemInfoFields {
	f.selection.AddField("extRef")
	return f
}

// ExtID selects the extID field
func (f *ItemInfoFields) ExtID() *ItemInfoFields {
	f.selection.AddField("extID")
	return f
}

// ExtMetadata selects the extMetadata field
func (f *ItemInfoFields) ExtMetadata() *ItemInfoFields {
	f.selection.AddField("extMetadata")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ItemInfoFields) WorkspaceID() *ItemInfoFields {
	f.selection.AddField("workspaceID")
	return f
}
