// Code generated by gqlsdk. DO NOT EDIT.

package fields

import "testsdk/api"

// ChannelUserFields provides type-safe field selection for ChannelUser
type ChannelUserFields struct {
	selection *api.FieldSelection
}

// NewChannelUserFields creates a new ChannelUserFields selector
func NewChannelUserFields(selection *api.FieldSelection) *ChannelUserFields {
	return &ChannelUserFields{selection: selection}
}

// ID selects the id field
func (f *ChannelUserFields) ID() *ChannelUserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChannelUserFields) CreatedAt() *ChannelUserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChannelUserFields) UpdatedAt() *ChannelUserFields {
	f.selection.AddField("updatedAt")
	return f
}

// UserID selects the userID field
func (f *ChannelUserFields) UserID() *ChannelUserFields {
	f.selection.AddField("userID")
	return f
}

// ChannelID selects the channelID field
func (f *ChannelUserFields) ChannelID() *ChannelUserFields {
	f.selection.AddField("channelID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChannelUserFields) WorkspaceID() *ChannelUserFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChannelUserFields) ChatbotID() *ChannelUserFields {
	f.selection.AddField("chatbotID")
	return f
}

// User selects the user field with nested selection
func (f *ChannelUserFields) User(selector func(*UserFields)) *ChannelUserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}

// Channel selects the channel field with nested selection
func (f *ChannelUserFields) Channel(selector func(*ChannelFields)) *ChannelUserFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channel", child)
	return f
}

// ChannelUserConnectionFields provides type-safe field selection for ChannelUserConnection
type ChannelUserConnectionFields struct {
	selection *api.FieldSelection
}

// NewChannelUserConnectionFields creates a new ChannelUserConnectionFields selector
func NewChannelUserConnectionFields(selection *api.FieldSelection) *ChannelUserConnectionFields {
	return &ChannelUserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChannelUserConnectionFields) Edges(selector func(*ChannelUserEdgeFields)) *ChannelUserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChannelUserConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChannelUserConnectionFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChannelUserConnectionFields) TotalCount() *ChannelUserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}

// ChannelUserEdgeFields provides type-safe field selection for ChannelUserEdge
type ChannelUserEdgeFields struct {
	selection *api.FieldSelection
}

// NewChannelUserEdgeFields creates a new ChannelUserEdgeFields selector
func NewChannelUserEdgeFields(selection *api.FieldSelection) *ChannelUserEdgeFields {
	return &ChannelUserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChannelUserEdgeFields) Node(selector func(*ChannelUserFields)) *ChannelUserEdgeFields {
	child := api.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChannelUserEdgeFields) Cursor() *ChannelUserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
