// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// WorkspaceDetailBuilder builds a query for workspaceDetail
type WorkspaceDetailBuilder struct {
	*api.BaseBuilder
}

// Select configures which fields to return
func (b *WorkspaceDetailBuilder) Select(selector func(*fields.WorkspaceDetailFields)) *WorkspaceDetailBuilder {
	selector(fields.NewWorkspaceDetailFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *WorkspaceDetailBuilder) Execute(ctx context.Context) (*api.WorkspaceDetail, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result *api.WorkspaceDetail `json:"workspaceDetail"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
