// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemGroupsBuilder builds a query for itemGroups
type ItemGroupsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ItemGroupsBuilder) After(v *string) *ItemGroupsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemGroupsBuilder) First(v *int) *ItemGroupsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemGroupsBuilder) Before(v *string) *ItemGroupsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemGroupsBuilder) Last(v *int) *ItemGroupsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemGroupsBuilder) OrderBy(v []api.ItemGroupOrder) *ItemGroupsBuilder {
	b.SetArg("orderBy", v, "[ItemGroupOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemGroupsBuilder) Where(v *api.ItemGroupWhereInput) *ItemGroupsBuilder {
	b.SetArg("where", v, "ItemGroupWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemGroupsBuilder) Select(selector func(*fields.ItemGroupConnectionFields)) *ItemGroupsBuilder {
	selector(fields.NewItemGroupConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupsBuilder) Execute(ctx context.Context) (api.ItemGroupConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ItemGroupConnection `json:"itemGroups"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ItemGroupConnection{}, err
	}

	return response.Data.Result, nil
}
