// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// BillingPlanWspacesBuilder builds a query for billingPlanWspaces
type BillingPlanWspacesBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *BillingPlanWspacesBuilder) After(v *string) *BillingPlanWspacesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingPlanWspacesBuilder) First(v *int) *BillingPlanWspacesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingPlanWspacesBuilder) Before(v *string) *BillingPlanWspacesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingPlanWspacesBuilder) Last(v *int) *BillingPlanWspacesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingPlanWspacesBuilder) Select(selector func(*fields.BillingPlanWspaceConnectionFields)) *BillingPlanWspacesBuilder {
	selector(fields.NewBillingPlanWspaceConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingPlanWspacesBuilder) Execute(ctx context.Context) (api.BillingPlanWspaceConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.BillingPlanWspaceConnection `json:"billingPlanWspaces"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.BillingPlanWspaceConnection{}, err
	}

	return response.Data.Result, nil
}
