// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// BillingCustomPlansBuilder builds a query for billingCustomPlans
type BillingCustomPlansBuilder struct {
	*api.BaseBuilder
}

// Select configures which fields to return
func (b *BillingCustomPlansBuilder) Select(selector func(*fields.BillingPlanFields)) *BillingCustomPlansBuilder {
	selector(fields.NewBillingPlanFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingCustomPlansBuilder) Execute(ctx context.Context) ([]*api.BillingPlan, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []*api.BillingPlan `json:"billingCustomPlans"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
