// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// NodesBuilder builds a query for nodes
type NodesBuilder struct {
	*api.BaseBuilder
}

// Ids sets the ids argument
func (b *NodesBuilder) Ids(v []string) *NodesBuilder {
	b.SetArg("ids", v, "[ID!]!")
	return b
}

// Select configures which fields to return
func (b *NodesBuilder) Select(selector func(*fields.NodeFields)) *NodesBuilder {
	selector(fields.NewNodeFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *NodesBuilder) Execute(ctx context.Context) ([]*api.Node, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []*api.Node `json:"nodes"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
