// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
)

// IsAppInstalledBuilder builds a query for isAppInstalled
type IsAppInstalledBuilder struct {
	*api.BaseBuilder
}

// AppID sets the appId argument
func (b *IsAppInstalledBuilder) AppID(v string) *IsAppInstalledBuilder {
	b.SetArg("appId", v, "ID!")
	return b
}

// Execute runs the query and returns the result
func (b *IsAppInstalledBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result bool `json:"isAppInstalled"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Data.Result, nil
}
