// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemGroupSourcesSummaryBuilder builds a query for itemGroupSourcesSummary
type ItemGroupSourcesSummaryBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *ItemGroupSourcesSummaryBuilder) ID(v string) *ItemGroupSourcesSummaryBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemGroupSourcesSummaryBuilder) Select(selector func(*fields.ItemGroupSourceSummaryFields)) *ItemGroupSourcesSummaryBuilder {
	selector(fields.NewItemGroupSourceSummaryFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupSourcesSummaryBuilder) Execute(ctx context.Context) ([]api.ItemGroupSourceSummary, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []api.ItemGroupSourceSummary `json:"itemGroupSourcesSummary"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
