// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// IChatbotBuilder builds a query for iChatbot
type IChatbotBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *IChatbotBuilder) ID(v string) *IChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Input sets the input argument
func (b *IChatbotBuilder) Input(v *api.IChatbotGetInput) *IChatbotBuilder {
	b.SetArg("input", v, "IChatbotGetInput")
	return b
}

// Select configures which fields to return
func (b *IChatbotBuilder) Select(selector func(*fields.ChatbotFields)) *IChatbotBuilder {
	selector(fields.NewChatbotFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IChatbotBuilder) Execute(ctx context.Context) (api.Chatbot, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.Chatbot `json:"iChatbot"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.Chatbot{}, err
	}

	return response.Data.Result, nil
}
