// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemAiSearchBuilder builds a query for itemAiSearch
type ItemAiSearchBuilder struct {
	*api.BaseBuilder
}

// ItemGroupID sets the itemGroupID argument
func (b *ItemAiSearchBuilder) ItemGroupID(v string) *ItemAiSearchBuilder {
	b.SetArg("itemGroupID", v, "ID!")
	return b
}

// Search sets the search argument
func (b *ItemAiSearchBuilder) Search(v string) *ItemAiSearchBuilder {
	b.SetArg("search", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemAiSearchBuilder) Select(selector func(*fields.ItemFields)) *ItemAiSearchBuilder {
	selector(fields.NewItemFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemAiSearchBuilder) Execute(ctx context.Context) ([]api.Item, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []api.Item `json:"itemAiSearch"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
