// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// AiModels2Builder builds a query for aiModels2
type AiModels2Builder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *AiModels2Builder) After(v *string) *AiModels2Builder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *AiModels2Builder) First(v *int) *AiModels2Builder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *AiModels2Builder) Before(v *string) *AiModels2Builder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *AiModels2Builder) Last(v *int) *AiModels2Builder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *AiModels2Builder) OrderBy(v []api.AiModelOrder) *AiModels2Builder {
	b.SetArg("orderBy", v, "[AiModelOrder!]")
	return b
}

// Where sets the where argument
func (b *AiModels2Builder) Where(v *api.AiModelWhereInput) *AiModels2Builder {
	b.SetArg("where", v, "AiModelWhereInput")
	return b
}

// Select configures which fields to return
func (b *AiModels2Builder) Select(selector func(*fields.AiModelConnectionFields)) *AiModels2Builder {
	selector(fields.NewAiModelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AiModels2Builder) Execute(ctx context.Context) (api.AiModelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.AiModelConnection `json:"aiModels2"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.AiModelConnection{}, err
	}

	return response.Data.Result, nil
}
