// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
)

// ICanUserAccessWorkspaceBuilder builds a query for iCanUserAccessWorkspace
type ICanUserAccessWorkspaceBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *ICanUserAccessWorkspaceBuilder) ID(v string) *ICanUserAccessWorkspaceBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// SbyteUserID sets the sbyteUserID argument
func (b *ICanUserAccessWorkspaceBuilder) SbyteUserID(v string) *ICanUserAccessWorkspaceBuilder {
	b.SetArg("sbyteUserID", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *ICanUserAccessWorkspaceBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result bool `json:"iCanUserAccessWorkspace"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Data.Result, nil
}
