// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// AvailableAppsBuilder builds a query for availableApps
type AvailableAppsBuilder struct {
	*api.BaseBuilder
}

// Select configures which fields to return
func (b *AvailableAppsBuilder) Select(selector func(*fields.AppStoreAppFields)) *AvailableAppsBuilder {
	selector(fields.NewAppStoreAppFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AvailableAppsBuilder) Execute(ctx context.Context) ([]api.AppStoreApp, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []api.AppStoreApp `json:"availableApps"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
