// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// BillingFeaturesBuilder builds a query for billingFeatures
type BillingFeaturesBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *BillingFeaturesBuilder) After(v *string) *BillingFeaturesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingFeaturesBuilder) First(v *int) *BillingFeaturesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingFeaturesBuilder) Before(v *string) *BillingFeaturesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingFeaturesBuilder) Last(v *int) *BillingFeaturesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingFeaturesBuilder) Select(selector func(*fields.BillingFeatureConnectionFields)) *BillingFeaturesBuilder {
	selector(fields.NewBillingFeatureConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingFeaturesBuilder) Execute(ctx context.Context) (api.BillingFeatureConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.BillingFeatureConnection `json:"billingFeatures"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.BillingFeatureConnection{}, err
	}

	return response.Data.Result, nil
}
