// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// AiModelsBuilder builds a query for aiModels
type AiModelsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *AiModelsBuilder) After(v *string) *AiModelsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *AiModelsBuilder) First(v *int) *AiModelsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *AiModelsBuilder) Before(v *string) *AiModelsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *AiModelsBuilder) Last(v *int) *AiModelsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *AiModelsBuilder) OrderBy(v []api.AiModelOrder) *AiModelsBuilder {
	b.SetArg("orderBy", v, "[AiModelOrder!]")
	return b
}

// Where sets the where argument
func (b *AiModelsBuilder) Where(v *api.AiModelWhereInput) *AiModelsBuilder {
	b.SetArg("where", v, "AiModelWhereInput")
	return b
}

// Select configures which fields to return
func (b *AiModelsBuilder) Select(selector func(*fields.AiModelConnectionFields)) *AiModelsBuilder {
	selector(fields.NewAiModelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AiModelsBuilder) Execute(ctx context.Context) (api.AiModelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.AiModelConnection `json:"aiModels"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.AiModelConnection{}, err
	}

	return response.Data.Result, nil
}
