// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChatbotUsersBuilder builds a query for chatbotUsers
type ChatbotUsersBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ChatbotUsersBuilder) After(v *string) *ChatbotUsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChatbotUsersBuilder) First(v *int) *ChatbotUsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChatbotUsersBuilder) Before(v *string) *ChatbotUsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChatbotUsersBuilder) Last(v *int) *ChatbotUsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChatbotUsersBuilder) OrderBy(v []api.ChatbotUserOrder) *ChatbotUsersBuilder {
	b.SetArg("orderBy", v, "[ChatbotUserOrder!]")
	return b
}

// Where sets the where argument
func (b *ChatbotUsersBuilder) Where(v *api.ChatbotUserWhereInput) *ChatbotUsersBuilder {
	b.SetArg("where", v, "ChatbotUserWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChatbotUsersBuilder) Select(selector func(*fields.ChatbotUserConnectionFields)) *ChatbotUsersBuilder {
	selector(fields.NewChatbotUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotUsersBuilder) Execute(ctx context.Context) (api.ChatbotUserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ChatbotUserConnection `json:"chatbotUsers"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ChatbotUserConnection{}, err
	}

	return response.Data.Result, nil
}
