// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// CworkspaceSubsBuilder builds a query for cworkspaceSubs
type CworkspaceSubsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *CworkspaceSubsBuilder) After(v *string) *CworkspaceSubsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CworkspaceSubsBuilder) First(v *int) *CworkspaceSubsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CworkspaceSubsBuilder) Before(v *string) *CworkspaceSubsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CworkspaceSubsBuilder) Last(v *int) *CworkspaceSubsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Where sets the where argument
func (b *CworkspaceSubsBuilder) Where(v *api.CWorkspaceSubWhereInput) *CworkspaceSubsBuilder {
	b.SetArg("where", v, "CWorkspaceSubWhereInput")
	return b
}

// Select configures which fields to return
func (b *CworkspaceSubsBuilder) Select(selector func(*fields.CWorkspaceSubConnectionFields)) *CworkspaceSubsBuilder {
	selector(fields.NewCWorkspaceSubConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CworkspaceSubsBuilder) Execute(ctx context.Context) (api.CWorkspaceSubConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.CWorkspaceSubConnection `json:"cworkspaceSubs"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.CWorkspaceSubConnection{}, err
	}

	return response.Data.Result, nil
}
