// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// WorkspaceSubscriptionsBuilder builds a query for workspaceSubscriptions
type WorkspaceSubscriptionsBuilder struct {
	*api.BaseBuilder
}

// Select configures which fields to return
func (b *WorkspaceSubscriptionsBuilder) Select(selector func(*fields.CWorkspaceSubFields)) *WorkspaceSubscriptionsBuilder {
	selector(fields.NewCWorkspaceSubFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *WorkspaceSubscriptionsBuilder) Execute(ctx context.Context) ([]*api.CWorkspaceSub, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []*api.CWorkspaceSub `json:"workspaceSubscriptions"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
