// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// NodeBuilder builds a query for node
type NodeBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *NodeBuilder) ID(v string) *NodeBuilder {
	b.SetArg("id", v, "ID!")
	return b
}

// Select configures which fields to return
func (b *NodeBuilder) Select(selector func(*fields.NodeFields)) *NodeBuilder {
	selector(fields.NewNodeFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *NodeBuilder) Execute(ctx context.Context) (*api.Node, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result *api.Node `json:"node"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
