// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// UsersBuilder builds a query for users
type UsersBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *UsersBuilder) After(v *string) *UsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *UsersBuilder) First(v *int) *UsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *UsersBuilder) Before(v *string) *UsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *UsersBuilder) Last(v *int) *UsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *UsersBuilder) OrderBy(v []api.UserOrder) *UsersBuilder {
	b.SetArg("orderBy", v, "[UserOrder!]")
	return b
}

// Where sets the where argument
func (b *UsersBuilder) Where(v *api.UserWhereInput) *UsersBuilder {
	b.SetArg("where", v, "UserWhereInput")
	return b
}

// Select configures which fields to return
func (b *UsersBuilder) Select(selector func(*fields.UserConnectionFields)) *UsersBuilder {
	selector(fields.NewUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *UsersBuilder) Execute(ctx context.Context) (api.UserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.UserConnection `json:"users"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.UserConnection{}, err
	}

	return response.Data.Result, nil
}
