// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// LeadsBuilder builds a query for leads
type LeadsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *LeadsBuilder) After(v *string) *LeadsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *LeadsBuilder) First(v *int) *LeadsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *LeadsBuilder) Before(v *string) *LeadsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *LeadsBuilder) Last(v *int) *LeadsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *LeadsBuilder) OrderBy(v []api.LeadOrder) *LeadsBuilder {
	b.SetArg("orderBy", v, "[LeadOrder!]")
	return b
}

// Where sets the where argument
func (b *LeadsBuilder) Where(v *api.LeadWhereInput) *LeadsBuilder {
	b.SetArg("where", v, "LeadWhereInput")
	return b
}

// Select configures which fields to return
func (b *LeadsBuilder) Select(selector func(*fields.LeadConnectionFields)) *LeadsBuilder {
	selector(fields.NewLeadConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *LeadsBuilder) Execute(ctx context.Context) (api.LeadConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.LeadConnection `json:"leads"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.LeadConnection{}, err
	}

	return response.Data.Result, nil
}
