// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// MessagesBuilder builds a query for messages
type MessagesBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *MessagesBuilder) After(v *string) *MessagesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *MessagesBuilder) First(v *int) *MessagesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *MessagesBuilder) Before(v *string) *MessagesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *MessagesBuilder) Last(v *int) *MessagesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *MessagesBuilder) OrderBy(v []api.MessageOrder) *MessagesBuilder {
	b.SetArg("orderBy", v, "[MessageOrder!]")
	return b
}

// Where sets the where argument
func (b *MessagesBuilder) Where(v *api.MessageWhereInput) *MessagesBuilder {
	b.SetArg("where", v, "MessageWhereInput")
	return b
}

// Select configures which fields to return
func (b *MessagesBuilder) Select(selector func(*fields.MessageConnectionFields)) *MessagesBuilder {
	selector(fields.NewMessageConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *MessagesBuilder) Execute(ctx context.Context) (api.MessageConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.MessageConnection `json:"messages"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.MessageConnection{}, err
	}

	return response.Data.Result, nil
}
