// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemsBuilder builds a query for items
type ItemsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ItemsBuilder) After(v *string) *ItemsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemsBuilder) First(v *int) *ItemsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemsBuilder) Before(v *string) *ItemsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemsBuilder) Last(v *int) *ItemsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemsBuilder) OrderBy(v []api.ItemOrder) *ItemsBuilder {
	b.SetArg("orderBy", v, "[ItemOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemsBuilder) Where(v *api.ItemWhereInput) *ItemsBuilder {
	b.SetArg("where", v, "ItemWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemsBuilder) Select(selector func(*fields.ItemConnectionFields)) *ItemsBuilder {
	selector(fields.NewItemConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemsBuilder) Execute(ctx context.Context) (api.ItemConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ItemConnection `json:"items"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ItemConnection{}, err
	}

	return response.Data.Result, nil
}
