// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
)

// ICanUserAccessChannelBuilder builds a query for iCanUserAccessChannel
type ICanUserAccessChannelBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *ICanUserAccessChannelBuilder) ID(v string) *ICanUserAccessChannelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// AiUserID sets the aiUserID argument
func (b *ICanUserAccessChannelBuilder) AiUserID(v string) *ICanUserAccessChannelBuilder {
	b.SetArg("aiUserID", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *ICanUserAccessChannelBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result bool `json:"iCanUserAccessChannel"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Data.Result, nil
}
