// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// CredentialsBuilder builds a query for credentials
type CredentialsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *CredentialsBuilder) After(v *string) *CredentialsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CredentialsBuilder) First(v *int) *CredentialsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CredentialsBuilder) Before(v *string) *CredentialsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CredentialsBuilder) Last(v *int) *CredentialsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *CredentialsBuilder) OrderBy(v []api.CredentialOrder) *CredentialsBuilder {
	b.SetArg("orderBy", v, "[CredentialOrder!]")
	return b
}

// Where sets the where argument
func (b *CredentialsBuilder) Where(v *api.CredentialWhereInput) *CredentialsBuilder {
	b.SetArg("where", v, "CredentialWhereInput")
	return b
}

// Select configures which fields to return
func (b *CredentialsBuilder) Select(selector func(*fields.CredentialConnectionFields)) *CredentialsBuilder {
	selector(fields.NewCredentialConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CredentialsBuilder) Execute(ctx context.Context) (api.CredentialConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.CredentialConnection `json:"credentials"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.CredentialConnection{}, err
	}

	return response.Data.Result, nil
}
