// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChatbotToolsBuilder builds a query for chatbotTools
type ChatbotToolsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ChatbotToolsBuilder) After(v *string) *ChatbotToolsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChatbotToolsBuilder) First(v *int) *ChatbotToolsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChatbotToolsBuilder) Before(v *string) *ChatbotToolsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChatbotToolsBuilder) Last(v *int) *ChatbotToolsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChatbotToolsBuilder) OrderBy(v []api.ChatbotToolOrder) *ChatbotToolsBuilder {
	b.SetArg("orderBy", v, "[ChatbotToolOrder!]")
	return b
}

// Where sets the where argument
func (b *ChatbotToolsBuilder) Where(v *api.ChatbotToolWhereInput) *ChatbotToolsBuilder {
	b.SetArg("where", v, "ChatbotToolWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChatbotToolsBuilder) Select(selector func(*fields.ChatbotToolConnectionFields)) *ChatbotToolsBuilder {
	selector(fields.NewChatbotToolConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotToolsBuilder) Execute(ctx context.Context) (api.ChatbotToolConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ChatbotToolConnection `json:"chatbotTools"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ChatbotToolConnection{}, err
	}

	return response.Data.Result, nil
}
