// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChannelsBuilder builds a query for channels
type ChannelsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ChannelsBuilder) After(v *string) *ChannelsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChannelsBuilder) First(v *int) *ChannelsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChannelsBuilder) Before(v *string) *ChannelsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChannelsBuilder) Last(v *int) *ChannelsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChannelsBuilder) OrderBy(v []api.ChannelOrder) *ChannelsBuilder {
	b.SetArg("orderBy", v, "[ChannelOrder!]")
	return b
}

// Where sets the where argument
func (b *ChannelsBuilder) Where(v *api.ChannelWhereInput) *ChannelsBuilder {
	b.SetArg("where", v, "ChannelWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChannelsBuilder) Select(selector func(*fields.ChannelConnectionFields)) *ChannelsBuilder {
	selector(fields.NewChannelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChannelsBuilder) Execute(ctx context.Context) (api.ChannelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ChannelConnection `json:"channels"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ChannelConnection{}, err
	}

	return response.Data.Result, nil
}
