// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// FuncToolLogsBuilder builds a query for funcToolLogs
type FuncToolLogsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *FuncToolLogsBuilder) After(v *string) *FuncToolLogsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *FuncToolLogsBuilder) First(v *int) *FuncToolLogsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *FuncToolLogsBuilder) Before(v *string) *FuncToolLogsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *FuncToolLogsBuilder) Last(v *int) *FuncToolLogsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *FuncToolLogsBuilder) OrderBy(v []api.FuncToolLogOrder) *FuncToolLogsBuilder {
	b.SetArg("orderBy", v, "[FuncToolLogOrder!]")
	return b
}

// Where sets the where argument
func (b *FuncToolLogsBuilder) Where(v *api.FuncToolLogWhereInput) *FuncToolLogsBuilder {
	b.SetArg("where", v, "FuncToolLogWhereInput")
	return b
}

// Select configures which fields to return
func (b *FuncToolLogsBuilder) Select(selector func(*fields.FuncToolLogConnectionFields)) *FuncToolLogsBuilder {
	selector(fields.NewFuncToolLogConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *FuncToolLogsBuilder) Execute(ctx context.Context) (api.FuncToolLogConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.FuncToolLogConnection `json:"funcToolLogs"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.FuncToolLogConnection{}, err
	}

	return response.Data.Result, nil
}
