// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemGroupSourcesBuilder builds a query for itemGroupSources
type ItemGroupSourcesBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ItemGroupSourcesBuilder) After(v *string) *ItemGroupSourcesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemGroupSourcesBuilder) First(v *int) *ItemGroupSourcesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemGroupSourcesBuilder) Before(v *string) *ItemGroupSourcesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemGroupSourcesBuilder) Last(v *int) *ItemGroupSourcesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemGroupSourcesBuilder) OrderBy(v []api.ItemGroupSourceOrder) *ItemGroupSourcesBuilder {
	b.SetArg("orderBy", v, "[ItemGroupSourceOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemGroupSourcesBuilder) Where(v *api.ItemGroupSourceWhereInput) *ItemGroupSourcesBuilder {
	b.SetArg("where", v, "ItemGroupSourceWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemGroupSourcesBuilder) Select(selector func(*fields.ItemGroupSourceConnectionFields)) *ItemGroupSourcesBuilder {
	selector(fields.NewItemGroupSourceConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupSourcesBuilder) Execute(ctx context.Context) (api.ItemGroupSourceConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ItemGroupSourceConnection `json:"itemGroupSources"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ItemGroupSourceConnection{}, err
	}

	return response.Data.Result, nil
}
