// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ItemGroupBuilder builds a query for itemGroup
type ItemGroupBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *ItemGroupBuilder) ID(v string) *ItemGroupBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemGroupBuilder) Select(selector func(*fields.ItemGroupFields)) *ItemGroupBuilder {
	selector(fields.NewItemGroupFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupBuilder) Execute(ctx context.Context) (api.ItemGroup, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ItemGroup `json:"itemGroup"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ItemGroup{}, err
	}

	return response.Data.Result, nil
}
