// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// BillingPlansBuilder builds a query for billingPlans
type BillingPlansBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *BillingPlansBuilder) After(v *string) *BillingPlansBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingPlansBuilder) First(v *int) *BillingPlansBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingPlansBuilder) Before(v *string) *BillingPlansBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingPlansBuilder) Last(v *int) *BillingPlansBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingPlansBuilder) Select(selector func(*fields.BillingPlanConnectionFields)) *BillingPlansBuilder {
	selector(fields.NewBillingPlanConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingPlansBuilder) Execute(ctx context.Context) (api.BillingPlanConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.BillingPlanConnection `json:"billingPlans"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.BillingPlanConnection{}, err
	}

	return response.Data.Result, nil
}
