// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChatbotBuilder builds a query for chatbot
type ChatbotBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *ChatbotBuilder) ID(v string) *ChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ChatbotBuilder) Select(selector func(*fields.ChatbotFields)) *ChatbotBuilder {
	selector(fields.NewChatbotFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotBuilder) Execute(ctx context.Context) (*api.Chatbot, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result *api.Chatbot `json:"chatbot"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
