// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// FoldersBuilder builds a query for folders
type FoldersBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *FoldersBuilder) After(v *string) *FoldersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *FoldersBuilder) First(v *int) *FoldersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *FoldersBuilder) Before(v *string) *FoldersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *FoldersBuilder) Last(v *int) *FoldersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *FoldersBuilder) OrderBy(v []api.FolderOrder) *FoldersBuilder {
	b.SetArg("orderBy", v, "[FolderOrder!]")
	return b
}

// Where sets the where argument
func (b *FoldersBuilder) Where(v *api.FolderWhereInput) *FoldersBuilder {
	b.SetArg("where", v, "FolderWhereInput")
	return b
}

// Select configures which fields to return
func (b *FoldersBuilder) Select(selector func(*fields.FolderConnectionFields)) *FoldersBuilder {
	selector(fields.NewFolderConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *FoldersBuilder) Execute(ctx context.Context) (api.FolderConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.FolderConnection `json:"folders"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.FolderConnection{}, err
	}

	return response.Data.Result, nil
}
