// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// IChannelBuilder builds a query for iChannel
type IChannelBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *IChannelBuilder) ID(v string) *IChannelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// UserIds sets the userIds argument
func (b *IChannelBuilder) UserIds(v []string) *IChannelBuilder {
	b.SetArg("userIds", v, "[String!]")
	return b
}

// Select configures which fields to return
func (b *IChannelBuilder) Select(selector func(*fields.ChannelFields)) *IChannelBuilder {
	selector(fields.NewChannelFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IChannelBuilder) Execute(ctx context.Context) (api.Channel, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.Channel `json:"iChannel"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.Channel{}, err
	}

	return response.Data.Result, nil
}
