// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// IAiModelBuilder builds a query for iAiModel
type IAiModelBuilder struct {
	*api.BaseBuilder
}

// ID sets the id argument
func (b *IAiModelBuilder) ID(v string) *IAiModelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *IAiModelBuilder) Select(selector func(*fields.AiModelFields)) *IAiModelBuilder {
	selector(fields.NewAiModelFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IAiModelBuilder) Execute(ctx context.Context) (api.AiModel, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.AiModel `json:"iAiModel"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.AiModel{}, err
	}

	return response.Data.Result, nil
}
