// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// CworkspaceFeatureLimitsBuilder builds a query for cworkspaceFeatureLimits
type CworkspaceFeatureLimitsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *CworkspaceFeatureLimitsBuilder) After(v *string) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CworkspaceFeatureLimitsBuilder) First(v *int) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CworkspaceFeatureLimitsBuilder) Before(v *string) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CworkspaceFeatureLimitsBuilder) Last(v *int) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *CworkspaceFeatureLimitsBuilder) Select(selector func(*fields.CWorkspaceFeatureLimitConnectionFields)) *CworkspaceFeatureLimitsBuilder {
	selector(fields.NewCWorkspaceFeatureLimitConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CworkspaceFeatureLimitsBuilder) Execute(ctx context.Context) (api.CWorkspaceFeatureLimitConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.CWorkspaceFeatureLimitConnection `json:"cworkspaceFeatureLimits"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.CWorkspaceFeatureLimitConnection{}, err
	}

	return response.Data.Result, nil
}
