// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
)

// PingBuilder builds a query for ping
type PingBuilder struct {
	*api.BaseBuilder
}

// Execute runs the query and returns the result
func (b *PingBuilder) Execute(ctx context.Context) (string, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result string `json:"ping"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return "", err
	}

	return response.Data.Result, nil
}
