// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// GuestsBuilder builds a query for guests
type GuestsBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *GuestsBuilder) After(v *string) *GuestsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *GuestsBuilder) First(v *int) *GuestsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *GuestsBuilder) Before(v *string) *GuestsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *GuestsBuilder) Last(v *int) *GuestsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *GuestsBuilder) OrderBy(v []api.GuestOrder) *GuestsBuilder {
	b.SetArg("orderBy", v, "[GuestOrder!]")
	return b
}

// Where sets the where argument
func (b *GuestsBuilder) Where(v *api.GuestWhereInput) *GuestsBuilder {
	b.SetArg("where", v, "GuestWhereInput")
	return b
}

// Select configures which fields to return
func (b *GuestsBuilder) Select(selector func(*fields.GuestConnectionFields)) *GuestsBuilder {
	selector(fields.NewGuestConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *GuestsBuilder) Execute(ctx context.Context) (api.GuestConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.GuestConnection `json:"guests"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.GuestConnection{}, err
	}

	return response.Data.Result, nil
}
