// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChatbotFoldersBuilder builds a query for chatbotFolders
type ChatbotFoldersBuilder struct {
	*api.BaseBuilder
}

// ChatbotID sets the chatbotId argument
func (b *ChatbotFoldersBuilder) ChatbotID(v string) *ChatbotFoldersBuilder {
	b.SetArg("chatbotId", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ChatbotFoldersBuilder) Select(selector func(*fields.FolderFields)) *ChatbotFoldersBuilder {
	selector(fields.NewFolderFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotFoldersBuilder) Execute(ctx context.Context) ([]api.Folder, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []api.Folder `json:"chatbotFolders"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
