// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// ChannelUsersBuilder builds a query for channelUsers
type ChannelUsersBuilder struct {
	*api.BaseBuilder
}

// After sets the after argument
func (b *ChannelUsersBuilder) After(v *string) *ChannelUsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChannelUsersBuilder) First(v *int) *ChannelUsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChannelUsersBuilder) Before(v *string) *ChannelUsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChannelUsersBuilder) Last(v *int) *ChannelUsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChannelUsersBuilder) OrderBy(v []api.ChannelUserOrder) *ChannelUsersBuilder {
	b.SetArg("orderBy", v, "[ChannelUserOrder!]")
	return b
}

// Where sets the where argument
func (b *ChannelUsersBuilder) Where(v *api.ChannelUserWhereInput) *ChannelUsersBuilder {
	b.SetArg("where", v, "ChannelUserWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChannelUsersBuilder) Select(selector func(*fields.ChannelUserConnectionFields)) *ChannelUsersBuilder {
	selector(fields.NewChannelUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChannelUsersBuilder) Execute(ctx context.Context) (api.ChannelUserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result api.ChannelUserConnection `json:"channelUsers"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return api.ChannelUserConnection{}, err
	}

	return response.Data.Result, nil
}
