// Code generated by gqlsdk. DO NOT EDIT.

package queries

import (
	"context"

	"testsdk/api"
	"testsdk/api/fields"
)

// InstalledAppsBuilder builds a query for installedApps
type InstalledAppsBuilder struct {
	*api.BaseBuilder
}

// Select configures which fields to return
func (b *InstalledAppsBuilder) Select(selector func(*fields.WorkspaceAppInstallationFields)) *InstalledAppsBuilder {
	selector(fields.NewWorkspaceAppInstallationFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *InstalledAppsBuilder) Execute(ctx context.Context) ([]api.WorkspaceAppInstallation, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Data struct {
			Result []api.WorkspaceAppInstallation `json:"installedApps"`
		} `json:"data"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Data.Result, nil
}
