// Code generated by gqlsdk. DO NOT EDIT.

package queries

import "testsdk/api"

// QueryRoot is the entry point for queries
type QueryRoot struct {
	client *api.Client
}

// NewQueryRoot creates a new QueryRoot
func NewQueryRoot(client *api.Client) *QueryRoot {
	return &QueryRoot{client: client}
}

// Node creates a new NodeBuilder
func (q *QueryRoot) Node() *NodeBuilder {
	return &NodeBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "node", "Node"),
	}
}

// Nodes creates a new NodesBuilder
func (q *QueryRoot) Nodes() *NodesBuilder {
	return &NodesBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "nodes", "Nodes"),
	}
}

// AiModels creates a new AiModelsBuilder
func (q *QueryRoot) AiModels() *AiModelsBuilder {
	return &AiModelsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "aiModels", "AiModels"),
	}
}

// AiModels2 creates a new AiModels2Builder
func (q *QueryRoot) AiModels2() *AiModels2Builder {
	return &AiModels2Builder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "aiModels2", "AiModels2"),
	}
}

// BillingFeatures creates a new BillingFeaturesBuilder
func (q *QueryRoot) BillingFeatures() *BillingFeaturesBuilder {
	return &BillingFeaturesBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "billingFeatures", "BillingFeatures"),
	}
}

// BillingPlans creates a new BillingPlansBuilder
func (q *QueryRoot) BillingPlans() *BillingPlansBuilder {
	return &BillingPlansBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "billingPlans", "BillingPlans"),
	}
}

// BillingPlanWspaces creates a new BillingPlanWspacesBuilder
func (q *QueryRoot) BillingPlanWspaces() *BillingPlanWspacesBuilder {
	return &BillingPlanWspacesBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "billingPlanWspaces", "BillingPlanWspaces"),
	}
}

// CworkspaceFeatureLimits creates a new CworkspaceFeatureLimitsBuilder
func (q *QueryRoot) CworkspaceFeatureLimits() *CworkspaceFeatureLimitsBuilder {
	return &CworkspaceFeatureLimitsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "cworkspaceFeatureLimits", "CworkspaceFeatureLimits"),
	}
}

// CworkspaceSubs creates a new CworkspaceSubsBuilder
func (q *QueryRoot) CworkspaceSubs() *CworkspaceSubsBuilder {
	return &CworkspaceSubsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "cworkspaceSubs", "CworkspaceSubs"),
	}
}

// Channels creates a new ChannelsBuilder
func (q *QueryRoot) Channels() *ChannelsBuilder {
	return &ChannelsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "channels", "Channels"),
	}
}

// ChannelUsers creates a new ChannelUsersBuilder
func (q *QueryRoot) ChannelUsers() *ChannelUsersBuilder {
	return &ChannelUsersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "channelUsers", "ChannelUsers"),
	}
}

// Chatbots creates a new ChatbotsBuilder
func (q *QueryRoot) Chatbots() *ChatbotsBuilder {
	return &ChatbotsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "chatbots", "Chatbots"),
	}
}

// ChatbotTools creates a new ChatbotToolsBuilder
func (q *QueryRoot) ChatbotTools() *ChatbotToolsBuilder {
	return &ChatbotToolsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "chatbotTools", "ChatbotTools"),
	}
}

// ChatbotUsers creates a new ChatbotUsersBuilder
func (q *QueryRoot) ChatbotUsers() *ChatbotUsersBuilder {
	return &ChatbotUsersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "chatbotUsers", "ChatbotUsers"),
	}
}

// Credentials creates a new CredentialsBuilder
func (q *QueryRoot) Credentials() *CredentialsBuilder {
	return &CredentialsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "credentials", "Credentials"),
	}
}

// Folders creates a new FoldersBuilder
func (q *QueryRoot) Folders() *FoldersBuilder {
	return &FoldersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "folders", "Folders"),
	}
}

// FuncTools creates a new FuncToolsBuilder
func (q *QueryRoot) FuncTools() *FuncToolsBuilder {
	return &FuncToolsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "funcTools", "FuncTools"),
	}
}

// FuncToolLogs creates a new FuncToolLogsBuilder
func (q *QueryRoot) FuncToolLogs() *FuncToolLogsBuilder {
	return &FuncToolLogsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "funcToolLogs", "FuncToolLogs"),
	}
}

// Guests creates a new GuestsBuilder
func (q *QueryRoot) Guests() *GuestsBuilder {
	return &GuestsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "guests", "Guests"),
	}
}

// Items creates a new ItemsBuilder
func (q *QueryRoot) Items() *ItemsBuilder {
	return &ItemsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "items", "Items"),
	}
}

// ItemGroups creates a new ItemGroupsBuilder
func (q *QueryRoot) ItemGroups() *ItemGroupsBuilder {
	return &ItemGroupsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "itemGroups", "ItemGroups"),
	}
}

// ItemGroupSources creates a new ItemGroupSourcesBuilder
func (q *QueryRoot) ItemGroupSources() *ItemGroupSourcesBuilder {
	return &ItemGroupSourcesBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "itemGroupSources", "ItemGroupSources"),
	}
}

// Leads creates a new LeadsBuilder
func (q *QueryRoot) Leads() *LeadsBuilder {
	return &LeadsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "leads", "Leads"),
	}
}

// Messages creates a new MessagesBuilder
func (q *QueryRoot) Messages() *MessagesBuilder {
	return &MessagesBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "messages", "Messages"),
	}
}

// Users creates a new UsersBuilder
func (q *QueryRoot) Users() *UsersBuilder {
	return &UsersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "users", "Users"),
	}
}

// AvailableApps creates a new AvailableAppsBuilder
func (q *QueryRoot) AvailableApps() *AvailableAppsBuilder {
	return &AvailableAppsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "availableApps", "AvailableApps"),
	}
}

// InstalledApps creates a new InstalledAppsBuilder
func (q *QueryRoot) InstalledApps() *InstalledAppsBuilder {
	return &InstalledAppsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "installedApps", "InstalledApps"),
	}
}

// IsAppInstalled creates a new IsAppInstalledBuilder
func (q *QueryRoot) IsAppInstalled() *IsAppInstalledBuilder {
	return &IsAppInstalledBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "isAppInstalled", "IsAppInstalled"),
	}
}

// WorkspaceSubscriptions creates a new WorkspaceSubscriptionsBuilder
func (q *QueryRoot) WorkspaceSubscriptions() *WorkspaceSubscriptionsBuilder {
	return &WorkspaceSubscriptionsBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "workspaceSubscriptions", "WorkspaceSubscriptions"),
	}
}

// BillingCustomPlans creates a new BillingCustomPlansBuilder
func (q *QueryRoot) BillingCustomPlans() *BillingCustomPlansBuilder {
	return &BillingCustomPlansBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "billingCustomPlans", "BillingCustomPlans"),
	}
}

// Chatbot creates a new ChatbotBuilder
func (q *QueryRoot) Chatbot() *ChatbotBuilder {
	return &ChatbotBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "chatbot", "Chatbot"),
	}
}

// MyChatbotUsers creates a new MyChatbotUsersBuilder
func (q *QueryRoot) MyChatbotUsers() *MyChatbotUsersBuilder {
	return &MyChatbotUsersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "myChatbotUsers", "MyChatbotUsers"),
	}
}

// ChatbotFolders creates a new ChatbotFoldersBuilder
func (q *QueryRoot) ChatbotFolders() *ChatbotFoldersBuilder {
	return &ChatbotFoldersBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "chatbotFolders", "ChatbotFolders"),
	}
}

// IChatbot creates a new IChatbotBuilder
func (q *QueryRoot) IChatbot() *IChatbotBuilder {
	return &IChatbotBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iChatbot", "IChatbot"),
	}
}

// IChannel creates a new IChannelBuilder
func (q *QueryRoot) IChannel() *IChannelBuilder {
	return &IChannelBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iChannel", "IChannel"),
	}
}

// ICanUserAccessChatbot creates a new ICanUserAccessChatbotBuilder
func (q *QueryRoot) ICanUserAccessChatbot() *ICanUserAccessChatbotBuilder {
	return &ICanUserAccessChatbotBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iCanUserAccessChatbot", "ICanUserAccessChatbot"),
	}
}

// ICanUserAccessChannel creates a new ICanUserAccessChannelBuilder
func (q *QueryRoot) ICanUserAccessChannel() *ICanUserAccessChannelBuilder {
	return &ICanUserAccessChannelBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iCanUserAccessChannel", "ICanUserAccessChannel"),
	}
}

// ICanUserAccessWorkspace creates a new ICanUserAccessWorkspaceBuilder
func (q *QueryRoot) ICanUserAccessWorkspace() *ICanUserAccessWorkspaceBuilder {
	return &ICanUserAccessWorkspaceBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iCanUserAccessWorkspace", "ICanUserAccessWorkspace"),
	}
}

// IAiModel creates a new IAiModelBuilder
func (q *QueryRoot) IAiModel() *IAiModelBuilder {
	return &IAiModelBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "iAiModel", "IAiModel"),
	}
}

// ItemAiSearch creates a new ItemAiSearchBuilder
func (q *QueryRoot) ItemAiSearch() *ItemAiSearchBuilder {
	return &ItemAiSearchBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "itemAiSearch", "ItemAiSearch"),
	}
}

// ItemGroup creates a new ItemGroupBuilder
func (q *QueryRoot) ItemGroup() *ItemGroupBuilder {
	return &ItemGroupBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "itemGroup", "ItemGroup"),
	}
}

// ItemGroupSourcesSummary creates a new ItemGroupSourcesSummaryBuilder
func (q *QueryRoot) ItemGroupSourcesSummary() *ItemGroupSourcesSummaryBuilder {
	return &ItemGroupSourcesSummaryBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "itemGroupSourcesSummary", "ItemGroupSourcesSummary"),
	}
}

// WorkspaceDetail creates a new WorkspaceDetailBuilder
func (q *QueryRoot) WorkspaceDetail() *WorkspaceDetailBuilder {
	return &WorkspaceDetailBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "workspaceDetail", "WorkspaceDetail"),
	}
}

// Ping creates a new PingBuilder
func (q *QueryRoot) Ping() *PingBuilder {
	return &PingBuilder{
		BaseBuilder: api.NewBaseBuilder(q.client, "query", "ping", "Ping"),
	}
}
