// Code generated by gqlsdk. DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// Custom scalar type aliases
type (
	// Define a Relay Cursor type:
	// https://relay.dev/graphql/connections.htm#sec-Cursor
	Cursor = string

	// ItemEmbeddingStatus is a custom GraphQL scalar
	ItemEmbeddingStatus = string

	// ItemGroupSourceTrainingStatus is a custom GraphQL scalar
	ItemGroupSourceTrainingStatus = string

	// ItemGroupSourceType is a custom GraphQL scalar
	ItemGroupSourceType = string

	// JSON is a custom GraphQL scalar
	JSON = json.RawMessage

	// JsonSlice is a custom GraphQL scalar
	JsonSlice = string

	// Map is a custom GraphQL scalar
	Map = map[string]interface{}

	// Password is a custom GraphQL scalar
	Password = string

	// Time is a custom GraphQL scalar
	Time = time.Time

	// Uint is a custom GraphQL scalar
	Uint = string

	// Uint64 is a custom GraphQL scalar
	Uint64 = string

	// UserType is a custom GraphQL scalar
	UserType = string
)
