// Code generated by gqlsdk. DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// AiModel represents the GraphQL type AiModel
type AiModel struct {
	ID              string      `json:"id"`
	CreatedAt       *time.Time  `json:"createdAt,omitempty"`
	UpdatedAt       *time.Time  `json:"updatedAt,omitempty"`
	Name            *string     `json:"name,omitempty"`
	ProviderName    string      `json:"providerName"`
	ModelID         string      `json:"modelID"`
	BaseURL         *string     `json:"baseURL,omitempty"`
	APIKey          *string     `json:"apiKey,omitempty"`
	OrgID           *string     `json:"orgID,omitempty"`
	Descr           *string     `json:"descr,omitempty"`
	Status          *bool       `json:"status,omitempty"`
	WorkspaceID     *string     `json:"workspaceID,omitempty"`
	HasChat         *bool       `json:"hasChat,omitempty"`
	HasEmbeddings   *bool       `json:"hasEmbeddings,omitempty"`
	IsWildai        *bool       `json:"isWildai,omitempty"`
	IntProviderName *string     `json:"intProviderName,omitempty"`
	IntBaseURL      *string     `json:"intBaseURL,omitempty"`
	IntApikey       *string     `json:"intApikey,omitempty"`
	IntOrgID        *string     `json:"intOrgID,omitempty"`
	IntModelID      *string     `json:"intModelID,omitempty"`
	MaxDims         *int        `json:"maxDims,omitempty"`
	MaxTokens       *int        `json:"maxTokens,omitempty"`
	Chatbots        []Chatbot   `json:"chatbots,omitempty"`
	FuncTools       []FuncTool  `json:"funcTools,omitempty"`
	ItemGroups      []ItemGroup `json:"itemGroups,omitempty"`
}

// AiModelConnection A connection to a list of items.
type AiModelConnection struct {
	Edges      []*AiModelEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo       `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int            `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// AiModelEdge An edge in a connection.
type AiModelEdge struct {
	Node   *AiModel `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string   `json:"cursor"`         // A cursor for use in pagination.
}

// AppSessionResponse represents the GraphQL type AppSessionResponse
type AppSessionResponse struct {
	SessionToken string    `json:"sessionToken"`
	LaunchURL    string    `json:"launchURL"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

// AppStoreApp represents the GraphQL type AppStoreApp
type AppStoreApp struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	IconURL     *string         `json:"iconURL,omitempty"`
	Partner     AppStorePartner `json:"partner"`
}

// AppStorePartner represents the GraphQL type AppStorePartner
type AppStorePartner struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	CompanyName *string `json:"companyName,omitempty"`
}

// BillingFeature represents the GraphQL type BillingFeature
type BillingFeature struct {
	ID                      string                   `json:"id"`
	CreatedAt               *time.Time               `json:"createdAt,omitempty"`
	UpdatedAt               *time.Time               `json:"updatedAt,omitempty"`
	Name                    string                   `json:"name"`
	GroupName               *string                  `json:"groupName,omitempty"`
	IsActive                bool                     `json:"isActive"`
	DefaultValue            *int                     `json:"defaultValue,omitempty"`
	UnitType                *string                  `json:"unitType,omitempty"`
	FeatureType             *string                  `json:"featureType,omitempty"`
	SortOrder               *int                     `json:"sortOrder,omitempty"`
	Description             *string                  `json:"description,omitempty"`
	BillingPlanFeatures     []BillingPlanFeature     `json:"billingPlanFeatures,omitempty"`
	CworkspaceFeatureLimits []CWorkspaceFeatureLimit `json:"cworkspaceFeatureLimits,omitempty"`
}

// BillingFeatureConnection A connection to a list of items.
type BillingFeatureConnection struct {
	Edges      []*BillingFeatureEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo              `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                   `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// BillingFeatureEdge An edge in a connection.
type BillingFeatureEdge struct {
	Node   *BillingFeature `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string          `json:"cursor"`         // A cursor for use in pagination.
}

// BillingPlan represents the GraphQL type BillingPlan
type BillingPlan struct {
	ID                  string               `json:"id"`
	CreatedAt           *time.Time           `json:"createdAt,omitempty"`
	UpdatedAt           *time.Time           `json:"updatedAt,omitempty"`
	Name                string               `json:"name"`
	GroupName           *string              `json:"groupName,omitempty"`
	Description         *string              `json:"description,omitempty"`
	IsActive            bool                 `json:"isActive"`
	StripeProductID     *string              `json:"stripeProductID,omitempty"`
	IsMultiQty          bool                 `json:"isMultiQty"`
	MaxQty              *int                 `json:"maxQty,omitempty"`
	IsCustom            bool                 `json:"isCustom"`
	CustomPriceID       *string              `json:"customPriceID,omitempty"`
	PlanType            *string              `json:"planType,omitempty"`
	HasAnnual           bool                 `json:"hasAnnual"`
	StripePriceID       *string              `json:"stripePriceID,omitempty"`
	StripePriceIdannual *string              `json:"stripePriceIdannual,omitempty"`
	Amount              *float64             `json:"amount,omitempty"`
	AmountAnnual        *float64             `json:"amountAnnual,omitempty"`
	Features            *json.RawMessage     `json:"features,omitempty"`
	SortOrder           *int                 `json:"sortOrder,omitempty"`
	BillingPlanFeatures []BillingPlanFeature `json:"billingPlanFeatures,omitempty"`
}

// BillingPlanConnection A connection to a list of items.
type BillingPlanConnection struct {
	Edges      []*BillingPlanEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo           `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// BillingPlanEdge An edge in a connection.
type BillingPlanEdge struct {
	Node   *BillingPlan `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string       `json:"cursor"`         // A cursor for use in pagination.
}

// BillingPlanFeature represents the GraphQL type BillingPlanFeature
type BillingPlanFeature struct {
	ID             string          `json:"id"`
	CreatedAt      *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time      `json:"updatedAt,omitempty"`
	FeatureID      *string         `json:"featureID,omitempty"`
	Value          int             `json:"value"`
	BillingPlanID  *string         `json:"billingPlanID,omitempty"`
	BillingPlan    *BillingPlan    `json:"billingPlan,omitempty"`
	BillingFeature *BillingFeature `json:"billingFeature,omitempty"`
}

// BillingPlanFeatureConnection A connection to a list of items.
type BillingPlanFeatureConnection struct {
	Edges      []*BillingPlanFeatureEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo                  `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                       `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// BillingPlanFeatureEdge An edge in a connection.
type BillingPlanFeatureEdge struct {
	Node   *BillingPlanFeature `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string              `json:"cursor"`         // A cursor for use in pagination.
}

// BillingPlanWspace represents the GraphQL type BillingPlanWspace
type BillingPlanWspace struct {
	ID            string       `json:"id"`
	CreatedAt     *time.Time   `json:"createdAt,omitempty"`
	UpdatedAt     *time.Time   `json:"updatedAt,omitempty"`
	BillingPlanID *string      `json:"billingPlanID,omitempty"`
	WorkspaceID   *string      `json:"workspaceID,omitempty"`
	BillingPlan   *BillingPlan `json:"billingPlan,omitempty"`
}

// BillingPlanWspaceConnection A connection to a list of items.
type BillingPlanWspaceConnection struct {
	Edges      []*BillingPlanWspaceEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo                 `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                      `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// BillingPlanWspaceEdge An edge in a connection.
type BillingPlanWspaceEdge struct {
	Node   *BillingPlanWspace `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string             `json:"cursor"`         // A cursor for use in pagination.
}

// CWorkspaceFeatureLimit represents the GraphQL type CWorkspaceFeatureLimit
type CWorkspaceFeatureLimit struct {
	ID               string          `json:"id"`
	CreatedAt        *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time      `json:"updatedAt,omitempty"`
	WorkspaceID      string          `json:"workspaceID"`
	BillingFeatureID *string         `json:"billingFeatureID,omitempty"`
	Available        int             `json:"available"`
	Used             int             `json:"used"`
	Balance          int             `json:"balance"`
	CalculatedAt     time.Time       `json:"calculatedAt"`
	Sources          *JsonSlice      `json:"sources,omitempty"`
	BillingFeature   *BillingFeature `json:"billingFeature,omitempty"`
}

// CWorkspaceFeatureLimitConnection A connection to a list of items.
type CWorkspaceFeatureLimitConnection struct {
	Edges      []*CWorkspaceFeatureLimitEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo                      `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                           `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// CWorkspaceFeatureLimitEdge An edge in a connection.
type CWorkspaceFeatureLimitEdge struct {
	Node   *CWorkspaceFeatureLimit `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string                  `json:"cursor"`         // A cursor for use in pagination.
}

// CWorkspaceSub represents the GraphQL type CWorkspaceSub
type CWorkspaceSub struct {
	ID                  string       `json:"id"`
	CreatedAt           *time.Time   `json:"createdAt,omitempty"`
	UpdatedAt           *time.Time   `json:"updatedAt,omitempty"`
	WorkspaceID         *string      `json:"workspaceID,omitempty"`
	Lock                *bool        `json:"lock,omitempty"`
	BillingPlanID       *string      `json:"billingPlanID,omitempty"`
	Status              *string      `json:"status,omitempty"`
	StripeStatus        *string      `json:"stripeStatus,omitempty"`
	IsSubscription      *bool        `json:"isSubscription,omitempty"`
	CheckoutSessionID   *string      `json:"checkoutSessionID,omitempty"`
	Amount              *float64     `json:"amount,omitempty"`
	Qty                 *int         `json:"qty,omitempty"`
	SubscriptionID      *string      `json:"subscriptionID,omitempty"`
	SubscriptionItemID  *string      `json:"subscriptionItemID,omitempty"`
	PlanInterval        *string      `json:"planInterval,omitempty"`
	PlanIntervalCount   *int         `json:"planIntervalCount,omitempty"`
	ItemID              *string      `json:"itemID,omitempty"`
	ItemPriceID         *string      `json:"itemPriceID,omitempty"`
	ItemName            *string      `json:"itemName,omitempty"`
	InvoiceID           *string      `json:"invoiceID,omitempty"`
	InvoiceLineID       *string      `json:"invoiceLineID,omitempty"`
	InvoiceNumber       *string      `json:"invoiceNumber,omitempty"`
	CurrentPeriodStart  *string      `json:"currentPeriodStart,omitempty"`
	CurrentPeriodEnd    *string      `json:"currentPeriodEnd,omitempty"`
	CancelAt            *string      `json:"cancelAt,omitempty"`
	CancelAtPeriodEnd   *string      `json:"cancelAtPeriodEnd,omitempty"`
	CanceledAt          *string      `json:"canceledAt,omitempty"`
	StripeCustomerID    *string      `json:"stripeCustomerID,omitempty"`
	StripeCustomerEmail *string      `json:"stripeCustomerEmail,omitempty"`
	LastCheckedAt       *time.Time   `json:"lastCheckedAt,omitempty"`
	BillingPlan         *BillingPlan `json:"billingPlan,omitempty"`
}

// CWorkspaceSubConnection A connection to a list of items.
type CWorkspaceSubConnection struct {
	Edges      []*CWorkspaceSubEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo             `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                  `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// CWorkspaceSubEdge An edge in a connection.
type CWorkspaceSubEdge struct {
	Node   *CWorkspaceSub `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string         `json:"cursor"`         // A cursor for use in pagination.
}

// Channel represents the GraphQL type Channel
type Channel struct {
	ID           string                `json:"id"`
	CreatedAt    *time.Time            `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time            `json:"updatedAt,omitempty"`
	Name         *string               `json:"name,omitempty"`
	IsPublic     *bool                 `json:"isPublic,omitempty"`
	GuestID      *string               `json:"guestID,omitempty"`
	OwnerID      *string               `json:"ownerID,omitempty"`
	WorkspaceID  *string               `json:"workspaceID,omitempty"`
	ChatbotID    *string               `json:"chatbotID,omitempty"`
	FolderID     *string               `json:"folderID,omitempty"`
	Messages     MessageConnection     `json:"messages"`
	Users        UserConnection        `json:"users"`
	Owner        *User                 `json:"owner,omitempty"`
	Chatbot      *Chatbot              `json:"chatbot,omitempty"`
	Folder       *Folder               `json:"folder,omitempty"`
	ChannelUsers ChannelUserConnection `json:"channelUsers"`
}

// ChannelConnection A connection to a list of items.
type ChannelConnection struct {
	Edges      []*ChannelEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo       `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int            `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ChannelEdge An edge in a connection.
type ChannelEdge struct {
	Node   *Channel `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string   `json:"cursor"`         // A cursor for use in pagination.
}

// ChannelUser represents the GraphQL type ChannelUser
type ChannelUser struct {
	ID          string     `json:"id"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	UserID      string     `json:"userID"`
	ChannelID   string     `json:"channelID"`
	WorkspaceID *string    `json:"workspaceID,omitempty"`
	ChatbotID   *string    `json:"chatbotID,omitempty"`
	User        User       `json:"user"`
	Channel     Channel    `json:"channel"`
}

// ChannelUserConnection A connection to a list of items.
type ChannelUserConnection struct {
	Edges      []*ChannelUserEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo           `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ChannelUserEdge An edge in a connection.
type ChannelUserEdge struct {
	Node   *ChannelUser `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string       `json:"cursor"`         // A cursor for use in pagination.
}

// Chatbot represents the GraphQL type Chatbot
type Chatbot struct {
	ID                 string                `json:"id"`
	CreatedAt          *time.Time            `json:"createdAt,omitempty"`
	UpdatedAt          *time.Time            `json:"updatedAt,omitempty"`
	Name               *string               `json:"name,omitempty"`
	ShortDescr         *string               `json:"shortDescr,omitempty"`
	Active             *bool                 `json:"active,omitempty"`
	IsPublic           *bool                 `json:"isPublic,omitempty"`
	Instruction        *string               `json:"instruction,omitempty"`
	Temperature        *float64              `json:"temperature,omitempty"`
	OverviewDescr      *string               `json:"overviewDescr,omitempty"`
	TotalChars         *int                  `json:"totalChars,omitempty"`
	Text               *string               `json:"text,omitempty"`
	ColorUserMessage   *string               `json:"colorUserMessage,omitempty"`
	InitialMessage1    *string               `json:"initialMessage1,omitempty"`
	InitialMessage2    *string               `json:"initialMessage2,omitempty"`
	ColorBubble        *string               `json:"colorBubble,omitempty"`
	ChatButtonAlign    *string               `json:"chatButtonAlign,omitempty"`
	DisplayName        *string               `json:"displayName,omitempty"`
	ChatIconURL        *string               `json:"chatIconURL,omitempty"`
	BotIconURL         *string               `json:"botIconURL,omitempty"`
	MessagePlaceholder *string               `json:"messagePlaceholder,omitempty"`
	Footer             *string               `json:"footer,omitempty"`
	Theme              *string               `json:"theme,omitempty"`
	AutoShowPopupAfter *int                  `json:"autoShowPopupAfter,omitempty"`
	AiModelID          *string               `json:"aiModelID,omitempty"`
	SbyteUserID        *string               `json:"sbyteUserID,omitempty"`
	AiUserID           *string               `json:"aiUserID,omitempty"`
	WorkspaceID        *string               `json:"workspaceID,omitempty"`
	IsFavorite         *bool                 `json:"isFavorite,omitempty"`
	IsDebug            *bool                 `json:"isDebug,omitempty"`
	CacheDisabled      *bool                 `json:"cacheDisabled,omitempty"`
	LeadNameEnabled    *bool                 `json:"leadNameEnabled,omitempty"`
	LeadEmailEnabled   *bool                 `json:"leadEmailEnabled,omitempty"`
	LeadPhoneEnabled   *bool                 `json:"leadPhoneEnabled,omitempty"`
	Users              []User                `json:"users,omitempty"`
	Channels           []Channel             `json:"channels,omitempty"`
	Folders            []Folder              `json:"folders,omitempty"`
	FuncTools          FuncToolConnection    `json:"funcTools"`
	AiModel            *AiModel              `json:"aiModel,omitempty"`
	ChatbotUsers       []ChatbotUser         `json:"chatbotUsers,omitempty"`
	ChatbotTools       ChatbotToolConnection `json:"chatbotTools"`
}

// ChatbotConnection A connection to a list of items.
type ChatbotConnection struct {
	Edges      []*ChatbotEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo       `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int            `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ChatbotEdge An edge in a connection.
type ChatbotEdge struct {
	Node   *Chatbot `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string   `json:"cursor"`         // A cursor for use in pagination.
}

// ChatbotTool represents the GraphQL type ChatbotTool
type ChatbotTool struct {
	ID          string     `json:"id"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	FuncToolID  string     `json:"funcToolID"`
	ChatbotID   string     `json:"chatbotID"`
	WorkspaceID *string    `json:"workspaceID,omitempty"`
	FuncTool    FuncTool   `json:"funcTool"`
	Chatbot     Chatbot    `json:"chatbot"`
}

// ChatbotToolConnection A connection to a list of items.
type ChatbotToolConnection struct {
	Edges      []*ChatbotToolEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo           `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ChatbotToolEdge An edge in a connection.
type ChatbotToolEdge struct {
	Node   *ChatbotTool `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string       `json:"cursor"`         // A cursor for use in pagination.
}

// ChatbotUser represents the GraphQL type ChatbotUser
type ChatbotUser struct {
	ID          string     `json:"id"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	UserID      string     `json:"userID"`
	ChatbotID   string     `json:"chatbotID"`
	WorkspaceID *string    `json:"workspaceID,omitempty"`
	User        User       `json:"user"`
	Chatbot     Chatbot    `json:"chatbot"`
}

// ChatbotUserConnection A connection to a list of items.
type ChatbotUserConnection struct {
	Edges      []*ChatbotUserEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo           `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ChatbotUserEdge An edge in a connection.
type ChatbotUserEdge struct {
	Node   *ChatbotUser `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string       `json:"cursor"`         // A cursor for use in pagination.
}

// CheckoutSession represents the GraphQL type CheckoutSession
type CheckoutSession struct {
	ID    *string `json:"id,omitempty"`
	Value *string `json:"value,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// CheckoutSessionVerify represents the GraphQL type CheckoutSessionVerify
type CheckoutSessionVerify struct {
	WorkspaceID     *string `json:"workspaceID,omitempty"`
	AlreadyVerified *bool   `json:"alreadyVerified,omitempty"`
}

// CreateChatbotResponse represents the GraphQL type CreateChatbotResponse
type CreateChatbotResponse struct {
	Chatbot   Chatbot   `json:"chatbot"`
	ItemGroup ItemGroup `json:"itemGroup"`
}

// Credential represents the GraphQL type Credential
type Credential struct {
	ID             string     `json:"id"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
	Name           *string    `json:"name,omitempty"`
	CredentialType *string    `json:"credentialType,omitempty"`
	Active         *bool      `json:"active,omitempty"`
	DbType         *string    `json:"dbType,omitempty"`
	DbName         *string    `json:"dbName,omitempty"`
	Host           *string    `json:"host,omitempty"`
	Port           *Uint      `json:"port,omitempty"`
	Username       *string    `json:"username,omitempty"`
	Password       *string    `json:"password,omitempty"`
	Secret         *string    `json:"secret,omitempty"`
	APIKey         *string    `json:"apiKey,omitempty"`
	WorkspaceID    *string    `json:"workspaceID,omitempty"`
	FuncTools      []FuncTool `json:"funcTools,omitempty"`
}

// CredentialConnection A connection to a list of items.
type CredentialConnection struct {
	Edges      []*CredentialEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo          `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int               `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// CredentialEdge An edge in a connection.
type CredentialEdge struct {
	Node   *Credential `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string      `json:"cursor"`         // A cursor for use in pagination.
}

// Folder represents the GraphQL type Folder
type Folder struct {
	ID           string     `json:"id"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
	Name         string     `json:"name"`
	ChatbotID    *string    `json:"chatbotID,omitempty"`
	OwnerID      *string    `json:"ownerID,omitempty"`
	Position     int        `json:"position"`
	Channels     []Channel  `json:"channels,omitempty"`
	Chatbot      *Chatbot   `json:"chatbot,omitempty"`
	Owner        *User      `json:"owner,omitempty"`
	ChannelCount int        `json:"channelCount"`
}

// FolderConnection A connection to a list of items.
type FolderConnection struct {
	Edges      []*FolderEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo      `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int           `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// FolderEdge An edge in a connection.
type FolderEdge struct {
	Node   *Folder `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string  `json:"cursor"`         // A cursor for use in pagination.
}

// FuncTool represents the GraphQL type FuncTool
type FuncTool struct {
	ID           string           `json:"id"`
	CreatedAt    *time.Time       `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time       `json:"updatedAt,omitempty"`
	Name         *string          `json:"name,omitempty"`
	FuncToolType *string          `json:"funcToolType,omitempty"`
	Active       *bool            `json:"active,omitempty"`
	Description  *string          `json:"description,omitempty"`
	SystemPrompt *string          `json:"systemPrompt,omitempty"`
	CredentialID *string          `json:"credentialID,omitempty"`
	Data         *json.RawMessage `json:"data,omitempty"`
	AiModelID    *string          `json:"aiModelID,omitempty"`
	MaxTokens    *int             `json:"maxTokens,omitempty"`
	Temperature  *float64         `json:"temperature,omitempty"`
	ItemGroupID  *string          `json:"itemGroupID,omitempty"`
	Limit        *int             `json:"limit,omitempty"`
	WorkspaceID  *string          `json:"workspaceID,omitempty"`
	Chatbots     []Chatbot        `json:"chatbots,omitempty"`
	Credential   *Credential      `json:"credential,omitempty"`
	FuncToolLogs []FuncToolLog    `json:"funcToolLogs,omitempty"`
	AiModel      *AiModel         `json:"aiModel,omitempty"`
	ItemGroup    *ItemGroup       `json:"itemGroup,omitempty"`
	ChatbotTools []ChatbotTool    `json:"chatbotTools,omitempty"`
}

// FuncToolConnection A connection to a list of items.
type FuncToolConnection struct {
	Edges      []*FuncToolEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo        `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int             `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// FuncToolEdge An edge in a connection.
type FuncToolEdge struct {
	Node   *FuncTool `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string    `json:"cursor"`         // A cursor for use in pagination.
}

// FuncToolLog represents the GraphQL type FuncToolLog
type FuncToolLog struct {
	ID          string           `json:"id"`
	CreatedAt   *time.Time       `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time       `json:"updatedAt,omitempty"`
	ToolCallID  *string          `json:"toolCallID,omitempty"`
	LogType     *string          `json:"logType,omitempty"`
	Msg         *string          `json:"msg,omitempty"`
	Body        *json.RawMessage `json:"body,omitempty"`
	FuncToolID  *string          `json:"funcToolID,omitempty"`
	ChannelID   *string          `json:"channelID,omitempty"`
	UserID      *string          `json:"userID,omitempty"`
	WorkspaceID *string          `json:"workspaceID,omitempty"`
	ChatbotID   *string          `json:"chatbotID,omitempty"`
	FuncTool    *FuncTool        `json:"funcTool,omitempty"`
}

// FuncToolLogConnection A connection to a list of items.
type FuncToolLogConnection struct {
	Edges      []*FuncToolLogEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo           `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// FuncToolLogEdge An edge in a connection.
type FuncToolLogEdge struct {
	Node   *FuncToolLog `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string       `json:"cursor"`         // A cursor for use in pagination.
}

// Guest represents the GraphQL type Guest
type Guest struct {
	ID          string     `json:"id"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	ExtUserID   *string    `json:"extUserID,omitempty"`
	FirstName   *string    `json:"firstName,omitempty"`
	LastName    *string    `json:"lastName,omitempty"`
	Email       *string    `json:"email,omitempty"`
	Ip          *string    `json:"ip,omitempty"`
	ChatbotID   *string    `json:"chatbotID,omitempty"`
	WorkspaceID *string    `json:"workspaceID,omitempty"`
}

// GuestConnection A connection to a list of items.
type GuestConnection struct {
	Edges      []*GuestEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo     `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int          `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// GuestEdge An edge in a connection.
type GuestEdge struct {
	Node   *Guest `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string `json:"cursor"`         // A cursor for use in pagination.
}

// HtmlToMarkdownResponse represents the GraphQL type HtmlToMarkdownResponse
type HtmlToMarkdownResponse struct {
	Content string `json:"content"`
}

// Item represents the GraphQL type Item
type Item struct {
	ID                string               `json:"id"`
	CreatedAt         *time.Time           `json:"createdAt,omitempty"`
	UpdatedAt         *time.Time           `json:"updatedAt,omitempty"`
	Name              *string              `json:"name,omitempty"`
	EmbeddingStatus   *ItemEmbeddingStatus `json:"embeddingStatus,omitempty"`
	EmbeddingMsg      *string              `json:"embeddingMsg,omitempty"`
	Content           *string              `json:"content,omitempty"`
	Filename          *string              `json:"filename,omitempty"`
	ContentChars      *int                 `json:"contentChars,omitempty"`
	AiModelID         *string              `json:"aiModelID,omitempty"`
	VecDims           *int                 `json:"vecDims,omitempty"`
	TotalTokens       *int                 `json:"totalTokens,omitempty"`
	Metadata          *json.RawMessage     `json:"metadata,omitempty"`
	ExtRef            *string              `json:"extRef,omitempty"`
	ExtID             *string              `json:"extID,omitempty"`
	ExtMetadata       *json.RawMessage     `json:"extMetadata,omitempty"`
	WorkspaceID       *string              `json:"workspaceID,omitempty"`
	ChatbotID         *string              `json:"chatbotID,omitempty"`
	ItemGroupSourceID *string              `json:"itemGroupSourceID,omitempty"`
	ItemGroupID       *string              `json:"itemGroupID,omitempty"`
}

// ItemConnection A connection to a list of items.
type ItemConnection struct {
	Edges      []*ItemEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo    `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int         `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ItemEdge An edge in a connection.
type ItemEdge struct {
	Node   *Item  `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string `json:"cursor"`         // A cursor for use in pagination.
}

// ItemGroup represents the GraphQL type ItemGroup
type ItemGroup struct {
	ID               string                    `json:"id"`
	CreatedAt        *time.Time                `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time                `json:"updatedAt,omitempty"`
	Name             *string                   `json:"name,omitempty"`
	ShortDescr       *string                   `json:"shortDescr,omitempty"`
	AiModelID        *string                   `json:"aiModelID,omitempty"`
	Dims             *int                      `json:"dims,omitempty"`
	HasPendingItems  *bool                     `json:"hasPendingItems,omitempty"`
	Locked           *bool                     `json:"locked,omitempty"`
	WorkspaceID      *string                   `json:"workspaceID,omitempty"`
	ItemGroupSources ItemGroupSourceConnection `json:"itemGroupSources"`
	FuncTools        []FuncTool                `json:"funcTools,omitempty"`
	AiModel          *AiModel                  `json:"aiModel,omitempty"`
}

// ItemGroupConnection A connection to a list of items.
type ItemGroupConnection struct {
	Edges      []*ItemGroupEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo         `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int              `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ItemGroupEdge An edge in a connection.
type ItemGroupEdge struct {
	Node   *ItemGroup `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string     `json:"cursor"`         // A cursor for use in pagination.
}

// ItemGroupSource represents the GraphQL type ItemGroupSource
type ItemGroupSource struct {
	ID                  string                         `json:"id"`
	CreatedAt           *time.Time                     `json:"createdAt,omitempty"`
	UpdatedAt           *time.Time                     `json:"updatedAt,omitempty"`
	ItemGroupID         *string                        `json:"itemGroupID,omitempty"`
	Name                *string                        `json:"name,omitempty"`
	Type                *ItemGroupSourceType           `json:"type,omitempty"`
	URL                 *string                        `json:"url,omitempty"`
	FileID              *string                        `json:"fileID,omitempty"`
	OriginalFileName    *string                        `json:"originalFileName,omitempty"`
	FileName            *string                        `json:"fileName,omitempty"`
	FileSize            *int                           `json:"fileSize,omitempty"`
	IsQueued            *bool                          `json:"isQueued,omitempty"`
	QueueID             *bool                          `json:"queueID,omitempty"`
	TrainingStatus      *ItemGroupSourceTrainingStatus `json:"trainingStatus,omitempty"`
	TrainingMsg         *string                        `json:"trainingMsg,omitempty"`
	Chars               *int                           `json:"chars,omitempty"`
	WorkspaceID         *string                        `json:"workspaceID,omitempty"`
	ExtID               *string                        `json:"extID,omitempty"`
	DeletedAt           *time.Time                     `json:"deletedAt,omitempty"`
	Body                *string                        `json:"body,omitempty"`
	Metadata            *json.RawMessage               `json:"metadata,omitempty"`
	TotalItems          *int                           `json:"totalItems,omitempty"`
	TotalItemsPending   *int                           `json:"totalItemsPending,omitempty"`
	TotalItemsError     *int                           `json:"totalItemsError,omitempty"`
	TotalItemsCompleted *int                           `json:"totalItemsCompleted,omitempty"`
	ItemGroup           *ItemGroup                     `json:"itemGroup,omitempty"`
}

// ItemGroupSourceConnection A connection to a list of items.
type ItemGroupSourceConnection struct {
	Edges      []*ItemGroupSourceEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo               `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int                    `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// ItemGroupSourceEdge An edge in a connection.
type ItemGroupSourceEdge struct {
	Node   *ItemGroupSource `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string           `json:"cursor"`         // A cursor for use in pagination.
}

// ItemGroupSourceSummary represents the GraphQL type ItemGroupSourceSummary
type ItemGroupSourceSummary struct {
	Type           string `json:"type"`
	Count          int    `json:"count"`
	TotalCompleted int    `json:"totalCompleted"`
	TotlaPending   int    `json:"totlaPending"`
	TotalError     int    `json:"totalError"`
}

// ItemInfo represents the GraphQL type ItemInfo
type ItemInfo struct {
	ID          string           `json:"id"`
	CreatedAt   string           `json:"createdAt"`
	Name        string           `json:"name"`
	FileName    string           `json:"fileName"`
	Metadata    *json.RawMessage `json:"metadata,omitempty"`
	ExtRef      *string          `json:"extRef,omitempty"`
	ExtID       *string          `json:"extID,omitempty"`
	ExtMetadata *json.RawMessage `json:"extMetadata,omitempty"`
	WorkspaceID string           `json:"workspaceID"`
}

// Lead represents the GraphQL type Lead
type Lead struct {
	ID          string     `json:"id"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Email       *string    `json:"email,omitempty"`
	Phone       *string    `json:"phone,omitempty"`
	Company     *string    `json:"company,omitempty"`
	Ip          *string    `json:"ip,omitempty"`
	GuestUserID *string    `json:"guestUserID,omitempty"`
	ChatbotID   *string    `json:"chatbotID,omitempty"`
	WorkspaceID *string    `json:"workspaceID,omitempty"`
}

// LeadConnection A connection to a list of items.
type LeadConnection struct {
	Edges      []*LeadEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo    `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int         `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// LeadEdge An edge in a connection.
type LeadEdge struct {
	Node   *Lead  `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string `json:"cursor"`         // A cursor for use in pagination.
}

// Message represents the GraphQL type Message
type Message struct {
	ID               string           `json:"id"`
	CreatedAt        *time.Time       `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time       `json:"updatedAt,omitempty"`
	Role             *string          `json:"role,omitempty"`
	Msgid            *string          `json:"msgid,omitempty"`
	Content          *json.RawMessage `json:"content,omitempty"`
	Parts            *JsonSlice       `json:"parts,omitempty"`
	PromptTokens     *int             `json:"promptTokens,omitempty"`
	CompletionTokens *int             `json:"completionTokens,omitempty"`
	TotalTokens      *int             `json:"totalTokens,omitempty"`
	UserID           *string          `json:"userID,omitempty"`
	ChannelID        *string          `json:"channelID,omitempty"`
	WorkspaceID      *string          `json:"workspaceID,omitempty"`
	ChatbotID        *string          `json:"chatbotID,omitempty"`
	Channel          *Channel         `json:"channel,omitempty"`
	User             *User            `json:"user,omitempty"`
}

// MessageConnection A connection to a list of items.
type MessageConnection struct {
	Edges      []*MessageEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo       `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int            `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// MessageEdge An edge in a connection.
type MessageEdge struct {
	Node   *Message `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string   `json:"cursor"`         // A cursor for use in pagination.
}

// Node An object with an ID.
// Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
type Node interface {
	IsNode()
}

// PageInfo Information about pagination in a connection.
// https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`           // When paginating forwards, are there more items?
	HasPreviousPage bool    `json:"hasPreviousPage"`       // When paginating backwards, are there more items?
	StartCursor     *string `json:"startCursor,omitempty"` // When paginating backwards, the cursor to continue.
	EndCursor       *string `json:"endCursor,omitempty"`   // When paginating forwards, the cursor to continue.
}

// Student represents the GraphQL type Student
type Student struct {
	Name string `json:"name"`
}

// TmpItem represents the GraphQL type TmpItem
type TmpItem struct {
	ID                string               `json:"id"`
	CreatedAt         *time.Time           `json:"createdAt,omitempty"`
	UpdatedAt         *time.Time           `json:"updatedAt,omitempty"`
	ItemID            *string              `json:"itemID,omitempty"`
	BatchID           *string              `json:"batchID,omitempty"`
	EmbeddingStatus   *ItemEmbeddingStatus `json:"embeddingStatus,omitempty"`
	EmbeddingMsg      *string              `json:"embeddingMsg,omitempty"`
	WorkspaceID       string               `json:"workspaceID"`
	ItemGroupID       *string              `json:"itemGroupID,omitempty"`
	ItemGroupSourceID *string              `json:"itemGroupSourceID,omitempty"`
}

// UrlToHtmlResponse represents the GraphQL type UrlToHtmlResponse
type UrlToHtmlResponse struct {
	Content    string `json:"content"`
	StatusCode *int   `json:"statusCode,omitempty"`
}

// User represents the GraphQL type User
type User struct {
	ID           string        `json:"id"`
	CreatedAt    *time.Time    `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time    `json:"updatedAt,omitempty"`
	Type         *UserType     `json:"type,omitempty"`
	ExtUserID    *string       `json:"extUserID,omitempty"`
	FirstName    *string       `json:"firstName,omitempty"`
	LastName     *string       `json:"lastName,omitempty"`
	Email        *string       `json:"email,omitempty"`
	Ip           *string       `json:"ip,omitempty"`
	WorkspaceID  *string       `json:"workspaceID,omitempty"`
	MyChannels   []Channel     `json:"myChannels,omitempty"`
	Channels     []Channel     `json:"channels,omitempty"`
	Messages     []Message     `json:"messages,omitempty"`
	Chatbots     []Chatbot     `json:"chatbots,omitempty"`
	Folders      []Folder      `json:"folders,omitempty"`
	ChannelUsers []ChannelUser `json:"channelUsers,omitempty"`
	ChatbotUsers []ChatbotUser `json:"chatbotUsers,omitempty"`
}

// UserConnection A connection to a list of items.
type UserConnection struct {
	Edges      []*UserEdge `json:"edges,omitempty"` // A list of edges.
	PageInfo   PageInfo    `json:"pageInfo"`        // Information to aid in pagination.
	TotalCount int         `json:"totalCount"`      // Identifies the total count of items in the connection.
}

// UserEdge An edge in a connection.
type UserEdge struct {
	Node   *User  `json:"node,omitempty"` // The item at the end of the edge.
	Cursor string `json:"cursor"`         // A cursor for use in pagination.
}

// WorkspaceAppInstallation represents the GraphQL type WorkspaceAppInstallation
type WorkspaceAppInstallation struct {
	ID          string      `json:"id"`
	App         AppStoreApp `json:"app"`
	WorkspaceID string      `json:"workspaceID"`
	Status      string      `json:"status"`
	InstalledAt time.Time   `json:"installedAt"`
}

// WorkspaceDetail represents the GraphQL type WorkspaceDetail
type WorkspaceDetail struct {
	ID            string  `json:"id"`
	Name          *string `json:"name,omitempty"`
	TotalAgents   int     `json:"totalAgents"`
	TotalDatasets int     `json:"totalDatasets"`
	TotalUsers    int     `json:"totalUsers"`
	TotalChannels int     `json:"totalChannels"`
	TotalMessages int     `json:"totalMessages"`
}
