// Code generated by ent, DO NOT EDIT.

package enums

// AiModelOrderField Properties by which AiModel connections can be ordered.

type AiModelOrderField string

// AiModelOrderField enum values
const (
	AiModelOrderFieldCreatedAt    AiModelOrderField = "CREATED_AT"
	AiModelOrderFieldProviderName AiModelOrderField = "PROVIDER_NAME"
	AiModelOrderFieldModelID      AiModelOrderField = "MODEL_ID"
	AiModelOrderFieldStatus       AiModelOrderField = "STATUS"
)

// ChannelOrderField Properties by which Channel connections can be ordered.

type ChannelOrderField string

// ChannelOrderField enum values
const (
	ChannelOrderFieldCreatedAt ChannelOrderField = "CREATED_AT"
	ChannelOrderFieldName      ChannelOrderField = "NAME"
)

// ChannelUserOrderField Properties by which ChannelUser connections can be ordered.

type ChannelUserOrderField string

// ChannelUserOrderField enum values
const (
	ChannelUserOrderFieldCreatedAt ChannelUserOrderField = "CREATED_AT"
)

// ChatbotOrderField Properties by which Chatbot connections can be ordered.

type ChatbotOrderField string

// ChatbotOrderField enum values
const (
	ChatbotOrderFieldCreatedAt  ChatbotOrderField = "CREATED_AT"
	ChatbotOrderFieldName       ChatbotOrderField = "NAME"
	ChatbotOrderFieldIsFavorite ChatbotOrderField = "IS_FAVORITE"
)

// ChatbotToolOrderField Properties by which ChatbotTool connections can be ordered.

type ChatbotToolOrderField string

// ChatbotToolOrderField enum values
const (
	ChatbotToolOrderFieldCreatedAt ChatbotToolOrderField = "CREATED_AT"
)

// ChatbotUserOrderField Properties by which ChatbotUser connections can be ordered.

type ChatbotUserOrderField string

// ChatbotUserOrderField enum values
const (
	ChatbotUserOrderFieldCreatedAt ChatbotUserOrderField = "CREATED_AT"
)

// CredentialOrderField Properties by which Credential connections can be ordered.

type CredentialOrderField string

// CredentialOrderField enum values
const (
	CredentialOrderFieldCreatedAt CredentialOrderField = "CREATED_AT"
)

// FolderOrderField Properties by which Folder connections can be ordered.

type FolderOrderField string

// FolderOrderField enum values
const (
	FolderOrderFieldCreatedAt FolderOrderField = "CREATED_AT"
	FolderOrderFieldName      FolderOrderField = "NAME"
	FolderOrderFieldPosition  FolderOrderField = "POSITION"
)

// FuncToolLogOrderField Properties by which FuncToolLog connections can be ordered.

type FuncToolLogOrderField string

// FuncToolLogOrderField enum values
const (
	FuncToolLogOrderFieldCreatedAt FuncToolLogOrderField = "CREATED_AT"
)

// FuncToolOrderField Properties by which FuncTool connections can be ordered.

type FuncToolOrderField string

// FuncToolOrderField enum values
const (
	FuncToolOrderFieldCreatedAt FuncToolOrderField = "CREATED_AT"
)

// GuestOrderField Properties by which Guest connections can be ordered.

type GuestOrderField string

// GuestOrderField enum values
const (
	GuestOrderFieldCreatedAt GuestOrderField = "CREATED_AT"
)

// ItemGroupOrderField Properties by which ItemGroup connections can be ordered.

type ItemGroupOrderField string

// ItemGroupOrderField enum values
const (
	ItemGroupOrderFieldCreatedAt ItemGroupOrderField = "CREATED_AT"
)

// ItemGroupSourceOrderField Properties by which ItemGroupSource connections can be ordered.

type ItemGroupSourceOrderField string

// ItemGroupSourceOrderField enum values
const (
	ItemGroupSourceOrderFieldCreatedAt ItemGroupSourceOrderField = "CREATED_AT"
	ItemGroupSourceOrderFieldName      ItemGroupSourceOrderField = "NAME"
)

// ItemOrderField Properties by which Item connections can be ordered.

type ItemOrderField string

// ItemOrderField enum values
const (
	ItemOrderFieldCreatedAt ItemOrderField = "CREATED_AT"
	ItemOrderFieldName      ItemOrderField = "NAME"
)

// LeadOrderField Properties by which Lead connections can be ordered.

type LeadOrderField string

// LeadOrderField enum values
const (
	LeadOrderFieldCreatedAt LeadOrderField = "CREATED_AT"
)

// MessageOrderField Properties by which Message connections can be ordered.

type MessageOrderField string

// MessageOrderField enum values
const (
	MessageOrderFieldCreatedAt MessageOrderField = "CREATED_AT"
)

// OrderDirection Possible directions in which to order a list of items when provided an `orderBy` argument.

type OrderDirection string

// OrderDirection enum values
const (
	// Specifies an ascending order for a given `orderBy` argument.
	OrderDirectionAsc OrderDirection = "ASC"
	// Specifies a descending order for a given `orderBy` argument.
	OrderDirectionDesc OrderDirection = "DESC"
)

// TmpItemOrderField Properties by which TmpItem connections can be ordered.

type TmpItemOrderField string

// TmpItemOrderField enum values
const (
	TmpItemOrderFieldCreatedAt TmpItemOrderField = "CREATED_AT"
)

// UserOrderField Properties by which User connections can be ordered.

type UserOrderField string

// UserOrderField enum values
const (
	UserOrderFieldCreatedAt UserOrderField = "CREATED_AT"
)
