package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// Writer handles writing generated files to disk
type Writer struct {
	outputDir string
}

// NewWriter creates a new Writer
func NewWriter(outputDir string) *Writer {
	return &Writer{outputDir: outputDir}
}

// WriteFile writes content to a file in the output directory
// Supports subdirectories (e.g., "fields/chatbot.go")
func (w *Writer) WriteFile(filename, content string) error {
	fullPath := filepath.Join(w.outputDir, filename)

	// Ensure parent directory exists (handles subdirectories like fields/, queries/, mutations/)
	parentDir := filepath.Dir(fullPath)
	if err := os.MkdirAll(parentDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", parentDir, err)
	}

	// Format Go code
	formatted, err := format.Source([]byte(content))
	if err != nil {
		// If formatting fails, write unformatted content for debugging
		fmt.Printf("Warning: failed to format %s: %v\n", filename, err)
		formatted = []byte(content)
	}

	if err := os.WriteFile(fullPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filename, err)
	}

	return nil
}

// WriteGoMod writes the go.mod file
func (w *Writer) WriteGoMod(modulePath, packageName string) error {
	if modulePath == "" {
		modulePath = packageName
	}

	content := fmt.Sprintf(`module %s

go 1.21
`, modulePath)

	filepath := filepath.Join(w.outputDir, "go.mod")

	if err := os.MkdirAll(w.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write go.mod: %w", err)
	}

	return nil
}

// FormatGoCode formats Go source code
func FormatGoCode(code string) (string, error) {
	formatted, err := format.Source([]byte(code))
	if err != nil {
		return code, err
	}
	return string(formatted), nil
}

// WriteFormattedFile writes formatted Go code to a file
func (w *Writer) WriteFormattedFile(filename, content string) error {
	formatted, err := FormatGoCode(content)
	if err != nil {
		return fmt.Errorf("failed to format %s: %w", filename, err)
	}

	return w.WriteFile(filename, formatted)
}

// EnsureDir ensures the output directory exists
func (w *Writer) EnsureDir() error {
	return os.MkdirAll(w.outputDir, 0755)
}

// OutputPath returns the full path for a file in the output directory
func (w *Writer) OutputPath(filename string) string {
	return filepath.Join(w.outputDir, filename)
}

// Exists checks if a file exists in the output directory
func (w *Writer) Exists(filename string) bool {
	path := filepath.Join(w.outputDir, filename)
	_, err := os.Stat(path)
	return err == nil
}

// Clean removes all files in the output directory
func (w *Writer) Clean() error {
	if _, err := os.Stat(w.outputDir); os.IsNotExist(err) {
		return nil
	}

	entries, err := os.ReadDir(w.outputDir)
	if err != nil {
		return fmt.Errorf("failed to read output directory: %w", err)
	}

	for _, entry := range entries {
		path := filepath.Join(w.outputDir, entry.Name())
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("failed to remove %s: %w", path, err)
		}
	}

	return nil
}

// WriteFileWithHeader writes a file with a generated header
func (w *Writer) WriteFileWithHeader(filename, content string) error {
	header := `// Code generated by gqlsdk. DO NOT EDIT.

`
	return w.WriteFile(filename, header+content)
}

// BufferedWriter collects content before writing
type BufferedWriter struct {
	buffer bytes.Buffer
}

// NewBufferedWriter creates a new BufferedWriter
func NewBufferedWriter() *BufferedWriter {
	return &BufferedWriter{}
}

// Write writes to the buffer
func (bw *BufferedWriter) Write(p []byte) (n int, err error) {
	return bw.buffer.Write(p)
}

// WriteString writes a string to the buffer
func (bw *BufferedWriter) WriteString(s string) (n int, err error) {
	return bw.buffer.WriteString(s)
}

// String returns the buffer content as a string
func (bw *BufferedWriter) String() string {
	return bw.buffer.String()
}

// Reset resets the buffer
func (bw *BufferedWriter) Reset() {
	bw.buffer.Reset()
}
