// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Node interface {
	IsNode()
	GetID() string
}

type SearchResult interface {
	IsSearchResult()
}

type Mutation struct {
}

type NewTodo struct {
	Text     string   `json:"text"`
	UserID   string   `json:"userID"`
	Priority *int32   `json:"priority,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type Query struct {
}

type Todo struct {
	ID       string   `json:"id"`
	Text     string   `json:"text"`
	Done     bool     `json:"done"`
	Priority *int32   `json:"priority,omitempty"`
	Tags     []string `json:"tags"`
	User     *User    `json:"user"`
}

func (Todo) IsSearchResult() {}

type TodoConnection struct {
	Edges      []*TodoEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int32       `json:"totalCount"`
}

type TodoEdge struct {
	Cursor string `json:"cursor"`
	Node   *Todo  `json:"node"`
}

type TodoFilter struct {
	TextContains *string `json:"textContains,omitempty"`
	Done         *bool   `json:"done,omitempty"`
	MinPriority  *int32  `json:"minPriority,omitempty"`
	HasTag       *string `json:"hasTag,omitempty"`
}

type UpdateTodoInput struct {
	Text     *string  `json:"text,omitempty"`
	Done     *bool    `json:"done,omitempty"`
	Priority *int32   `json:"priority,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
	Role  Role    `json:"role"`
}

func (User) IsSearchResult() {}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
	RoleGuest Role = "GUEST"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
	RoleGuest,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser, RoleGuest:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
